### ISSUE TITLE
Can not render web components

### ISSUE THREAD

**Issue by maxcodefaster** [QwikDev/qwik#1714]
### Qwik Version

0.10.0

### Operating System (or Browser)

MacOS Chrome

### Which component is affected?

Qwik Rollup / Vite plugin

### Expected Behaviour

Should render Webcomponents exported as ES6 modules 
https://sap.github.io/ui5-webcomponents/

### Actual Behaviour

Throws: 

```sh
[vite] Internal server error: `line` must be greater than 0 (lines start at line 1)
at originalPositionFor$1 (file:///Users/.../node_modules/vite/dist/node/chunks/dep-a713b95d.js:10041:19)
    at file:///Users/.../node_modules/vite/dist/node/chunks/dep-a713b95d.js:53241:25
    at String.replace (<anonymous>)
    at file:///Users/.../node_modules/vite/dist/node/chunks/dep-a713b95d.js:53232:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (file:///Users/.../node_modules/vite/dist/node/chunks/dep-a713b95d.js:53231:10)
    at instantiateModule 
```

**Comment by manucorporat** [comment]
We need a repo case, web components dont have SSR in their specification btw.

**Comment by maxcodefaster** [comment]
> We need a repo case, web components dont have SSR in their specification btw.

Yeah I guess thats what the problem boils down to. Any way to import webcomponents on client side? I tried to `await import()` but that did not work.

**Comment by shairez** [comment]
I'm closing this as it doesn't have a repro

Please feel free to re-open once you add a link to a reproduction repository

Thanks

**Comment by njoguamos** [comment]
> > We need a repo case, web components dont have SSR in their specification btw.
> 
> Yeah I guess thats what the problem boils down to. Any way to import webcomponents on client side? I tried to `await import()` but that did not work.

Did you get a solution?

**Comment by PatrickJS** [comment]
move all qwik web components comments here
https://github.com/QwikDev/qwik/issues/6451
