### ISSUE TITLE
[📖] Qwik Environment Variables -- Lifecycle Demystified

### ISSUE THREAD

**Issue by n8sabes** [QwikDev/qwik#2645]
### Suggestion

*This Issue is to capture the discord conversation on Environment Variables w/ related video and repo for tracking purposes.*

---

The attached video explanation and code repo is intended as a community resource that provides insights into environment variables in the Qwik lifecycle, how they are loaded from the `.env` file, and log them as they flow through the application's lifecycle (between server and client).

The repo allows the developer to explore what is provided as defaults vs `loadEnv` and `dotenv` library functions, their scope and depth.

**NOTE:** This is not a comprehensive guide on environment variables, nor does it cover all the 3rd-Party hosting scenarios, but gives insights that can be applied to all environments. *Be sure to exclude `.env` files from your source control. The repo also contains an example to point elsewhere in the filesystem for the `.env.mode` files, such as the user/home directory.*

**Video:** https://youtu.be/NPf39RWc8LM

**Repo:** https://github.com/n8sabes/qwik-env-vars-demystified

**Comment by PatrickJS** [comment]
merging with https://github.com/QwikDev/qwik/issues/3642
