### ISSUE TITLE
[🐞] Console Ninja support

### ISSUE THREAD

**Issue by EamonHeffernan** [QwikDev/qwik#2936]
### Which component is affected?

Qwik Runtime

### Describe the bug

Currently Console Ninja is not correctly supported by Qwik. Is is possible that some information could be provided to the Console Ninja team in how to best implement their extension with Qwik.
My understanding of the Console Ninja extension is that it injects a function at the end of files in order to override the default behaviour of console.log. This doesn't work with Qwik however due to the need to export the function. Adding a blanket export to every instance of the function did not work either and there is an open issue here: https://github.com/wallabyjs/console-ninja/issues/102

I understand if it is not a high priority as it is third party, but me and a couple users on discord were incredibly confused by some rather unclear console messages caused by the failed integration until I worked out the source.

### Reproduction

.

### Steps to reproduce

Install console ninja @ v0.0.74 for the error caused by not having Qwik integration, and console ninja @ v0.0.75 for the failed fix to the issue.

### System Info

```shell
System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1
    Memory: 40.39 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.1 - ~/.nvm/versions/node/v19.0.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.0.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v19.0.1/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0.1
    Firefox Developer Edition: 110.0
    Safari: 16.3
```

**Comment by gioboa** [comment]
Is this issue still valid?
