### ISSUE TITLE
[🐞] Regex not using constructor does not work as expected

### ISSUE THREAD

**Issue by jweb89** [QwikDev/qwik#3123]
### Which component is affected?

Qwik Runtime

### Describe the bug

When upgrading from qwik 18 to 19 I started running into this error.

```
# Fatal error in , line 0
# Fatal JavaScript invalid size error 169220804
#
#
#
#FailureMessage Object: 0x16f3b9598
 1: 0x100b4db3c node::NodePlatform::GetStackTracePrinter()::$_3::__invoke() [/Users/joshweber/.nvm/versions/node/v16.18.1/bin/node]
 2: 0x1018e7b34 V8_Fatal(char const*, ...) [/Users/joshweber/.nvm/versions/node/v16.18.1/bin/node]
 3: 0x100d8adb8 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/Users/joshweber/.nvm/versions/node/v16.18.1/bin/node]
 4: 0x100ee9be4 v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::GrowCapacity(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/Users/joshweber/.nvm/versions/node/v16.18.1/bin/node]
 5: 0x1010bda2c v8::internal::Runtime_GrowArrayElements(int, unsigned long*, v8::internal::Isolate*) [/Users/joshweber/.nvm/versions/node/v16.18.1/bin/node]
```

Turns out it was because of an infinite loop caused by regex. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec

### Reproduction

https://stackblitz.com/edit/qwik-starter-r64tkt?file=src%2Froutes%2Findex.tsx,index.js

### Steps to reproduce

Uncomment line 8 and comment line 7 of the index route. You can also run `node index.js` in the terminal to see how it should be running using constructor and non constructor.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: 0.19.2 => 0.19.2 
    @builder.io/qwik-city: 0.4.0 => 0.4.0 
    undici: ^5.16.0 => 5.16.0 
    vite: ^4.0.4 => 4.0.4
```

### Additional Information

Sorry in advance. This is a really weird bug that seems so unrelated to qwik. I'm not sure if this is even caused by qwik or one of the dependencies qwik is using

**Comment by manucorporat** [comment]
This is so weird, i cant wrap my head about how this can possibly be happening

**Comment by jweb89** [comment]
I agree. Took me a few hours to figure out and it’s a pretty easy fix for us to use constructor, but figured I should file for tracking purposes.

**Comment by gioboa** [comment]
Hi @jweb89, thanks for opening this issue, with the latest version of Qwik is it still a valid issue?
