### ISSUE TITLE
[📖] Docs and error message: SSR should warn when changing rendered state

### ISSUE THREAD

**Issue by fabian-hiller** [QwikDev/qwik#3193]
### Which component is affected?

Qwik Runtime

### Describe the bug

When a store is initialized in a parent component on the server side and the state is read in the JSX area, Qwik "places" a subscription on the state. If now in the same process in the JSX area an inline-component is included on the server side, which in turn contains a normal component and the state of the store is changed in it via `useTask$`, Qwik does not subsequently update the subscription in the parent element.

In simple words: In the following reproduction Qwik places a subscription on the `form.field.active` signal in line 28 in the `routes/index.tsx` file. In line 35 in the `components/Field.tsx` file, this signal is modified. Now Qwik should set the subscription in line 28 in the `routes/index.tsx` file to the `form.field.value` signal. Since this does not happen, an invalid state is serialized which causes bugs on the client side and in this example the value of the field is not printed when it is changed.

### Reproduction

https://stackblitz.com/edit/qwik-starter-m7l69x?file=src%2Froutes%2Findex.tsx%3AL28-L28,src%2Fcomponents%2FField.tsx%3AL35-L35

### Steps to reproduce

Just open the reproduction link. StackBlitz should automatically run `npm install && npm start`. After that, type something into the `<input />` element. If now everything would run smoothly, the current value of the field should be displayed under the field after `Value: `.

### System Info

```shell
I think that this information is not relevant here.
```

**Comment by gioboa** [comment]
Hi @fabian-hiller, thanks for opening this issue. a lot of things happened during this months and the docs was updated as well, the limitation of inline components are described here [docs](https://qwik.builder.io/docs/components/overview/#limitations)
Are you still looking for the solution to this problem?

**Comment by fabian-hiller** [comment]
As a workaround I use `useVisibleTask$`. However, this requires the Qwik application to be resume immediately and therefore hurts the startup performance. I think it should be technically possible to solve this problem so I can change the implementation back to `useTask$`.

**Comment by mhevery** [comment]
I don't think this is something which we will fix any time soon, as it would be a very complex refactoring...

**Comment by wmertens** [comment]
@fabian-hiller so what solution would you prefer?

**Comment by wmertens** [comment]
@fabian-hiller right now you could use the `isServer` build variable to not set the active to false again.

I suppose it's a little bit of an issue that setting the `active` to false doesn't cause the component to re-render on the client, I'm thinking that's more of a philosophy vs correctness decision.

**Comment by fabian-hiller** [comment]
Thanks for your research! I will take this into account when I revise Modular Forms in January.

**Comment by wmertens** [comment]
I think the correct solution for Qwik here is to show a detailed warning on SSR when this happens and which code caused it.

The alternative of running tasks on client load is not The Qwik Way.

**Comment by fabian-hiller** [comment]
Yes, I agree that Qwik should either show a warning or support this kind of implementation. Or do you think that the use of `isServer` is required for such an implementation anyway?

**Comment by wmertens** [comment]
Right I think all the cases are covered with `isServer`, probably needs some documentation.

I'm convinced that the situation should be detected and avoided, not supported.

**Comment by maiieul** [comment]
@wmertens So Qwik should detect when this happens, throw a proper error message to tell the user to add isServer to prevent this from happening?

**Comment by shairez** [comment]
@Varixo in V2 are we throwing an error for this type of situations?

**Comment by Varixo** [comment]
> @Varixo in V2 are we throwing an error for this type of situations?

I don't think so, but it looks like it is working fine in v2?
https://qwikdev-build-v2.qwik-8nx.pages.dev/playground/#f=7VdNT9wwEL3zK3xAbCLS0FbiUDfJjVWFaCuVHrihBRIpgHZXLCBWlv8782bGjqOFFRy4sYds7NjjmTdvPpyS5vBw8BQt2C3oMdAAI2LfcqpwYgyG4z8UZX3n1FfsbGGbHsPud%2Bb49Ox1t1%2Bvnr7cUdKnVAJYecu0b2%2BvoMyKQIWuKFrWTOnJevyE5sjY5FFrMu1UsNAgbh9aq%2F0IFDZUwblh2LUjA6usfSTDrTnCX2Go4iForfn1%2F%2FcJbziSGXbq46K%2FojgwxvOQTCr1M%2BM8pgPrDz441ryIyhpPVkTjWBIoUp30XXu5ppzK62uHpxdvurA3E%2FuihVhTdhBW8ozYmlpLoX3%2BRvOCbIE6FUtm6FYZAwP8fC4H%2BtzDgoNoQrND1BM%2FxrmtvtyAb0CjTgg6gMTSmkzRVY9AdGz36BMK1PxhmXwd2TYjDlDVrbmAi026I8mHPJt0mZMgdNEZETDJddlLorvZ7UplI3%2BGZ8iyiC6KYEmuAQHhfwBHIeOuyGrHBQhxTiC8HGfNxYLUnM3lvFEU8NEjnLdWAXECQ1sP%2FXjUqZGkNuDDun0N9BvplurHaIRVUcNJP%2B%2FvqahOwhevtJI%2FR6q2SyttFogGqIb0qpm1kjvL0Kq7LK8bdgmrt7%2Fvm3%2BtpP94wYmXJ3PTriXkZLUG3vhmRSOJ6jRAnaQeRq7q%2BVLiyrLkSU%2Bu9dUBb0qEUIvXuOPTv39K8U3frTPJEejwCvM9p01YFBN7er3DO7fkBPAm4%2Fb2NqKXhMX98ZUKBKrDqyX924%2Fk0vqekj66zH4W9I8o6M8

**Comment by fabian-hiller** [comment]
That would be even better 🙏
