### ISSUE TITLE
[✨] Upgrade to the new version from command line

### ISSUE THREAD

**Issue by kokecar11** [QwikDev/qwik#3405]
### Is your feature request related to a problem?

After starting a project, and check in a couple of weeks you have already changed the version of qwik, qwik-city and more qwik core dependencies, it would be good to implement in the command line a package updater that is obviously compatible with that stable version.

### Describe the solution you'd like

Create a function in the qwik command line to upgrade packages to the latest version.

### Describe alternatives you've considered

No

**Comment by JerryWu1234** [comment]
I can pick this task but Who can tell me more detail what I have to do?

**Comment by shairez** [comment]
Thanks @kokecar11 

Yes we do have it on our plans for after V2

For V2 we'll have a `migrate` command -  #6810

And after that we're planning to implement a simple `upgrade` command as this issue describes

Thanks @JerryWu1234 , it's best to talk with @dmitry-stepanenko about it as he is leading this effort
