### ISSUE TITLE
[🐞] useStore: cannot reference itself in a function inside of it

### ISSUE THREAD

**Issue by samijaber** [QwikDev/qwik#3446]
### Which component is affected?

Qwik Runtime

### Describe the bug

```tsx
import {
  $,
  component$,
  useStore,
} from '@builder.io/qwik';

type State = { foo: number };

export default component$(() => {
  const contextStore = useStore(() => ({
    state: { foo: 123 } as State,
    setState: $((newState: State) => {
      contextStore.state = newState;
    }),
  }))

  return (
    <div>
      <div>Parent foo: {contextStore.state.foo}</div>
    </div>
  );
});
```

gives the following error:

```
ReferenceError: Cannot access 'contextStore' before initialization at eval (eval at H (https://qwik.builder.io/repl/repl-sw.js:12:3820), <anonymous>:23:17)
at invoke (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:1428:30)
at useStore (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:8411:50)
at inlinedQrlDEV.file (eval at H (https://qwik.builder.io/repl/repl-sw.js:12:3820), <anonymous>:10:26)
at AsyncFunction.invoke (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:1428:30)
at eval (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:7898:39)
at then (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:390:60)
at eval (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:7887:24)
at eval (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:2561:31)
at safeCall (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:377:29)
```

### Reproduction

[link](https://qwik.builder.io/playground#version=0.23.0&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTVDbiUyMCUyMCUyNCUyQyU1Q24lMjAlMjBjb21wb25lbnQlMjQlMkMlNUNuJTIwJTIwdXNlU3RvcmUlMkMlNUNuJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbnR5cGUlMjBTdGF0ZSUyMCUzRCUyMCU3QiUyMGZvbyUzQSUyMG51bWJlciUyMCU3RCUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGNvbXBvbmVudCUyNCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMGNvbnRleHRTdG9yZSUyMCUzRCUyMHVzZVN0b3JlKCgpJTIwJTNEJTNFJTIwKCU3QiU1Q24lMjAlMjAlMjAlMjBzdGF0ZSUzQSUyMCU3QiUyMGZvbyUzQSUyMDEyMyUyMCU3RCUyMGFzJTIwU3RhdGUlMkMlNUNuJTIwJTIwJTIwJTIwc2V0U3RhdGUlM0ElMjAlMjQoKG5ld1N0YXRlJTNBJTIwU3RhdGUpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGNvbnRleHRTdG9yZS5zdGF0ZSUyMCUzRCUyMG5ld1N0YXRlJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCklMkMlNUNuJTIwJTIwJTdEKSklNUNuJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDZGl2JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2RpdiUzRVBhcmVudCUyMGZvbyUzQSUyMCU3QmNvbnRleHRTdG9yZS5zdGF0ZS5mb28lN0QlM0MlMkZkaXYlM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGZGl2JTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEKSUzQiU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGZW50cnkuc2VydmVyLnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjByZW5kZXJUb1N0cmluZyUyQyUyMFJlbmRlck9wdGlvbnMlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJTJGc2VydmVyJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBSb290JTIwJTdEJTIwZnJvbSUyMCcuJTJGcm9vdCclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMChvcHRzJTNBJTIwUmVuZGVyT3B0aW9ucyklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwcmVuZGVyVG9TdHJpbmcoJTNDUm9vdCUyMCUyRiUzRSUyQyUyMG9wdHMpJTNCJTVDbiU3RCU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcm9vdC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwQXBwJTIwZnJvbSUyMCcuJTJGYXBwJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBSb290JTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0MlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0N0aXRsZSUzRUhlbGxvJTIwUXdpayUzQyUyRnRpdGxlJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmhlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NBcHAlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkYlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTdEJTVE)

### System Info

```shell
playground/latest
```

**Comment by jsaf80** [comment]
it's possible to use a callback function.
e.g.
`
...  
const setStateCallBackFn = $((newState: State) => {
      contextStore.state = newState;})
  const contextStore = useStore(() => ({
    state: { foo: 123 } as State,
    setState: setStateCallBackFn
  }))
  ...
  `

**Comment by gioboa** [comment]
Thanks for your suggestion @jsaf80 
I'm closing it for now, feel free to open a new one if it's still a issue for you.
