### ISSUE TITLE
[🐞] Unable to deploy project to Vercel when path to client and server are specified

### ISSUE THREAD

**Issue by SebasG22** [QwikDev/qwik#3498]
### Which component is affected?

Qwik Runtime

### Describe the bug

When specifying the client and server paths in the qwikVite configuration, an error is encountered that prevents the application from building properly. The error occurs when the `client` and `ssr` options are specified with their respective outDir paths.
For example, if the configuration looks like this:

```js
// vite.config.js
qwikVite({
  client: {
    outDir: '.other_folder/client',
  },
  ssr: {
    outDir: '.other_folder/server',
  },
})

```

The error occurs when attempting to building the application using `build.client` and then `build.server`.

However, if the paths are not specified, the application runs without any issues.

This issue may be related to a configuration problem or a bug in `qwikVite` itself. Further investigation is required to determine the root cause of the error.

Here is an reproduction stackblitz 

This is a particularly big issue when trying to deploy from a Monorepo setup because there is not way to specified the outDirfor each package..

Please let me know if you require any additional information.

### Reproduction

https://stackblitz.com/edit/qwik-starter-btfzrt?

### System Info

```shell
All
```

**Comment by manucorporat** [comment]
Vercel needs this files to be generated in specific locations, you are probably breaking it by emitting them in a different place.

**Comment by PatrickJS** [comment]
this is correct. I need to redo vercel adapter
