### ISSUE TITLE
[🐞] Qwik `core.mjs` should not include `import { isServer, isBrowser } from '@builder.io/qwik/build';`

### ISSUE THREAD

**Issue by mhevery** [QwikDev/qwik#3644]
### Which component is affected?

Qwik Runtime

### Describe the bug

1. See https://unpkg.com/@builder.io/qwik@0.100.0/core.mjs
2. Line 8: `import { isServer, isBrowser } from '@builder.io/qwik/build';`

This is unnecessary as `core.mjs` will always be in the browser, and it complicates browsers import.

### Reproduction

https://unpkg.com/@builder.io/qwik@0.100.0/core.mjs

### System Info

```shell
na
```

**Comment by manucorporat** [comment]
Core.mjs is used in node too, but open to ideas

**Comment by gioboa** [comment]
Is it still valid with the new v2 version?
