### ISSUE TITLE
Only generate `<!-- qv -->` when needed

### ISSUE THREAD

**Issue by mhevery** [QwikDev/qwik#3645]
### Which component is affected?

Qwik Runtime

### Describe the bug

Currently, `<!-- qv -->` is generated for each component. This adds weight to HTML. We should only generate `<!-- qv -->` for components that have more than one root component. For the ones which only have one root component, we could just add a special attribute `q:v` to the root element of the component. 

This change is needed to make Qwik SDK more efficient in using `component$` (currently it relies on inline-components, which come with limitations)

### Reproduction

na

### System Info

```shell
na
```

**Comment by manucorporat** [comment]
Not easy to pull this off, a component could rerender and change from one node at the root to multiple

**Comment by PatrickJS** [comment]
this is fixed in v2
