### ISSUE TITLE
[🐞] async useTask$ and updating signal within does not trigger DOM updates

### ISSUE THREAD

**Issue by intellix** [QwikDev/qwik#3707]
### Which component is affected?

Qwik Runtime

### Describe the bug

I've got a list of people that I load once in the server with useTask$ and then trigger re-fetches in the browser using a reactive variables store. Upon triggering another fetch, I'm setting loading.value to true, fetching more people and then setting loading.value to false. These loading.value updates don't update the DOM in either a useTask$ or useVisibleTask$.

### Reproduction

https://stackblitz.com/edit/qwik-starter-q9qhni?file=src%2Froot.tsx

### Steps to reproduce

1) Open the stackblitz
2) Click "Load more" on either useTask$ or useVisibleTask$
3) Notice how "Loading: false" never updates

### System Info

```shell
Chrome: v111
```

### Additional Information

Apparently the workaround is to split the server side stuff into a routeLoader$ and then not use async for useTask$ but as a new developer it's not clear and it just feels like signals don't work at all for me. 

This was previously reported in https://github.com/BuilderIO/qwik/issues/3544 but it got closed (I put too many issues in a single ticket)

**Comment by manucorporat** [comment]
This is not really an issue. useTask$() is holding the rendering, the component can not update while useTask$() is actively running:

```tsx
  useTask$(({ track }) => {
    track(() => variables.count);
    console.log('useTask$ loading true');
    loading.value = true; // does not update DOM on browser
    getPeople(variables.count).then(items => {
      people.items = items;
       loading.value = false;
       console.log('useTask$ loading false');
   });
  });
```

**Comment by intellix** [comment]
ok so the only way to first load data in the server and transfer it across is to use routeLoader$ and duplicate the fetch logic between server and client (upon clicking load more). Not sure if you meant to re-open this btw

**Comment by gioboa** [comment]
@intellix is it still a problem for you?
