### ISSUE TITLE
[🐞] Unbound breakpoint error when debugging in Visual Studio

### ISSUE THREAD

**Issue by JohnathanKG** [QwikDev/qwik#3753]
### Which component is affected?

Qwik Runtime

### Describe the bug

I am making a Qwik app and attempting to debug it in Visual Studio 2022, breakpoints are grayed out and unbound.

### Reproduction

https://github.com/JohnathanKG/Qwik-Bug/tree/master

### Steps to reproduce

1. Run `npm create qwik@latest` to create a new Qwik app. 
2. Create a new visual studio project with the "From existing Node.js code" template, and select the `qwik-app` folder.
3. Open the project properties and set "Script (startup file)" to `node_modules/vite/bin/vite.js`, and `Script arguments" to `--mode ssr`.
4. Set "Launch URL" to `localhost:5173`
5. Start debugging the project, and set a breakpoint anywhere under "src/", it will say "Unbound breakpoint" and only occasionally pauses near the breakpoint.

### System Info

```shell
System:
    OS: Windows 10 10.0.23430
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 31.80 GB / 47.90 GB
  Binaries:
    Node: 19.8.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.23430.1000.0), Chromium (112.0.1722.34), ChromiumDev (113.0.1774.7)
    Internet Explorer: 11.0.23430.1000
  npmPackages:
    @builder.io/qwik: 0.101.0 => 0.101.0
    @builder.io/qwik-city: ~0.101.0 => 0.101.0
    undici: 5.21.0 => 5.21.0
    vite: 4.2.1 => 4.2.1
```

**Comment by gioboa** [comment]
I close this one because right now it's working fine 
we also have a specific configuration in the Qwik repo
https://github.com/QwikDev/qwik/blob/main/.vscode/launch.json
Thanks for your reporting @JohnathanKG
