### ISSUE TITLE
[🐞] `renderToString` not working on client side in `preview` mode

### ISSUE THREAD

**Issue by revintec** [QwikDev/qwik#3758]
### Which component is affected?

Qwik Runtime

### Describe the bug

using qwik 0.101.0, latest version as of writting

`renderToString` works in `npm run dev` but not `npm run preview`
can' t reproduce on stackblitz because `npm run preview` crashes there

1. what is the recommended way to get html representation of jsx nodes?
2. if I'd like to do a PR, where should I change to fix this issue?

<img width="777" alt="image" src="https://user-images.githubusercontent.com/8952734/231729453-36e32b5b-534c-4385-b1d2-36e86b7ae1a7.png">

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/8952734/231730146-192f63e1-2fe7-4b18-aac4-0945a77258f4.png">
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/8952734/231730226-67238314-75e8-4144-9fda-bf32522f749d.png">

the code was something like
```typescript
renderToString(<>...<div>some</div> <div>jsx</div> <div>fragment</div>...</>,{manifest:{}as any,containerTagName:"div"}).then((result)=>callback(tick,result.html))
```

### Reproduction

N/A

### System Info

```shell
System:
    OS: Linux 4.4 Debian GNU/Linux 8 (jessie) 8 (jessie)
    CPU: (48) x64 Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
    Memory: 46.54 GB / 251.18 GB
    Container: Yes
    Shell: 5.8.0.2 - ...zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
```

**Comment by gioboa** [comment]
Is it still a problem with the latest version of Qwik?
