### ISSUE TITLE
[✨] provide a way to customize the build output to subpath

### ISSUE THREAD

**Issue by revintec** [QwikDev/qwik#3759]
### Is your feature request related to a problem?

sharing a domain using subpath should be a common problem, a lot of site(esp. production ones) needs it

`npm run preview` in the default setting outputs to `dist` directory, let's say we deploy it to `http://a.com`, then
`http://a.com/service-worker.js`, `http://a.com/manifest.json`, `http://a.com/build/q-xxx.js`, etc...

how to make everything under a subpath(when sharing a domain name) like
`http://a.com/sub/service-worker.js`, `http://a.com/sub/manifest.json`, `http://a.com/sub/build/q-xxx.js`, etc...?

<img width="749" alt="image" src="https://user-images.githubusercontent.com/8952734/231734524-8d0ec518-24ae-4a6b-af1c-ec1be22d18f7.png">

I've tried the above but it only affected `js` files not `png`(using `import ...?url`) files, and also, how to change subpath for `service-worker.js`, `manifest.json`, etc?

### Describe the solution you'd like

add a switch(commandline and/or `entry.ssr.tsx` setting), that controls subpathing
`--subpath=abc/def` -> `http://a.com/abc/defservice-worker.js`, `http://a.com/abc/defbuild/q-xxx.js`
`--subpath=abc/def/` -> `http://a.com/abc/def/service-worker.js`, `http://a.com/abc/def/build/q-xxx.js`

### Describe alternatives you've considered

no viable alternative that I can think of, we can't just move the `build` folder and/or files under `dist`

**Comment by revintec** [comment]
1. what is the recommended way to sharing domain?
2. if I'd like to open a PR, how should I add these `subpath` settings?

**Comment by wmertens** [comment]
@revintec you need to set `base` to e.g. '/sub/' in vite, not in qwik

**Comment by gioboa** [comment]
@revintec did you try the suggested solution?

**Comment by dostufffancy** [comment]
```js
experimental: {
  renderBuiltUrl(filename: string) {
    return 'http://cdn.xxx.com/xxx/' + filename
  },
},
```
The above only affected `png` files not `css` files
