### ISSUE TITLE
[🐞] sharedMap not available in server$ function

### ISSUE THREAD

**Issue by juanpmarin** [QwikDev/qwik#3891]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I have a layout middleware that loads the current session to sharedMap, like this:
```
export const onRequest: RequestHandler = async ({ sharedMap }) => {
  sharedMap.set("session", session);
};
```

Then I have a server$ function in a nested route that tries to access shared map but it returns an empty object, the function is like this:
```
export const getOffers = server$(async function () {
  const { sharedMap } = this;
  console.log("SHARED MAP", sharedMap);
});
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-gta4fs?file=src/routes/index.tsx

### Steps to reproduce

As server functions don't work in stackblitz, you'll have to download the code and execute it locally

### System Info

```shell
System:
    OS: Linux 6.2 Fedora Linux 38 (Workstation Edition)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 18.60 GB / 31.19 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.volta/tools/image/node/18.16.0/bin/node
    npm: 9.5.1 - ~/.volta/tools/image/node/18.16.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.165
    Firefox: 112.0.1
  npmPackages:
    @builder.io/qwik: ^0.100.0 => 0.100.0 
    @builder.io/qwik-city: ^0.100.0 => 0.100.0 
    undici: 5.21.0 => 5.21.0 
    vite: 4.2.1 => 4.2.1
```

**Comment by cmbartschat** [comment]
Just in case I would try upgrading to 103 in case this fixes it: https://github.com/BuilderIO/qwik/pull/3813

**Comment by cmbartschat** [comment]
Oh, looks like `sharedMap` is available, it's just that the `onRequest` function in `layout.tsx` just isn't called for `server$` it seems like.

**Comment by juanpmarin** [comment]
@cmbartschat I was able to reproduce the bug with 103

**Comment by manucorporat** [comment]
there is a way to make this work, create a `plugin.ts` in `src/routes` and add the onRequest there.
`plugin.ts` files are always called, before any request!

**Comment by juanpmarin** [comment]
Hi @manucorporat, is the plugin.ts file considered part of the stable Api?

**Comment by manucorporat** [comment]
which version of qwik are you using?

**Comment by manucorporat** [comment]
Yeah! this is intrinsec of `server$` they can be called from any route, only routeAction, and routeLoader can be protected with a route guard.

**Comment by juanpmarin** [comment]
@jordanw66 but server$ functions offer a very simple API and semantics, routeAction$ could do but those semantics are weird for cases where you want to query some info.
For example, I'm polling for newly generated data periodically

**Comment by Mo0nbase** [comment]
Any progress or ideas on this @manucorporat? I've also noticed that RequestHandlers in the `plugin.ts` files execute twice on page navigation not sure if this is intentional.

**Comment by PatrickJS** [comment]
this should be fixed now but if you need middleware before server$ then you have to use qwik plugin.ts with plugin@<name>.ts
