### ISSUE TITLE
[🐞] Dynamic routes return 404s in static html builds

### ISSUE THREAD

**Issue by duncan1a** [QwikDev/qwik#4091]
### Which component is affected?

Qwik-city [routing]

... Or possibly qwik runtime

### Describe the bug

I'm building for firebase hosting, so I'm doing static HTML builds.

When I have a dynamic route it's returning 404s. When I run the dev server with `npm run dev` they work fine. It doesn't look like it's building the html files for the dynamic routes

<img width="735" alt="Screenshot 2023-05-07 at 17 04 30" src="https://user-images.githubusercontent.com/430780/236688912-683d8287-6bc5-40cb-a69d-2fd52c427c7e.png">

### Reproduction

https://corrineskitchen-dev.web.app/contact/test

### Steps to reproduce

Eg, I have a contact page `routes/contact/index.tsx`. If I make a dynamic route `routes/contact/[test]/index.tsx` which is just a component that returns "Hello Qwik" - so as simple as possible, I get a 404 in the production build.

The same happens if the route is only a dynamic route, eg: `routes/post/[id]/index.tsx`

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/430780/236672888-f21a20b3-9dd2-4e97-b035-3e4ff0a9f500.png">

The result from the production build
<img width="1216" alt="Screenshot 2023-05-07 at 11 48 25" src="https://user-images.githubusercontent.com/430780/236673008-b3846e02-ba08-498e-bad7-f0eebd003a71.png">

With the dev server it works fine:
<img width="1263" alt="Screenshot 2023-05-07 at 11 47 44" src="https://user-images.githubusercontent.com/430780/236673016-5716f88b-c0a7-429b-b1aa-c40d12e54592.png">

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 21.63 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.1.0 - /usr/local/bin/node
    npm: 9.6.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Edge: 112.0.1722.68
    Firefox: 112.0.2
    Safari: 16.4
  npmPackages:
    @builder.io/qwik: ^1.0.0 => 1.0.0 
    @builder.io/qwik-city: ^1.0.0 => 1.0.0 
    @builder.io/sdk-qwik: ^0.3.0 => 0.3.0 
    undici: 5.14.0 => 5.14.0 
    vite: 4.0.3 => 4.0.3
```

**Comment by duncan1a** [comment]
I've reproduced this with a fresh v1 qwik app. All I did was add a dynamic route under the /demo/flower/ route that comes with the initial setup. I've uploaded it here including the /dist folder 

https://github.com/duncan1a/qwik-v1

<img width="1296" alt="image" src="https://github.com/BuilderIO/qwik/assets/430780/d5504461-b02f-42bb-87d8-2080253e2722">

I've run it with npm/http-server ( https://www.npmjs.com/package/http-server/v/13.0.1 )
<img width="1395" alt="image" src="https://github.com/BuilderIO/qwik/assets/430780/75bbd6ca-6bf1-411b-a902-d658d154775c">

**Comment by othy54** [comment]
Have the same problem !

**Comment by othy54** [comment]
Solved the problem by using Netlify Edge ^^

**Comment by rkanani108** [comment]
@othy54 Can you please explain here...how to solved it?

**Comment by othy54** [comment]
> @othy54 Can you please explain here...how to be solved it? I'm also facing same issue.

> npm run qwik add netlify-edge

**Comment by PatrickJS** [comment]
this is because when rendering static pages you need to know how to get the data
https://qwik.dev/docs/guides/static-site-generation/#dynamic-ssg-routes

**Comment by gioboa** [comment]
Thanks @PatrickJS for your help
