### ISSUE TITLE
[🐞] Tailwind Css Plugin causes weird styling issues

### ISSUE THREAD

**Issue by brayden-wong** [QwikDev/qwik#4115]
### Which component is affected?

Qwik Runtime

### Describe the bug

if tailwind is installed for using `npm run qwik add tailwind`. If you make any change to a component$, it will cause some weird styling issues that wouldn't happen otherwise if you are using css modules instead.  If the server restarts the styling issue goes away until another change is made or all tailwind styles are removed and server restarts. 

e.g inside the hero component the text will get small once tailwind is added

### Reproduction

https://stackblitz.com/edit/qwik-starter-pprh6b?file=src/components/component.tsx

### Steps to reproduce

1. run `npm run dev`

2. create or use a preexisting component with it's respective css module

3. add a class to change the text color of something

4. styles update properly and no styling issues

6. run `npm run qwik add tailwind`

7. start server using `npm run dev`

8. instead of using the css module class change the text to use tailwind style syntax e.g `text-red-500`

small production video if my steps to reproduce are unclear
https://user-images.githubusercontent.com/75548271/236893012-d573f0f2-e68c-495e-9d10-9eb10a8c7044.mp4

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 85.22 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 16.4
```

### Additional Information

I'm not sure if tailwind's css classes are messing with the base styles that the qwik app is provided with, but I haven't looked too deeply into it.

**Comment by gioboa** [comment]
Hi, is it still an issue with the latest version of Qwik?
