### ISSUE TITLE
[✨] Stream resources

### ISSUE THREAD

**Issue by GrandSchtroumpf** [QwikDev/qwik#4178]
### Is your feature request related to a problem?

I'm building an NFT marketplace, and I need to get the latest state of the blockchain. For that, at each request I check if the current cache is outdated, and update it if needed.

I want to stream the data from the server (or client) like that: 
1. Return current context's state if any
2. Return the cache value if fresher than current state
3. Return the state from the blockchain if updated since cache/state

Currently if I use `useTask$` or `routeLoader$` I'll wait for the entire content to be query before displaying anything.
If I use `useResource$` I can display the static part, but I cannot stream my content along the way.

### Describe the solution you'd like

Here is what I would like to do :
```jsx
const state = useContext(GlobalState);
// If SPA navigation will run on browser, if MPA navigation will run on server (like `useTask$`)
const stream = useStream$(async function* () {
  // 1. Return current context's state if any
  yield state;
  
  // 2. Return the cache value if fresher than current state
  const cache = isServer ? await db.get(...) : await idb.get(...);
  if (state.blockNumber < cache.blockNumber) yield cache;
  
  // 3. Return the state from the blockchain if updated since cache/state
  const from = Math.max(state.blockNumber, cache.blockNumber);
  const to = await ethereum.getBlockNumber();
  const latest = await getFromBlockchain(from, to);
  isServer ? db.set(..., latest) : idb.set(..., latest); // Update cache
  yield latest;
});
useVisibleTask$(({ track }) => {
  track(() => stream);
  // Update context state with latest stream value if fresher, for next update
  if (stream.value.blockNumber > state.blockNumber) Object.assign(state, stream.value);
});
return <header>
  <h1>Static content displayed before stream finish</h1>
  {/* stream.loading is true when no data has been emitted yet */}
  {stream.loading && <p>Syncing...</p>}
  {/* stream.done is true when generator is past the end of its control flow */}
  {!stream.loading && !stream.done && <p>Syncing blocknumber: {stream.value.blockNumber}</p>}
  {!stream.loading && stream.done && <p>Current blocknumber: {stream.value.blockNumber}</p>}
</header>
```
Note: In my example I combine a local cache with indexedDB & global with a database to support offline app.

### Describe alternatives you've considered

I could use a combination of `useVisibleTask$` and `server$` stream but : 
1. I would have to wait for the page to be displayed to do the query
2. I would always query the server while in the example above I do the query once in the server if I load the page, then all upcoming navigation will use local cache.

```jsx
const stream = server$(async function*(state) {
  const cache = await db.get(...);
  if (state.blockNumber < cache.blockNumber) yield cache;
  
  const from = Math.max(state.blockNumber, cache.blockNumber);
  const to = await ethereum.getBlockNumber();
  const latest = await getFromBlockchain(from, to);
  db.set(..., latest); // Update cache
  yield latest;
})

export default component$(() => {
  const state = useContext(GlobalState);

  useVisibleTask$(() => {
    // 1. Page needs to be visible before doing the query as `useTask$` won't update the state when it runs on the server
    // 2. I'll query the server on every navigation while I should do it only once and then use local data
    const response = await stream(state);
    for await (newState of response) {
      if (newState.blockNumber > state.blockNumber) Object.assign(state, stream.value);
    }
  });
  return <header>
    <h1>Static content displayed before stream finish</h1>
    <p>Current blocknumber: {state.blockNumber}</p>
  </header>
})
```

If you're interested in this kind of hook but don't have the time, I can try to work on it if you've got some idea on how to achieve that.

### Additional context

Somehow related to #3304

**Comment by PatrickJS** [comment]
this will be in v2
