### ISSUE TITLE
[✨] store `qsymbol` events in an array on `window`

### ISSUE THREAD

**Issue by mhevery** [QwikDev/qwik#4181]
### Is your feature request related to a problem?

If in application has `useVisibleTask` it can be hard to register `addEventListener("qsymbol"` early enough to see oll of the `qsymbol`s as they are leaded.

### Describe the solution you'd like

Since we already have `qsymbol` listener, it would be nice if the listeners would add the result into `window.qwiksymbols` array. this way it would be very easy for the app developer to see which symbols have been loaded up to this point.

```
const qwiksymbols: {name: string, timestamp: 0}[]
```

Maybe just do something like
```
addEventListener('qsymbol', (e) {
  window.qwidSymobls.push(e.details);
});
```

### Describe alternatives you've considered

registering it yourself, but it is hard to ensure tha the registration happens before `useVisibleTask` wakes up.

**Comment by manucorporat** [comment]
It's not something we want to do by default, the array would always keep growing up, coudl be a lot of events! we let it to the developers to use the `qsymbol` event and do whatever they want with the data!

**Comment by mhevery** [comment]
- I think we should do it because it is very hard to get symbols for events that happen eagerly. (No easy way to register code before they run.)
- Yes the list would grow, but it would never be that large since it would never grow past a fraction size of the manifest. So I don't think that would be a problem.

**Comment by mhevery** [comment]
already solved with Qwik Insights
