### ISSUE TITLE
[🐞] `pnpm create qwik@latest` asks  to install dependencies but does not install them

### ISSUE THREAD

**Issue by sarvex** [QwikDev/qwik#4183]
### Which component is affected?

Qwik Runtime

### Describe the bug

Let's create a  Qwik App  ✨ (v1.1.1)
│
◇  Where would you like to create your new project? (Use '.' or './' for current directory)
│  ./qwik-app
│
●  Creating new project in  D:\Source\qwik-app  ... 🐇
│
◇  Select a starter
│  Basic App (QwikCity)
│
◇  Would you like to install pnpm dependencies?
│  Yes
│
◇  Initialize a new git repository?
│  Yes
│
◇  Created App 🐰
│
◇  Git initialized 🎲
│
◇  Failed to install dependencies 📋

### Reproduction

https://stackblitz.com/edit/qwik-starter

### Steps to reproduce

pnpm create qwik@latest

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 1012.99 MB / 15.77 GB
  Binaries:
    Node: 20.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.5.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.6.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: ^1.1.1 => 1.1.1
    @builder.io/qwik-city: ^1.1.1 => 1.1.1
    undici: 5.22.0 => 5.22.0
    vite: 4.3.5 => 4.3.5
```

**Comment by adamdbradley** [comment]
This isn't the fix, but it should help log any errors we're not seeing: https://github.com/BuilderIO/qwik/pull/4187

**Comment by sarvex** [comment]
> do you get the error message of why it failed to install dependencies?

@manucorporat I do not get any error 

> This isn't the fix, but it should help log any errors we're not seeing:  https://github.com/BuilderIO/qwik/pull/4187

@adamdbradley  Shall I merge this in my personal fork and try again?

**Comment by manucorporat** [comment]
Can you try again in 1.1.2? it should print the error message!

**Comment by sarvex** [comment]
```powershell
│
○  Installing pnpm dependencies
│
■  EXDEV: cross-device link not permitted, rename 'C:\Users\Yoga\AppData\Local\Temp\create-qwik-1axyk132in9\node_modules' -> 'D:\Source\test-app\node_modules'
│
│
│
■   pnpm install failed
│   You might need to run "pnpm install" manually inside the root of the project.
│
◇  Failed to install pnpm dependencies 📋
```

**Comment by manucorporat** [comment]
Ok! This gives me an idea of what’s going on!! We should be able to fix it in next release

**Comment by krishna-santosh** [comment]
Facing same issue with npm (v9.6.6) (OS: Archlinux)

```
◇  App Created 🐰│
◒  Installing npm dependencies...   
│
■  EXDEV: cross-device link not permitted, rename '/tmp/create-qwik-1xy4rohj08f/node_modules' -> '/home/krishna/Code/Qwik/deno-qwik-login-app/node_modules'
│  
│  
│
■   npm install failed 
│   You might need to run "npm install" manually inside the root of the project.
│
◇  Failed to install npm dependencies 📋
```

**Comment by sarvex** [comment]
@jordanw66 even windows users are facing the problem because of `pnpm` store is not under the project. 

First run of `pnpm` fails on Windows as the store is linked to the temp folder and asks to recreate the whole node_modules directory. 

@manucorporat we need to change the location as sub-folder of the project.

**Comment by ianlet** [comment]
Same issue with Yarn:
```
○  Installing yarn dependencies
│
■  EXDEV: cross-device link not permitted, rename '/tmp/create-qwik-y69244vbbi/node_modules' -> '/home/ian/Projects/tmp/yarn-workspaces/apps/qwik-app/node_modules'
│
│
│
■   yarn install failed
│   You might need to run "yarn install" manually inside the root of the project.
```

**Comment by gioboa** [comment]
@ianlet are you using the latest version of Qwik? Which is your environment?

**Comment by ianlet** [comment]
> @ianlet are you using the latest version of Qwik?

Yes, sorry I forgot to mention it:
```
@builder.io/qwik: 1.2.10
@builder.io/qwik-city: 1.2.10
vite: 4.4.7
undici: 5.1.6
```

**Comment by zanettin** [comment]
Hi @ianlet 
Just a quick question: when u run the install w/o selecting the `install dependencies` option and then `cd` into the app dir, would it then successfully install w/o errors?

**Comment by ianlet** [comment]
Hi @zanettin
Yes, in my case it does install without errors.

**Comment by mhevery** [comment]
I just tested the latest version, and all dependencies installed as expected for `npm` and `pnpm` but fail for `yarn`

Closing this issue in favor of https://github.com/BuilderIO/qwik/issues/5045

**Comment by karthikjn01** [comment]
I'm running into this too @zanettin - just trying to run `bun create qwik@latest` as is on the website and I'm getting the following issue: 
```EXDEV: cross-device link not permitted, rename '/var/folders/7c/c396xbkd7sbbj_5zz4mk1nlr0000gn/T/create-qwik-u5d7s6a9ia/node_modules' -> '/.../node_modules'```

Any help would be much appreciated.

**Comment by karthikjn01** [comment]
Just to expand a bit from the previous comment - I tried `bun`, `npm` and `yarn` all coming up with the same issue.

**Comment by karthikjn01** [comment]
So I ended up fixing the issue with:

`npm install fs-extra`
then
```
node -e "require('fs-extra').move('/var/folders/7c/c396xbkd7sbbj_5zz4mk1nlr0000gn/T/create-qwik-1rnvb666kff/node_modules', '/Volumes/Primary/Code/.../.../node_modules', { overwrite: true }, console.log)"
```

No idea what the original issue was but thanks perplexity.ai for the fix 😂

**Comment by igolskyi** [comment]
Facing same issue with node(20.11.0), npm(10.2.4), Ubuntu 22.04

```sh
┌  Let's create a  Qwik App  ✨ (v1.3.5)
│
◇  Where would you like to create your new project? (Use '.' or './' for current directory)
│  ./qwik_test
│
●  Creating new project in  /media/files/ws/qwik/qwik_test  ... 🐇
│
◇  Select a starter
│  Basic App (Qwik City + Qwik)
│
◇  Would you like to install npm dependencies?
│  Yes
│
◇  Initialize a new git repository?
│  Yes
│
◇  Finishing the install. Wanna hear a joke?
│  Yes
│
◇  🙈 ───────────────────────────────────────╮
│                                            │
│  What do you do when you see a space man?  │
│  Park your car, man.                       │
│                                            │
├────────────────────────────────────────────╯
│
◇  App Created 🐰
│
◇  Git initialized 🎲
│
◒  Installing npm dependencies│
■  EXDEV: cross-device link not permitted, rename '/tmp/create-qwik-rmf4tc4dvi/node_modules' -> '/media/files/ws/qwik/qwik_test/node_modules'
│  
│  
│
■   npm install failed 
│   You might need to run "npm install" manually inside the root of the project.
│  
│  
◇  Failed to install npm dependencies 📋
```

**Comment by gioboa** [comment]
I just tested the latest version, and all dependencies installed as expected.
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
