### ISSUE TITLE
[🐞] useTask$/useVisibleTask$ produce unexpected behavior

### ISSUE THREAD

**Issue by cmbartschat** [QwikDev/qwik#4210]
### Which component is affected?

Qwik Runtime

### Describe the bug

The behavior I'm seeing is that a server-side useTask$ is running, but the changes are not being applied to the rendered HTML that is sent to the client. The cleanup callback is also being called immediately which seems unintended.

More detail in the repro steps.

### Reproduction

https://stackblitz.com/edit/qwik-starter-d4eggl?file=src/routes/index.tsx

### Steps to reproduce

1. Open the StackBlitz
2. Start the server (`npm run preview`)
3. Open the site
4. See that the status is `init` rather than `mounted`.
5. See that using `<Link>` to navigate away does not switch to the `unmounted` status
6. See that using `<Link>` to navigate back does end up in the `mounted` state, then `unmounted` after that
7. Uncomment the `useVisibleTask$` in src/routes/index.tsx
8. Restart the server
9. See that the server rendered page is still `status: init` (browser JS turned off), but if JS is enabled, ends up as `unmounted (server) + visible`, which is also surprising

### System Info

```
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: ^1.1.2 => 1.1.2 
    @builder.io/qwik-city: ^1.1.2 => 1.1.2 
    undici: 5.22.0 => 5.22.0 
    vite: 4.3.3 => 4.3.3 
```

**Comment by manucorporat** [comment]
this is a limitation of streaming rendering. in order to make this work it would require to rerender a parent. It could lead to infinite loops, causing DDoS (no framework support this). On top of that, it would require to disable streaming, since eventually any children can change the root node. we can't send anything to the DOM.

I wonder how we can educate developers on this:
- Docs
- Some warnings?

Any thoughts?

**Comment by manucorporat** [comment]
All `cleanup` are called when the application is paused. Imagine a server does setTimeout(), we need to cleanup timer etc. it's expected behaviour

**Comment by cmbartschat** [comment]
Ok great, thanks for the extra context. 

My understanding of useTask was missing the detail that a useTask's cleanup is only called on component unmount if the task ran a second time on the client. My mental model is still adjusting.

However - there is something potentially actionable.

The serialized state we send to the client is the state after the child component's task has been processed, rather than immediately after the parent component is "finalized", let's say. This explains why we're seeing `init` in the html, but then using a useVisibleTask$, instead of getting `init + visible`, we get `unmounted (server) + visible`. Maybe this could be changed.

Then yeah, in terms of education, definitely warnings, maybe even erroring out on dev?

"State updates cannot be triggered from a component's `useTask$` if it received the state through context or props."

**Comment by manucorporat** [comment]
> "State updates cannot be triggered from a component's useTask$ if it received the state through context or props."

this would be a huge limitation during normal browser execution.

how about something like this:
```
This state mutation would trigger a rerender a component that is already rendered, which is not possible during SSR.

SSR HTML might not be in sync with the serialized state.
```

**Comment by manucorporat** [comment]
>My understanding of useTask was missing the detail that a useTask's cleanup is only called on component unmount if the task ran a second time on the client. My mental model is still adjusting.

The cleanup is called when:
- the same task runs again
- the component is unmounted
- the container is paused

**Comment by manucorporat** [comment]
The reason is that it's usually necesary to cleanup things when moving between server and client, imagine, a setTimeout will not cross from the server to the client

**Comment by cmbartschat** [comment]
I like your message. Yeah didn't mean for mine to imply anything about client-side behavior. I wonder if we could be sophisticated enough to know if an already-"finalized" component is subscribed to that state or not. Thinking of a case where a top-level parent defines a store, a subcomponent updates the store in `useTask$`, then another component renders that store. 
There's definitely some weirdness here, [see playground](https://qwik.builder.io/playground/#version=1.1.2&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU3RvcmUlMkMlMjB1c2VTaWduYWwlMkMlMjB1c2VUYXNrJTI0JTIwJTdEJTIwZnJvbSUyMCU1QyUyMiU0MGJ1aWxkZXIuaW8lMkZxd2lrJTVDJTIyJTNCJTVDciU1Q24lNUNyJTVDbmNvbnN0JTIwUmVuZGVyU3RvcmUlMjAlM0QlMjBjb21wb25lbnQlMjQlM0MlN0JzdG9yZSUzQSUyMCU3QnN0YXR1cyUzQSUyMHN0cmluZyU3RCU3RCUzRSgocHJvcHMpJTIwJTNEJTNFJTIwJTdCJTVDciU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjAlM0NwJTNFU3RhdHVzJTNBJTIwJTdCcHJvcHMuc3RvcmUuc3RhdHVzJTdEJTNDJTJGcCUzRSU1Q3IlNUNuJTdEKSU1Q3IlNUNuJTVDciU1Q25jb25zdCUyMFN0b3JlTWFuYWdlciUyMCUzRCUyMGNvbXBvbmVudCUyNCUzQyU3QnN0b3JlJTNBJTIwJTdCc3RhdHVzJTNBJTIwc3RyaW5nJTdEJTdEJTNFKHByb3BzJTIwJTNEJTNFJTIwJTdCJTVDciU1Q24lMjAlMjB1c2VUYXNrJTI0KChjdHgpJTIwJTNEJTNFJTIwJTdCJTVDciU1Q24lMjAlMjAlMjAlMjAlMjAlMjBwcm9wcy5zdG9yZS5zdGF0dXMlMjAlM0QlMjAnbW91bnRlZCclNUNyJTVDbiUyMCUyMCUyMCUyMGN0eC5jbGVhbnVwKCgpJTIwJTNEJTNFJTIwJTdCJTVDciU1Q24lMjAlMjAlMjAlMjAlMjAlMjBwcm9wcy5zdG9yZS5zdGF0dXMlMjAlM0QlMjAndW5tb3VudGVkJyU1Q3IlNUNuJTIwJTIwJTIwJTIwJTdEKSU1Q3IlNUNuJTIwJTIwJTdEKSU1Q3IlNUNuJTVDciU1Q25yZXR1cm4lMjAlM0NwJTNFTXklMjB0YXNrJTIwc2V0cyUyMHRoZSUyMHN0YXR1cyUyMHRvJTIwJTVDJTIybW91bnRlZCU1QyUyMiUzQyUyRnAlM0UlNUNyJTVDbiU3RCklNUNyJTVDbiU1Q3IlNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGNvbXBvbmVudCUyNCgoKSUyMCUzRCUzRSUyMCU3QiU1Q3IlNUNuY29uc3QlMjBzdG9yZSUyMCUzRCUyMHVzZVN0b3JlKCU3QnN0YXR1cyUzQSUyMCdpbml0JyUyQyUyMGhpZGRlbiUzQSUyMGZhbHNlJTdEKSU1Q3IlNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q3IlNUNuJTIwJTIwJTIwJTIwJTNDJTNFJTVDciU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NSZW5kZXJTdG9yZSUyMHN0b3JlJTNEJTdCc3RvcmUlN0QlMkYlM0UlNUNyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ1N0b3JlTWFuYWdlciUyMHN0b3JlJTNEJTdCc3RvcmUlN0QlMkYlM0UlNUNyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ1JlbmRlclN0b3JlJTIwc3RvcmUlM0QlN0JzdG9yZSU3RCUyRiUzRSU1Q3IlNUNuJTIwJTIwJTIwJTIwJTNDJTJGJTNFJTVDciU1Q24lMjAlMjApJTNCJTVDciU1Q24lN0QpJTNCJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjB0eXBlJTIwUmVuZGVyT3B0aW9ucyUyMCU3RCUyMGZyb20lMjAnJTQwYnVpbGRlci5pbyUyRnF3aWslMkZzZXJ2ZXInJTNCJTVDbmltcG9ydCUyMCU3QiUyMFJvb3QlMjAlN0QlMjBmcm9tJTIwJy4lMkZyb290JyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwKG9wdHMlM0ElMjBSZW5kZXJPcHRpb25zKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjByZW5kZXJUb1N0cmluZyglM0NSb290JTIwJTJGJTNFJTJDJTIwb3B0cyklM0IlNUNuJTdEJTVDbiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZyb290LnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBBcHAlMjBmcm9tJTIwJy4lMkZhcHAnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMFJvb3QlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQyUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRiUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCUzQiU1Q24lMjIlN0QlNUQ%3D)

**Comment by cmbartschat** [comment]
And then adding a client-side state update we see that the actual store value is `unmounted` - [playground](https://qwik.builder.io/playground/#version=1.1.2&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU3RvcmUlMkMlMjB1c2VTaWduYWwlMkMlMjB1c2VUYXNrJTI0JTIwJTdEJTIwZnJvbSUyMCU1QyUyMiU0MGJ1aWxkZXIuaW8lMkZxd2lrJTVDJTIyJTNCJTVDciU1Q24lNUNyJTVDbmNvbnN0JTIwUmVuZGVyU3RvcmUlMjAlM0QlMjBjb21wb25lbnQlMjQlM0MlN0JzdG9yZSUzQSUyMCU3QnN0YXR1cyUzQSUyMHN0cmluZyU3RCU3RCUzRSgocHJvcHMpJTIwJTNEJTNFJTIwJTdCJTVDciU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjAlM0NwJTNFU3RhdHVzJTNBJTIwJTdCcHJvcHMuc3RvcmUuc3RhdHVzJTdEJTNDJTJGcCUzRSU1Q3IlNUNuJTdEKSU1Q3IlNUNuJTVDciU1Q25jb25zdCUyMFN0b3JlTWFuYWdlciUyMCUzRCUyMGNvbXBvbmVudCUyNCUzQyU3QnN0b3JlJTNBJTIwJTdCc3RhdHVzJTNBJTIwc3RyaW5nJTdEJTdEJTNFKHByb3BzJTIwJTNEJTNFJTIwJTdCJTVDciU1Q24lMjAlMjB1c2VUYXNrJTI0KChjdHgpJTIwJTNEJTNFJTIwJTdCJTVDciU1Q24lMjAlMjAlMjAlMjAlMjAlMjBwcm9wcy5zdG9yZS5zdGF0dXMlMjAlM0QlMjAnbW91bnRlZCclNUNyJTVDbiUyMCUyMCUyMCUyMGN0eC5jbGVhbnVwKCgpJTIwJTNEJTNFJTIwJTdCJTVDciU1Q24lMjAlMjAlMjAlMjAlMjAlMjBwcm9wcy5zdG9yZS5zdGF0dXMlMjAlM0QlMjAndW5tb3VudGVkJyU1Q3IlNUNuJTIwJTIwJTIwJTIwJTdEKSU1Q3IlNUNuJTIwJTIwJTdEKSU1Q3IlNUNuJTVDciU1Q25yZXR1cm4lMjAlM0NwJTNFTXklMjB0YXNrJTIwc2V0cyUyMHRoZSUyMHN0YXR1cyUyMHRvJTIwJTVDJTIybW91bnRlZCU1QyUyMiUzQyUyRnAlM0UlNUNyJTVDbiU3RCklNUNyJTVDbiU1Q3IlNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGNvbXBvbmVudCUyNCgoKSUyMCUzRCUzRSUyMCU3QiU1Q3IlNUNuY29uc3QlMjBzdG9yZSUyMCUzRCUyMHVzZVN0b3JlKCU3QnN0YXR1cyUzQSUyMCdpbml0JyUyQyUyMGhpZGRlbiUzQSUyMGZhbHNlJTdEKSU1Q3IlNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q3IlNUNuJTIwJTIwJTIwJTIwJTNDJTNFJTVDciU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NSZW5kZXJTdG9yZSUyMHN0b3JlJTNEJTdCc3RvcmUlN0QlMkYlM0UlNUNyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ1N0b3JlTWFuYWdlciUyMHN0b3JlJTNEJTdCc3RvcmUlN0QlMkYlM0UlNUNyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ1JlbmRlclN0b3JlJTIwc3RvcmUlM0QlN0JzdG9yZSU3RCUyRiUzRSU1Q3IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDYnV0dG9uJTIwdHlwZSUzRCdidXR0b24nJTIwb25DbGljayUyNCUzRCU3QigpJTIwJTNEJTNFJTIwJTdCJTVDciU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBzdG9yZS5zdGF0dXMlMjAlMkIlM0QlMjAnJTIwY2xpY2tlZC4nJTVDciU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlN0QlN0QlM0VDbGljayUyMG1lJTNDJTJGYnV0dG9uJTNFJTVDciU1Q24lMjAlMjAlMjAlMjAlM0MlMkYlM0UlNUNyJTVDbiUyMCUyMCklM0IlNUNyJTVDbiU3RCklM0IlMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGZW50cnkuc2VydmVyLnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjByZW5kZXJUb1N0cmluZyUyQyUyMHR5cGUlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMEFwcCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2hlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDdGl0bGUlM0VIZWxsbyUyMFF3aWslM0MlMkZ0aXRsZSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2JvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDQXBwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmJvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEJTNCJTVDbiUyMiU3RCU1RA%3D%3D)

**Comment by cmbartschat** [comment]
By the way, there isn't always a cleanup to run when a component is unmounted, which is the thing I learned. [This playground](https://qwik.builder.io/playground/#version=1.0.0&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwdXNlU2lnbmFsJTJDJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlVGFzayUyNCUyMCU3RCUyMGZyb20lMjAlNUMlMjIlNDBidWlsZGVyLmlvJTJGcXdpayU1QyUyMiUzQiU1Q3IlNUNuaW1wb3J0JTIwJTdCJTIwaXNTZXJ2ZXIlMjAlN0QlMjBmcm9tJTIwJTVDJTIyJTQwYnVpbGRlci5pbyUyRnF3aWslMkZidWlsZCU1QyUyMiUzQiU1Q3IlNUNuJTVDciU1Q25jb25zdCUyMENoaWxkJTIwJTNEJTIwY29tcG9uZW50JTI0JTNDJTdCJTIwbmFtZSUzQSUyMHN0cmluZyUyMCU3RCUzRSgocHJvcHMpJTIwJTNEJTNFJTIwJTdCJTVDciU1Q24lMjAlMjB1c2VUYXNrJTI0KChjdHgpJTIwJTNEJTNFJTIwJTdCJTVDciU1Q24lMjAlMjAlMjAlMjBjb25zb2xlLmxvZyglNUMlMjJ0YXNrJTIwcnVubmluZyUyMG9uJTVDJTIyJTJDJTIwaXNTZXJ2ZXIlMjAlM0YlMjAlNUMlMjJzZXJ2ZXIlNUMlMjIlMjAlM0ElMjAlNUMlMjJjbGllbnQlNUMlMjIlMkMlMjBwcm9wcy5uYW1lKSUzQiU1Q3IlNUNuJTVDciU1Q24lMjAlMjAlMjAlMjBjdHguY2xlYW51cCgoKSUyMCUzRCUzRSUyMCU3QiU1Q3IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwY29uc29sZS5sb2coJTVDJTIyY2xlYW5pbmclMjB1cCUyMG9uJTVDJTIyJTJDJTIwaXNTZXJ2ZXIlMjAlM0YlMjAlNUMlMjJzZXJ2ZXIlNUMlMjIlMjAlM0ElMjAlNUMlMjJjbGllbnQlNUMlMjIlMkMlMjBwcm9wcy5uYW1lKSUzQiU1Q3IlNUNuJTIwJTIwJTIwJTIwJTdEKSUzQiU1Q3IlNUNuJTIwJTIwJTdEKSUzQiU1Q3IlNUNuJTVDciU1Q24lMjAlMjByZXR1cm4lMjAlM0NwJTNFQ2hpbGQlMjAoJTdCcHJvcHMubmFtZSU3RCklM0MlMkZwJTNFJTNCJTVDciU1Q24lN0QpJTNCJTVDciU1Q24lNUNyJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNyJTVDbiUyMCUyMGNvbnN0JTIwdG9nZ2xlJTIwJTNEJTIwdXNlU2lnbmFsKGZhbHNlKSUzQiU1Q3IlNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q3IlNUNuJTIwJTIwJTIwJTIwJTNDZGl2JTNFJTVDciU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NidXR0b24lNUNyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHR5cGUlM0QlNUMlMjJidXR0b24lNUMlMjIlNUNyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMG9uQ2xpY2slMjQlM0QlN0IoKSUyMCUzRCUzRSUyMCU3QiU1Q3IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdG9nZ2xlLnZhbHVlJTIwJTNEJTIwIXRvZ2dsZS52YWx1ZSUzQiU1Q3IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTdEJTVDciU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0UlNUNyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMFRvZ2dsZSU1Q3IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGYnV0dG9uJTNFJTVDciU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlN0IhdG9nZ2xlLnZhbHVlJTIwJTI2JTI2JTIwJTNDQ2hpbGQlMjBuYW1lJTNEJTVDJTIyU3RhcnRzJTIwTW91bnRlZCU1QyUyMiUyMCUyRiUzRSU3RCUyMCUyMCUyMCUyMCUyMCUyMCU1Q3IlNUNuJTIwJTIwJTIwJTIwJTNDJTJGZGl2JTNFJTVDciU1Q24lMjAlMjApJTNCJTVDciU1Q24lN0QpJTNCJTVDciU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGZW50cnkuc2VydmVyLnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjByZW5kZXJUb1N0cmluZyUyQyUyMHR5cGUlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMEFwcCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2hlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDdGl0bGUlM0VIZWxsbyUyMFF3aWslM0MlMkZ0aXRsZSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2JvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDQXBwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmJvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEJTNCJTVDbiUyMiU3RCU1RA%3D%3D) shows that - the first time the component is toggled, since the task never ran on the client, there's no cleanup to do.

**Comment by aivarsliepa** [comment]
> this is a limitation of streaming rendering. in order to make this work it would require to rerender a parent. It could lead to infinite loops, causing DDoS (no framework support this).

Could the server serialize updated state at the end of document (based on just initial render, without re-rendering components) and the Qwikloader resumes some components based on the updated state?

Worst case scenario the whole tree needs to be resumed client side when document is loaded, but at least things would work as expected.
We could show some warning when this behavior occurs and developer could optimize.

**Comment by gioboa** [comment]
This issue is really old and it's stale, there are few suggestions though.
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
