### ISSUE TITLE
[🐞] Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type

### ISSUE THREAD

**Issue by jocarrd** [QwikDev/qwik#4244]
### Which component is affected?

Qwik Runtime

### Describe the bug

When using Tailwind and changing the folder structure of the initial template, that error appears but the app works well.

![image](https://github.com/BuilderIO/qwik/assets/55456507/b099033f-5418-42b7-881e-2cbc96df3bcc)

### Reproduction

https://stackblitz.com/edit/qwik-starter-tjv86x?file=src%2Froutes%2Flayout.tsx

### Steps to reproduce

To reproduce the error, you must change the name of a component, including its CSS styles, and then move it to another folder.
When reloading or restarting the application, the error disappears. I believe it is a hot module replacement error when you mix css modules and tailwind .

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: 1.0.0 => 1.0.0 
    @builder.io/qwik-city: ^1.0.0 => 1.0.0 
    undici: 5.22.0 => 5.22.0 
    vite: 4.3.3 => 4.3.3
```

**Comment by DylanJu** [comment]
I'm experiencing the same issue with module css. I agreed it because HMR.
If app was restarted, message is disapeeared.

**Comment by gioboa** [comment]
Is it still a valid issue with the latest version?
