### ISSUE TITLE
[🐞] Function serialization

### ISSUE THREAD

**Issue by mhevery** [QwikDev/qwik#4334]
### Which component is affected?

Qwik Runtime

### Describe the bug

`<div>{signal.value +1}</div>` extracts `(p) => p.value +1` but

`<div>{signal.value.toUpperCase()}</div>` DOES NOT extracts `(p) => p.value.toUpperCase()` but

### Reproduction

n/a

### System Info

```shell
na
```

**Comment by manucorporat** [comment]
Doing so breaks some of our current e2e tests, people do:

```
<div>{props.render$()}</div>
```

which returns JSX, breaking the render. We cant tell at compiler time, so methods are not optimized

**Comment by mhevery** [comment]
I don't think I understand. Could you elaborate?

**Comment by PatrickJS** [comment]
I'm assuming this isn't an issue in v2. please reopen if we still need this
