### ISSUE TITLE
[✨] Better serialization of objects.

### ISSUE THREAD

**Issue by mhevery** [QwikDev/qwik#4338]
### Is your feature request related to a problem?

Currently, we serialize objects like so:
```
[
  { 'name': '3', 'age': 42},
  { 'name': '3', 'age': 42},
  { 'name': '3', 'age': 42},
  'Manu'
]
```

### Describe the solution you'd like

For arrays that create a lot of duplication of `name` and `age`.
We could dedup the keys like so:
```
[
  { '4': '3', '5': 42},
  { '4': '3', '5': 42},
  { '4': '3', '5': 42},
  'Manu',
  'name',
  'age'
]
```

### Describe alternatives you've considered

An alternative (more complex way would be to create arrays from objects, by storing the shape seperatly
```
[
  ['\u12344', '3', 42]
  ['\u12344', '3', 42]
  ['\u12344', '3', 42]
  'Manu',
  'name age'
]
```

Where:
`\u12344` consist of `\u1234` (some code for special object representation) and `4` pointer to "name age"` which describes the properties.

**Comment by ehrencrona** [comment]
Maybe I don't have the full picture here, but this seems like it would only be relevant if the server does not support compression. If I gzip the two first JSON blocks, the second one is actually larger (by 73 against 66 bytes).

**Comment by mhevery** [comment]
That is a good point.... so maybe we should just close it for now....

**Comment by gioboa** [comment]
this is changed with V2 so I close it
