### ISSUE TITLE
[✨] Display a warning for not using a unique key while mapping inside in JSX

### ISSUE THREAD

**Issue by sharifrezvani** [QwikDev/qwik#4551]
### Is your feature request related to a problem?

According to [Qwik docs](https://qwik.builder.io/docs/components/rendering/#rendering-child-components), a unique key should be given to the parent element within a `map()` statement. 

But, while mappping inside JSX, we don't see any warnings in console if a key is not given, and this could cause problems which the developer might not be able to debug instantly.

### Describe the solution you'd like

I think it would be nice if we get some warnings in console so that the developer knows if they missed a place where the key was not given.

### Describe alternatives you've considered

I'm not sure about alternatives, but I think showing an error or warning in console would be pretty straight forward.

**Comment by gioboa** [comment]
I'm closing this one because now we have the warning.
Thanks @sharifrezvani for your report
