### ISSUE TITLE
[🐞] Auth.js works in Qwik in dev mode, but fails when building

### ISSUE THREAD

**Issue by Nefcanto** [QwikDev/qwik#4596]
### Which component is affected?

Qwik Runtime

### Describe the bug

I want to use `auth.js` in my Qwik app. This is my `plugin@auth.ts` file:

```
import { serverAuth$ } from '@builder.io/qwik-auth';
import Keycloak from "@auth/core/providers/keycloak";

const {
    onRequest,
    useAuthSession,
    useAuthSignin,
    useAuthSignout,
} = serverAuth$(({ env }) => ({
    secret: env.get("AUTH_SECRET"),
    trustHost: true,
    providers: [
        Keycloak({
            clientId: 'Site',
            clientSecret: env.get('KEYCLOAK_CLIENT_SECRET'),
            issuer: env.get('KEYCLOAK_ISSUER')
        }),
    ],
}));

export { onRequest }
export { useAuthSession }
export { useAuthSignin }
export { useAuthSignout }
```

I have figured it out from combining docs of [Qwick](https://qwik.builder.io/docs/integrations/authjs/) and [auth.js](https://authjs.dev/reference/core/providers_keycloak).

It works great in the development mode. I have made a test page where I have a sign-in button, and when user logs in, I show him his email and the sign-out button.

However, when I run `npm run build` I get this error:

```
src/routes/plugin@auth.ts(13,9): error TS2322: Type 'OAuthConfig<KeycloakProfile>' is not assignable to type 'Provider'.
  Type 'OIDCConfig<KeycloakProfile>' is not assignable to type 'Provider'.
    Type 'OIDCConfig<KeycloakProfile>' is not assignable to type 'OIDCConfig<Profile> & InternalProviderOptions'.
      Type 'OIDCConfig<KeycloakProfile>' is not assignable to type 'OIDCConfig<Profile>'.
        Type 'Profile' is missing the following properties from type 'KeycloakProfile': exp, iat, auth_time, jti, and 14 more.
src/routes/plugin@auth.ts(15,13): error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
```

I searched that `TS2322` error, and added `as string` to the end of `env.get('KEYCLOAK_CLIENT_SECRET')` and `env.get('KEYCLOAK_ISSUER')`. 

I don't understand why `npm run build` on the same dev machine fails. I don't know why Qwik or TypeScript behaves differently for dev and build under the same conditions.

However, when I add `as string` I get this error:

```
src/routes/plugin@auth.ts(13,9): error TS2322: Type 'OAuthConfig<KeycloakProfile>' is not assignable to type 'Provider'.
  Type 'OIDCConfig<KeycloakProfile>' is not assignable to type 'Provider'.
    Type 'OIDCConfig<KeycloakProfile>' is not assignable to type 'OIDCConfig<Profile> & InternalProviderOptions'.
      Type 'OIDCConfig<KeycloakProfile>' is not assignable to type 'OIDCConfig<Profile>'.
        Type 'Profile' is missing the following properties from type 'KeycloakProfile': exp, iat, auth_time, jti, and 14 more.
```

If those 14 parameters are missing, then how it works in the `npm run dev` mode?

What can I do at this point?

### Reproduction

Since it contains credentials, I can't make a working example

### Steps to reproduce

- Create a new Qwik app
- Run `npm run qwik add auth` to add `auth.js`
- Add `optimizeDeps: { include: [ "@auth/core" ] }` to `vite.config.ts`
- Replace the content of `plugin@auth.ts` with the code above
- Define the required environment variables with a real Keycloak server (this part prevented me from creating a reproduction example)
- Run and it should be OK
- Now try to build it, you should see the errors above

### System Info

```shell
System:
    OS: Linux 5.19 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 8.59 GB / 15.50 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.7.2 - /usr/local/bin/npm
```

### Additional Information

Please add a section to your docs to explain why your `npm run dev` can be OK, but your `npm run build` for the same code, on the same machine fails.

**Comment by manucorporat** [comment]
I iamgine in production is only the typescript check, which i recall the types were very bad in auth.js:
https://github.com/nextauthjs/next-auth/issues/6174

**Comment by diecodev** [comment]
These are typescript typing errors. You can disable them in case you think your configuration is ok, or in case you want to fix it you would have to configure each provider (it is the first error, where it says that 'OAuthConfig<KeycloakProfile>' is not assignable to type 'Provider' this happen because the type 'Provider' expects to be passed an array with all the providers; in the .d.ts file of auth.js they must have the type 'Profile' with all the providers as required). Then you would have to mark the environment variables as valid, for this, you can use the "non-null assertion operator" in typescript. Now, the easiest option and the one that I find (personally) more comfortable is to do a // @ts-ignore when starting the serverAuth configuration.

**Comment by PatrickJS** [comment]
is this still an issue?

**Comment by Nefcanto** [comment]
@PatrickJS, no it's solved. Thank you.
