### ISSUE TITLE
routeAction$ manage same-name inputs

### ISSUE THREAD

**Issue by AustinGil** [QwikDev/qwik#4664]
In HTML it is valid to send FormData containing multiple values for the same name.

```html
<form>
  <input name="yo" value="1">
  <input name="yo" value="2">
</form>
```

There is a bug with `routeAction$` for receiving formdata like this that leads to data loss because only the latest value is accessible in the event handler

```js
routeAction$(async (data) => {
  console.log(data)
  return {
    success: true,
  };
});
```

The current returned value from `console.log(data)` is `{ yo: '2' }`. As you can see, this is missing the value `'1'`.

If we log `await requestEvent.request.formData()`, we can still see the full FormData content is still there:
```js
FormData {
  [Symbol(state)]: [ { name: 'name', value: '1' }, { name: 'name', value: '2' } ]
}
```

This is due to the fact that data is the result of the request FormData being converted to an Object, but Objects can only have one value for a given key, while FormData can have multiple values for the same key.

The bug exists in the source code here, I believe:
https://github.com/BuilderIO/qwik/blob/a64e7b140ef0f55c3c875a2f935fba06cf589077/packages/qwik-city/middleware/request-handler/request-event.ts#L317

I can recommend two solutions:
1. Assign the value of `data` to the `request.formData()` value which would be a FormData object.
2. Keep the Object syntax, but during the conversion, check if the key has already been set, and if so, reassign it to an array containing all value for that key.

**Comment by AustinGil** [comment]
Hmm. I don't know about that one. Havent dug into file uploads with Qwik yet. For multiple inputs, it looks like you can do `name="yo[]` on multiple inputs in order to support arrays, but I still think it should work without the square brackets.

And your comment also makes me wonder how `<select multiple>` would be treated.

**Comment by manucorporat** [comment]
is this a regression in 1.2.0?

**Comment by gioboa** [comment]
Is it working with the latest Qwik version?

**Comment by gioboa** [comment]
I tried with the latest Qwik and the `name="yo[]` works correctly so I close this issue.
Thanks @AustinGil :+1:  fell free to open a PR to propose a different solution if you like.
