### ISSUE TITLE
[🐞] Unsupported environment (bad pnpm and/or Node.js version)

### ISSUE THREAD

**Issue by minsoo-web** [QwikDev/qwik#4698]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

When I clone this project and install packages, following error occurred.

![image](https://github.com/BuilderIO/qwik/assets/57122180/9dbeee85-a9ce-442e-8d2b-eb6100e7b1c2)

I think it's because the node version used by `docs` and the node version used by the project `root` are different.

root -> 16 (.nvmrc)
docs -> 18 (.node-version)

### Reproduction

Clone this repository (main branch) and run follow steps

### Steps to reproduce

> In project root path

```bash
nvm install
nvm use
pnpm install
```

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.46 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.20.1 - ~/.nvm/versions/node/v16.20.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.1/bin/npm
    pnpm: 8.2.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 15.1
```
```


### Additional Information

The solution I suggest is, docs requires 18 version, so why don't we modify the nvmrc file in the root path to 18 version as well? If you don't mind, I'll edit it to PR and upload it.

**Comment by PatrickJS** [comment]
the requirements changed
