### ISSUE TITLE
[📖] What the onRequest returned from serverAuth$ is for?

### ISSUE THREAD

**Issue by Nefcanto** [QwikDev/qwik#4702]
### Suggestion

In the [Auth.js](https://qwik.builder.io/docs/integrations/authjs/#qwik-api) docs, three hooks are explained, which makes sense:

- useAuthSession
- useAuthSignin
- useAuthSignout

But in the [GitHub example](https://qwik.builder.io/docs/integrations/authjs/#github) an `onRequest` is also returned from the `serverAuth$` function.

What is that for?

How should we use it? Please add documentation for it.

I'm asking this because I want to create a central route check in a plugin, preferably in the same `plugin@auth.ts`. I thought of having an `onRequest` method and checking for the incoming path. If it's part of protected paths, I can redirect the user to the login page; otherwise, I do nothing. Yet I see that you already export an `onRequest` from `serverAuth$` and I don't know what it is.

**Comment by maieulchevalier** [comment]
It's in the docs: https://qwik.builder.io/docs/integrations/authjs/#route-protection

**Comment by Nefcanto** [comment]
@maieulchevalier the link you sent is **defining** the `onRequest` from scratch. I asked about the `onRequest` that the `serverAuth$` has already defined.

**Comment by maieulchevalier** [comment]
Here's the code: https://github.com/BuilderIO/qwik/blob/main/packages/qwik-auth/src/index.ts#L90C1-L110C5

It seems to set cookies for server actions and otherwise attach the session object to sharedMap. I'm not sure we're supposed to use it directly :thinking: 

But I redirected you to the docs because if you want to create a central route check, you can simply use a `RequestHandler`.

**Comment by Nefcanto** [comment]
@maieulchevalier yep, that's the main reason I opened this issue. There seems to be no use-case for direct usage of it. Therefore it should be removed from the docs and it's misleading now.

**Comment by maieulchevalier** [comment]
Oh yeah, fair point :see_no_evil:

**Comment by ulic75** [comment]
Yes, it appears as though parts of GitHub and Route Protection examples got overlapped.  Those could be made more clear.  Feel free to submit a PR.

**Comment by gioboa** [comment]
I close this issue because now it's documented 
![image](https://github.com/QwikDev/qwik/assets/35845425/cf2ff70c-6b4f-4df1-9e9a-83766f3e10e9)

Under the hook it saves the session too and catches all the `/api/auth/` routes but this is an internal implementation.
