### ISSUE TITLE
[🐞] Docs: conflicting ctrl+k shortcut

### ISSUE THREAD

**Issue by AustinGil** [QwikDev/qwik#4709]
### Which component is affected?

Qwik Playground

### Describe the bug

In the Qwik docs, there is a keyboard binding for `ctrl+k` that brings up the search box, but it also conflicts with the default browser behavior of focusing on the browser search/url bar.

It would be nice to remove the default behavior and autofocus the docs search widget.

### Reproduction

https://qwik.builder.io/docs/

### Steps to reproduce

Open docs
press `ctrl+k`

### System Info

```shell
Chrome, Edge, Firefox
```

**Comment by JoepKockelkorn** [comment]
I'm on a Mac and I can perfectly focus on the address bar using `CMD + L` in Chrome. In Windows or Linux there are also other alternatives than `CTRL + K`, like `CTRL + L` ([link](https://support.google.com/chrome/answer/157179?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Caddress-bar-shortcuts)).

**Comment by AustinGil** [comment]
The issue is not in focusing the address bar. That actually works as expected. However, I think the intended behavior is that `ctrl+k` should open the in-app search box and focus it. 

The actual behavior is that it opens in in-app search, but then the native key bindings move the focus to the search bar, which opens it instead and obscures the in-app search. This default behavior should be prevented, imo.

![c04a38e7-7ff8-42b9-8500-880c049d3c5b](https://github.com/BuilderIO/qwik/assets/4879075/05701c0e-df3a-4f77-8bd6-def1443bf377)
