### ISSUE TITLE
[🐞] qwik-auth - AuthJS is not calling https on prod

### ISSUE THREAD

**Issue by Klerith** [QwikDev/qwik#4715]
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm using AuthJS for a Google, Github, and custom credentials provider on my qwik app, locally everything works as expected, however, on prod/staging the application is calling my SignIn providers as a simple HTTP call instead of HTTPS (even Custom Credentials as well) on an HTTPS server.

I tried many possible configurations on the form submission and links with no success, at this point, I believe is something related to the serverAuth$ from the '@builder.io/qwik-auth' implementation.

Any light that you could throw me would much appreciate it.

[This is the login screen on staging](https://sea-turtle-app-36scw.ondigitalocean.app/auth/login/)

<img width="494" alt="Screenshot 2023-07-04 at 9 22 18 AM" src="https://github.com/BuilderIO/qwik/assets/3438503/11a274c4-1a32-43b8-8a64-a7e2be2043e9">

This is my package.json
```
{
  "name": "my-qwik-basic-starter",
  "description": "Website",
  "engines": {
    "node": ">=15.0.0"
  },
  "private": true,
  "scripts": {
    "build": "qwik build",
    "build.client": "vite build",
    "build.preview": "vite build --ssr src/entry.preview.tsx",
    "build.server": "vite build -c adapters/express/vite.config.ts",
    "build.types": "tsc --incremental --noEmit",
    "dev": "vite --mode ssr",
    "dev.debug": "node --inspect-brk ./node_modules/vite/bin/vite.js --mode ssr --force",
    "fmt": "prettier --write .",
    "fmt.check": "prettier --check .",
    "lint": "eslint \"src/**/*.ts*\"",
    "postinstall": "prisma generate",
    "preview": "qwik build preview && vite preview --open",
    "prisma": "prisma",
    "prisma:pull": "prisma db pull && prisma generate",
    "prisma:generate": "prisma generate",
    "prisma:migrate": "prisma migrate dev",
    "prisma:migrate:prod": "prisma migrate deploy",
    "serve": "node server/entry.express",
    "start": "vite --open --mode ssr",
    "qwik": "qwik"
  },
  "devDependencies": {
    "@auth/core": "^0.9.0",
    "@builder.io/qwik": "^1.2.4",
    "@builder.io/qwik-auth": "~0.1.0",
    "@builder.io/qwik-city": "^1.2.4",
    "@prisma/client": "4.16.2",
    "@types/bcryptjs": "^2.4.2",
    "@types/compression": "^1.7.2",
    "@types/eslint": "8.40.2",
    "@types/express": "4.17.17",
    "@types/masonry-layout": "^4.2.5",
    "@types/node": "^20.3.3",
    "@types/toastify-js": "^1.11.1",
    "@typescript-eslint/eslint-plugin": "5.61.0",
    "@typescript-eslint/parser": "5.61.0",
    "compression": "^1.7.4",
    "eslint": "8.44.0",
    "eslint-plugin-qwik": "^1.2.4",
    "express": "^4.18.2",
    "prettier": "2.8.8",
    "prisma": "^4.16.2",
    "typescript": "5.1.6",
    "undici": "5.22.1",
    "vite": "4.3.9",
    "vite-tsconfig-paths": "4.2.0"
  },
  "dependencies": {
    "bcryptjs": "^2.4.3",
    "masonry-layout": "^4.2.2",
    "toastify-js": "^1.12.0"
  }
}

```

Thank you

### Reproduction

https://sea-turtle-app-36scw.ondigitalocean.app/auth/login/

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (24) arm64 Apple M2 Ultra
    Memory: 94.50 GB / 128.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5
  npmPackages:
    @builder.io/qwik: ^1.2.4 => 1.2.4 
    @builder.io/qwik-auth: ~0.1.0 => 0.1.0 
    @builder.io/qwik-city: ^1.2.4 => 1.2.4 
    undici: 5.22.1 => 5.22.1 
    vite: 4.3.9 => 4.3.9
```

### Additional Information

The callback URLs are set as HTTPS on GitHub and Google, but because the app is calling an HTTP call, that causes a mismatch between them and causes this issue. (Try different servers, Digital Ocean and Railwaiy with the exact same results)

**Comment by manucorporat** [comment]
Where are u deploying? are u using a reverse proxy to add https?

**Comment by manucorporat** [comment]
I think, the root of the problem is that the express server (the node process) does not know it's being server under HTTP.
Could it be related to this?
https://github.com/BuilderIO/qwik/issues/4685#issuecomment-1616638734

Again the root of the problem is that the express server (node) does not know the `ORIGIN`

it can also be set manually by setting the `ORIGIN` environment variable:
```
ORIGIN=https://sea-turtle-app-36scw.ondigitalocean.app
```

Planning to add docs about this, this week! specially for manual deployments with node, this is not a problem for vercel, netlify, cloudflare pages, since we `know` the ORIGIN (it's provided by them)

**Comment by Klerith** [comment]
Thanks @manucorporat 

That did part of the trick, and I was able to continue on stating and testing the route protection as well.

However, not sure why in the local environment and the stating/prod the callbacks are different, I mean, I have something like this on the **plugin@auth.ts** file

```
callbacks: {
      async signIn({ user, account, credentials, email, profile }) {
```
On local, I was using the user to get the user's information, (email, name, and avatar), however, on prod/staging, that piece is null/undefined, I had to use the **profile** object and adapt the code according to the provider.

Thank you once again @manucorporat, you can close the issue!
