### ISSUE TITLE
[🐞] icon snippet made from icones.js.org is incorrect for qwik

### ISSUE THREAD

**Issue by atinylittleshell** [QwikDev/qwik#4724]
### Which component is affected?

Qwik Runtime

### Describe the bug

I was following instructions from https://qwik.builder.io/docs/integrations/icons/#iconesjsorg to use svg icons from icones.js.org. It led to me clicking the "qwik" button below to copy a code snippet:
![image](https://github.com/BuilderIO/qwik/assets/3233006/a029126e-1711-4d0d-b418-5f6b7ad3f983)

The snippet I got was 
```typescript
export function TablerMenu2(props: QwikIntrinsicElements['svg'], key: string) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" {...props} key={key}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
  )
}
```

However, when I try to use this component, I realized that the stroke width was wrong. After some attempts, it turned out that "strokeWidth" would not work as an attribute on <path> while "stroke-width" would. What would actually work in practice is below:
```typescript
export function TablerMenu2(props: QwikIntrinsicElements['svg'], key: string) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" {...props} key={key}><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
  )
}
```

Not sure if this is a bug on icones.js.org side or qwik runtime, as other frameworks seem to be able to handle "strokeWidth" correctly. 

### Reproduction

https://icones.js.org/collection/tabler?s=menu2

### Steps to reproduce

Click the "qwik" button here 
![image](https://github.com/BuilderIO/qwik/assets/3233006/a029126e-1711-4d0d-b418-5f6b7ad3f983)

### System Info

```shell
System:
    OS: Windows 10 10.0.23493
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
    Memory: 50.06 GB / 63.87 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.2 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.23493.1000.0), Chromium (114.0.1823.37)
    Internet Explorer: 11.0.23493.1000
```

**Comment by gioboa** [comment]
Hi @atinylittleshell thanks for your feedback.
I tested this icon with the latest Qwik version and it's working fine.
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
