### ISSUE TITLE
[🐞] Rollup external libraries are still breaking the build at the level of plugin

### ISSUE THREAD

**Issue by Nefcanto** [QwikDev/qwik#4755]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

I want to externalize some files (or js barrels).

I use `vite.config.ts` to configure them:

```
        build: {
            rollupOptions: {
                external: [
                    'CourseParts',
                    'InstructorParts',
                    'QuestionParts',
                ]
            }
        },
```

And if I don't add them, then I get this error:

> [vite]: Rollup failed to resolve import "CourseParts" from "/Project/SiteQwik/src/s_ossmb4bjxmg.js".

When I add them, this error goes away, but then I get this error:

```
✓ built in 4.86s

✓ Built client modules

error during build:
Error [PLUGIN_ERROR]: Cannot find package 'CourseParts' imported from /Project/SiteQwik/server/entry.ssr.mjs
    at new NodeError (node:internal/errors:399:5)
    at packageResolve (node:internal/modules/esm/resolve:889:9)
    at moduleResolve (node:internal/modules/esm/resolve:938:20)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)

```

Qwik defies the notion of external libraries of the rollup.

### Reproduction

I can't produce

### Steps to reproduce

- Create a Qwik project
- Import a non-existing item (using js barreling)
  - `import { Layout } from 'CourseParts'`
- `npm run dev` works
- `npm run build` fails at the level of rollup/vite
- Add `CourseParts` to rollup's external libraries
- `npm run build` fails at the level of plugin

### System Info

```shell
System:
    OS: Linux 5.19 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 9.05 GB / 15.50 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/partytown: ^0.8.0 => 0.8.0 
    @builder.io/qwik: ^1.2.6 => 1.2.6 
    @builder.io/qwik-auth: ~0.1.0 => 0.1.0 
    @builder.io/qwik-city: ^1.2.6 => 1.2.6 
    undici: 5.22.1 => 5.22.1 
    vite: ^4.4.2 => 4.4.2
```

**Comment by gioboa** [comment]
In these months we completely change this part, is the new version solving your issue?

**Comment by Nefcanto** [comment]
@gioboa, those errors are gone. But now we're stuck at https://github.com/QwikDev/qwik/issues/6242.

**Comment by gioboa** [comment]
Thanks @Nefcanto I close this one.
