### ISSUE TITLE
[🐞] Storybook build failed but served successfully with v1.2.x

### ISSUE THREAD

**Issue by ahnpnl** [QwikDev/qwik#4756]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

In **v1.2.x**, having a `stories` folder outside `src` folder will make Storybook build failed. However, starting Storybook dev server is still successful.

I have created a reproduce repo with 2 branches to show the error:
- `main`: the `.stories.tsx` file locates inside `src`
- `bug/storybook-build`: the `.stories.tsx` file has been moved to a folder `stories` which is on the same level as `src` folder

In branch `bug/storybook-build`, build Storybok failed with error
```
RollupError: "Button" is not exported by "stories/button/button.tsx", imported by "stories/button/button.stories.tsx".
```

The issue didn't exist when reverting back to **1.1.5** I think there is something broken about `rollup` plugin in **1.2.x**

### Reproduction

https://github.com/ahnpnl/monorepo-multi-apps

### Steps to reproduce

- Check out the reproduce repo branch `main`
- Install deps with `yarn`
- Run `yarn workspace qwik-app build-storybook` and observe build successfully
- Switch to branch `bug/storybook-build`
- Run `yarn workspace qwik-app build-storybook` and observe build failed

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 171.28 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - /opt/homebrew/bin/node
    Yarn: 3.3.1 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /opt/homebrew/bin/npm
    pnpm: 8.6.6 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
```

### Additional Information

**N.A.**

**Comment by rharink** [comment]
I'm having a similar issue with a local package in a pnpm monorepo.
I've also created a minimal example: https://github.com/rharink/qwik-workspace-import-error-example.

**Comment by ahnpnl** [comment]
@literalpie do you have any insights about this?

**Comment by literalpie** [comment]
Sorry, I don't think I can add anything here. A stories folder is probably the best example of a case where this issue will arise, but I think the issue doesn't have to do with the storybook-framework-qwik package. I think the issue just has to do with the optimizer (or some other part of the Qwik build system) not working correctly outside of the src folder. 

I think adding `component$` is the thing that causes issues. I can reproduce the issue with
```
export const Button = component$(() => {
    return <>test</>;
});
```
but not 
```
export const Button = () => {
    return <>test</>;
};
```

**Comment by shairez** [comment]
Try using the `vendorRoots` prop on the `qwikVite` plugin to add more paths where the optimizer might find Qwik related code in.

See if it helps

**Comment by ahnpnl** [comment]
I tried "vendorRoots: ['./']" and it resolves into stranger error
```
thread 'thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` valuethread '<unnamed><unnamed>thread 'thread '' panicked at '<unnamed><unnamed>', ' panicked at 'called `Option::unwrap()` on a `None` valuecalled `Option::unwrap()` on a `None` valuethread 'packages/qwik/src/optimizer/core/src/lib.rs', ' panicked at '' panicked at 'called `Option::unwrap()` on a `None` value', ', packages/qwik/src/optimizer/core/src/lib.rs:135:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
packages/qwik/src/optimizer/core/src/lib.rs:135:33
```

not sure if I configure like that is the right way

**Comment by ahnpnl** [comment]
Thanks a lot @pleclech, indeed modifying `entryStrategy` unblocks me to go further. For now I create a separate `vite.config.ts` for Storybook to change value of `entryStrategy` to something else and leave the default `vite.config.ts` untouched.

I also suspected that commit since it improves a lot about performance but also changed a lot how compiler works.

**Comment by rharink** [comment]
Thanks @pleclech! Ill use this as temporary workaround. I want to help solving this issue, I write Rust in my day job but I have no idea where to start, maybe someone could point me in the right direction?

**Comment by gioboa** [comment]
In these months we changed the rollup config.
Is the new version of Qwik solving your issue?
