### ISSUE TITLE
[✨] `useRenderIndex`

### ISSUE THREAD

**Issue by shairez** [QwikDev/qwik#4757]
### Is your feature request related to a problem?

When rendering projected children during CSR, there's often times a need to know the current render index of the component, to prevent flickers.

For example, an accordion component with a `selectedIndex` set to 1.

Because Qwik is rendering child components during CSR in parallel, there's no guarantee that the components will run in the same order as they are defined in the JSX 

So we can't rely on a counter that assigns the next index for each new child component. 

### Describe the solution you'd like

I would like to have a hook that will return a signal with the index of the current component in the context of either its parent Slot or element.

something like:

```
const thisCompIndexSig = useRenderIndex();
```

(for slots for example, because we are looping over the projected children inside of the visitor, we can maybe assign their index to the slot context and read it in the hook)

### Describe alternatives you've considered

What we're doing now is to loop over child elements using `querySelector` during "visible task" to get the rendered index of each child component - 

https://github.com/qwikifiers/qwik-ui/blob/main/packages/kit-headless/src/components/tabs/tabs.tsx#L214

### Additional context

This solution is critical for Qwik UI and I'm sure other composable & reusable components that want to prevent a flicker on client side rendering (for example - when navigating using a Link component to a page with that reusable component).

**Comment by thejackshelton** [comment]
To visually explain an example of this issue, here's that accordion example that shai mentioned above.

https://github.com/BuilderIO/qwik/assets/104264123/49972052-2063-4482-9df7-8a48ef89d135

**Comment by shairez** [comment]
closing 
context:
https://github.com/QwikDev/qwik/issues/3966#issuecomment-2131241498
