### ISSUE TITLE
[🐞] React components hydrating when they shouldn't

### ISSUE THREAD

**Issue by jweb89** [QwikDev/qwik#4771]
### Which component is affected?

Qwik React

### Describe the bug

React components are hydrating when they shouldn't be. Even if there is no hydration strategy specified they are still getting hydrated under certain circumstances. One of these is SPA navigation, however I believe there to be others I've just had a hard time minimally reproducing other cases.

### Reproduction

https://codesandbox.io/p/sandbox/angry-mendeleev-3zpfz9?file=%2Fsrc%2Froutes%2Fblog%2Findex.tsx%3A65%2C25

### Steps to reproduce

Click the block on the header
Click the image for a blog post
See that the react button is hydrated and is showing visible

### System Info

```shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
    Memory: 186.40 MB / 2.01 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.16.1 - ~/.local/state/fnm_multishells/6627_1689013245749/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.local/state/fnm_multishells/6627_1689013245749/bin/npm
    pnpm: 7.1.0 - /usr/local/bin/pnpm
    Watchman: 20220528.183901.0 - /usr/local/bin/watchman
  npmPackages:
    @builder.io/qwik: 1.2.0 => 1.2.0 
    @builder.io/qwik-city: 1.2.0 => 1.2.0 
    @builder.io/qwik-react: 0.5.0 => 0.5.0 
    vite: 4.3.9 => 4.3.9
```

### Additional Information
https://www.loom.com/share/47a97da6a993431dbabd0b2d355b05cd?sid=d7615c1c-c94d-4e3e-948f-877e40d662a3

**Comment by gioboa** [comment]
Is this still an issue with the latest version of Qwik?
