### ISSUE TITLE
[🐞]  TTY initialization failed: uv_tty_init returned EBADF (bad file descriptor)

### ISSUE THREAD

**Issue by konayukis** [QwikDev/qwik#4785]
### Which component is affected?

Qwik Runtime

### Describe the bug

![image](https://github.com/BuilderIO/qwik/assets/70825886/67047326-45df-4838-84ad-ca9772792bbc)

### Reproduction

NA

### Steps to reproduce

when excute `pnpm create qwik@latest`

### System Info

```shell
System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 7.42 GB / 15.93 GB
  Binaries:
    Node: 18.16.1 - ~\.nvm\versions\node\v18.16.1\bin\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - ~\.nvm\versions\node\v18.16.1\bin\npm.CMD
    pnpm: 7.29.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Internet Explorer: 11.0.19041.1
```

**Comment by gioboa** [comment]
I tried with the latest CLI version and it's working fine.
Thanks @konayukis for your report anyway. 
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
