### ISSUE TITLE
Error in Qwik tutorial

### ISSUE THREAD

**Issue by WillyWoe** [QwikDev/qwik#4801]
### Suggestion

https://qwik.builder.io/tutorial/welcome/overview/

https://github.com/BuilderIO/qwik/assets/48302225/48254a85-2c53-4a30-b145-f9c83a4c76b8

**Comment by gioboa** [comment]
Hey @WillyWoe , thanks for opening this issue, it's working right now.
So I'm closing this issue, feel free to re-open it if it's still an issue for you.
