### ISSUE TITLE
[📖]Missing tooling and service integration addition information

### ISSUE THREAD

**Issue by xinnks** [QwikDev/qwik#4830]
### Suggestion

I am trying to create a tooling/service integration and by following the documentation I arrived at [this page](https://qwik.builder.io/docs/integrations/#add-a-new-integration). The issue I'm raising is that it seems that this page is actually incomplete since it ends up by stating "If you'd like to add a new tooling or service integration, please read on.", then there's nothing to read on regarding the subject.

**Comment by zanettin** [comment]
thx for the hint @xinnks 🙏 will update the text. till the the best is to have a look at an existing integration which has a similar purpose as the one you'd like to add. thanks for helping to increase the ecosystem 🙏

**Comment by xinnks** [comment]
@zanettin I did, and thankfully the integration has been merged. This information would be quite useful nonetheless. Hopefully it will be added soon.

Kudos to the good work you guys are doing with this framework. 👏

**Comment by gioboa** [comment]
This seems solved now because the process is described.
Another good approach is to look at the other integrations and try to do the same.
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
