### ISSUE TITLE
[🐞] CLS warning is incorrectly styled.

### ISSUE THREAD

**Issue by mhevery** [QwikDev/qwik#4840]
### Which component is affected?

Qwik Runtime

### Describe the bug

https://www.loom.com/share/0f9759427cb04528ac5a917781e224e0

<img width="553" alt="image" src="https://github.com/BuilderIO/qwik/assets/111951/283e5c79-0791-42aa-b449-4333c27f44cf">

The text `CLS 0.008` is incorrectly styled to be `position: absolute`, resulting it being fixed on the page, when the page is scrolled. 

### Reproduction

https://www.loom.com/share/0f9759427cb04528ac5a917781e224e0

### System Info

```shell
na
```

**Comment by manucorporat** [comment]
Please provide a repo case, `position: absolute` is the correct option, in other pages it scroll as expected

**Comment by gioboa** [comment]
I recreated a CLS scenario and `absolute` is working good.
Probably in your test you had a clash with the rest of the CSS.
I close it because it's working fine.
