### ISSUE TITLE
[🐞] `<Link>` navigates leaving used styles.

### ISSUE THREAD

**Issue by genki** [QwikDev/qwik#4844]
### Which component is affected?

Qwik City (routing)

### Describe the bug

The `<Link>` component doesn't change styles after second navigation between two pages that use different styles.

### Reproduction

https://stackblitz.com/edit/qwik-starter-akfopt?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

Please click the link above.
There's 2 simple pages named `Top` and `Home`, these are styled differently by `useStyles$`
Each pages is linked by `<Link>` components at the footer.
And then click the `<Link>` to switch these pages and check out the color of its text.
At the first time the color is changed blue to red. But after that it will never change.
Expected behavior is the color of the text is switched between blue and red, but the fact is no change is happen until reloading the page.

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M2
    Memory: 89.09 MB / 24.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.7.2 - /opt/homebrew/bin/npm
    pnpm: 8.6.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.248
    Safari: 16.5.1
  npmPackages:
    @builder.io/qwik: 1.2.6 => 1.2.6 
    @builder.io/qwik-city: latest => 1.1.4 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.0 => 4.4.0
```

**Comment by gioboa** [comment]
I tested this with Qwik 1.5.7 and the issue is still there
The problem is that we have two styles in the page after the back and forth with `<Link />`
![image](https://github.com/QwikDev/qwik/assets/35845425/95d608b8-9b9f-44fc-b0ad-a3097307b037)

**Comment by gioboa** [comment]
@Varixo do we have a test for this in v2 release? Thanks

**Comment by genki** [comment]
To solve this issue, it is need to remove the style tag when the component be unmounted.
I have tried the removal manually by dev console, but there will be lack of style reinsertion when it is remounted.

**Comment by genki** [comment]
Found a quick workaround for this issue.

```ts
const hashCode = (text: string, hash: number = 0) => {
  for (let i = 0; i < text.length; i++) {
    const chr = text.charCodeAt(i);
    hash = (hash << 5) - hash + chr;
    hash |= 0; // Convert to 32bit integer
  }
  return Number(Math.abs(hash)).toString(36);
};

export const useStyledQrl = (qrl:QRL<string>) => {
  useStyles(qrl);
  const hash = hashCode(qrl.getHash());
  const loc = useLocation();
  const href = loc.url.href;
  const sel = `style[q\\:style^="${hash}-"]`;
  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(({track, cleanup}) => {
    track(() => loc.url.href);
    if (href === loc.url.href) {
      console.log('mounted', hash);
      const styles = document.head.querySelectorAll(sel);
      styles.forEach(s => {(s as HTMLStyleElement).disabled = false});
    }
    cleanup(() => {
      console.log('cleanup', hash);
      const styles = document.head.querySelectorAll(sel);
      styles.forEach(s => {(s as HTMLStyleElement).disabled = true});
    });
  }, {strategy: 'document-ready'})
};
export const useStyled$ = implicit$FirstArg(useStyledQrl);
```

I think there must be more sophisticated solution.

**Comment by Varixo** [comment]
> @Varixo do we have a test for this in v2 release? Thanks

I think in v2 we have the same behaviour. Probably we should fix this

**Comment by Varixo** [comment]
I created a PR for v2 with fix, we should probably do something similar in v1

**Comment by wmertens** [comment]
This is working as intended. If you want to add/remove CSS with mount/unmount, you need to do it as you show @genki

Qwik assumes that all CSS is composable and that order of useStyles$ does not matter. Styles are only added, never removed. The reason is that this is not needed most of the time and it would cost extra to track the usage.

**Comment by genki** [comment]
@wmertens 
You mean all style of components must be static and their looks can not be changed after the first rendering?
If it had changed, it is need to prepare all css rules that had changed by the change, in order to reset their looks again, or to change to another looks.

**Comment by maiieul** [comment]
@genki I believe this is intended behavior indeed. Using <Link> will add the new styles to the DOM and the browser will compose the CSS as if one document. If you really need that behavior you need either your workaround or use an <a> tag.

**Comment by wmertens** [comment]
@genki sorry for missing this. Yes, the useStyles hooks are meant for injecting static CSS only, and you should use classes and/or inline styles to dynamically change styling.

This is the way it works best for browsers and it's the least work for the framework. 

If you want dynamic css in JS, take a look at pandacss, style9 or stylex, vanilla-extract etc.

**Comment by genki** [comment]
I see.
I think it is reasonable decision if the changes are due to the user's micro operations.
But the change can be come from the SPA navigation, in that case it can contain large changes such as themes, color schemes and so on.
If it could happen, the components have to have styles for each themes. This is difficult.
Suppose the web app that there are many users and they have pages with their own theme, the blog system is a typical example.
It is simple that there are styles for each themes and all components refer them than the all components have variety of their styles for each themes. 
Currently, if we want to do so, we have to Non-SPA navigation between pages of different users at that site to reset styles.
As I had introduced a way to disable `<style>`, it can solve this problem.
How about the SPA navigation to have an option to disable styles that is introduced by `useStyles$`?

**Comment by wmertens** [comment]
@genki it really is more performant to use css variables to set the theme and to let css be static. 

In fact the most performant option are inline styles 😳
https://danielnagy.me/posts/Post_tsr8q6sx37pl

So if you want dynamic styling, there are many options, but useStyles$ is only meant for static CSS that always stays on the page. It also can't be changed once it's loaded because the css is stored as a qrl segment.

**Comment by genki** [comment]
@wmertens 
I agree with that result.
IMHO, the CSS in JS is not DRY, that is reason I don't prefer them.
We can use such as `@apply` for DRY up them, but it means it is need to use `useStyles$` to import CSS file.
It's about the speed vs. maintainability.

**Comment by wmertens** [comment]
@genki but if you want useStyles$ to add and remove dynamic styles, then you're also doing CSS-in-JS :)

**Comment by genki** [comment]
@wmertens Yep.
But that is possible to entrust the work of composition of the style to the browsers.
Just we have to do is putting a single class to the components that to be styled. It's DRY :)
