### ISSUE TITLE
[🐞] vite preview fails with vite template starters

### ISSUE THREAD

**Issue by gioboa** [QwikDev/qwik#4880]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

I created a Qwik Typescript app with
`pnpm create vite`
the `preview` script doesn't work

I have this error in the terminal
`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null`
from this piece of code
<img width="1058" alt="Screenshot 2023-07-27 at 23 55 04" src="https://github.com/BuilderIO/qwik/assets/35845425/26503455-80e7-4b3b-aa33-10df71cd3150">

### Reproduction

https://stackblitz.com/github/vitejs/vite/tree/main/packages/create-vite/template-qwik?file=README.md

### Steps to reproduce

- run `pnpm create vite` in the terminal
- create a Qwik application JS or TS
- run `pnpm preview`

### System Info

```shell
System:
  OS: macOS 13.4.1
  CPU: (8) arm64 Apple M1
  Memory: 1.48 GB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.0.0 - ~/.nvm/versions/node/v20.0.0/bin/node
  Yarn: 1.22.10 - /opt/homebrew/bin/yarn
  npm: 9.6.4 - ~/.nvm/versions/node/v20.0.0/bin/npm
  pnpm: 8.6.5 - /opt/homebrew/bin/pnpm
Browsers:
  Chrome: 114.0.5735.248
  Safari: 16.5.2
npmPackages:
  @builder.io/qwik: ^1.2.6 => 1.2.6 
  vite: ^4.4.5 => 4.4.5
```

**Comment by CharlesEkkel** [comment]
Bumping to say this is still an issue - it looks like the `ssrOutDir` is null, which `path.join` doesn't like.

I'm not at all familiar with this repo, so all I can say is that when I create the qwik typescript app (no qwikcity) with vite, it looks like `qwikCiteOpts.csr` (client-side-rendering, perhaps?) is true, which means that this code never runs:

```js
if (!qwikViteOpts.csr) {
  clientOutDir = qwikPlugin.normalizePath(
    sys.path.resolve(
      opts.rootDir,
      qwikViteOpts.client?.outDir || CLIENT_OUT_DIR
    )
  );
  clientPublicOutDir = viteConfig.base
    ? path.join(clientOutDir, viteConfig.base)
    : clientOutDir;

  // ------ THIS BIT HERE ------
  ssrOutDir = qwikPlugin.normalizePath(
    sys.path.resolve(
      opts.rootDir,
      qwikViteOpts.ssr?.outDir || SSR_OUT_DIR
    )
  );

  clientDevInput =
    "string" === typeof qwikViteOpts.client?.devInput
      ? path.resolve(opts.rootDir, qwikViteOpts.client.devInput)
      : opts.srcDir
      ? path.resolve(opts.srcDir, CLIENT_DEV_INPUT)
      : path.resolve(opts.rootDir, "src", CLIENT_DEV_INPUT);
  clientDevInput = qwikPlugin.normalizePath(clientDevInput);
}
```

This is the only place that gives `ssrOutDir` a non-null value, and it's not getting run for me, presumably because these are SSR-only settings. Is there an `entry.preview` file for csr apps somewhere? I can't find in in my project.

**Comment by wmertens** [comment]
Is this fixed?

**Comment by supfiger** [comment]
Any news?
Still have the same issues.

Demo:
https://stackblitz.com/edit/vitejs-vite-dwep7v?file=package.json&terminal=dev

P.S: the code is taken from [the official template](https://vite.new/qwik-ts) from the [Vite docs](https://vitejs.dev/guide/).

**Comment by gioboa** [comment]
@supfiger I created a PR for that in the Vite repo, you can use that workaround.
Change the `qwikVite` plugin to support this config
```qwikVite({ csr: true, })```
is complicated and time consuming I guess.
