### ISSUE TITLE
[🐞]qwik add auth installed 3m old @auth/core module and lacks support for update session

### ISSUE THREAD

**Issue by rolanday** [QwikDev/qwik#4881]
### Which component is affected?

Qwik Runtime

### Describe the bug

Newer versions of @auth/core include support for invoking session update from client w/ requiring page reload. From module's `types.ts` , note newSession and trigger below. See https://next-auth.js.org/getting-started/client , **Updating the session** section for use case (yes, doc ref is for next-auth, not @auth/core, but same capability carried fwd into core package). @auth/core, which is what `qwik add auth` installs is 3 month old auth module , and lacks the latest features including option to trigger session update.

  session: (
    params:
      | {
          session: Session
          /** Available when {@link AuthConfig.session} is set to `strategy: "jwt"` */
          token: JWT
          /** Available when {@link AuthConfig.session} is set to `strategy: "database"`. */
          user: AdapterUser
        } & {
          newSession: any
          trigger: "update"
        }
  ) => Awaitable<Session | DefaultSession>

### Reproduction

N/A

### Steps to reproduce

N/A

### System Info

```shell
N/A
```

**Comment by maieulchevalier** [comment]
Question: Have you tried updating @auth/core to the latest version? I haven't tried it yet but I don't see why it shouldn't work.

**Comment by PatrickJS** [comment]
should be fixed with latest version of auth core
https://github.com/QwikDev/qwik/pull/6147
