### ISSUE TITLE
[🐞] playground v1.1.5 error

### ISSUE THREAD

**Issue by samijaber** [QwikDev/qwik#4899]
### Which component is affected?

Qwik Runtime

### Describe the bug

If there's an `import('./some-module.js')` in the module scope of a file, it causes erratic build issues, where event handlers and other functions are no longer being exported. This happens only in a library that gets built and imported into a qwik app. If this code exists in the qwik webapp directly, there are no issues.

### Reproduction

https://github.com/samijaber/qwik-import-bug-repro/

### Steps to reproduce

- `pnpm i`
- `pnpm build` in `sdk/`
- `pnpm dev` in `webapp/`
- 
![CleanShot 2023-08-01 at 10 31 10@2x](https://github.com/BuilderIO/qwik/assets/1393142/ade28619-31ec-447e-8ffa-c3106d7bdd1f)

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 84.09 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.asdf/installs/nodejs/18.13.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.13.0/bin/yarn
    npm: 8.19.3 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 115.1.56.14
    Chrome: 115.0.5790.114
    Firefox: 109.0.1
    Safari: 15.2
```
```


### Additional Information

_No response_

**Comment by gioboa** [comment]
I tested the shorter example with the new playground and it's working fine.
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
Thanks
