### ISSUE TITLE
[🐞] Redirects don't work with queries on routeAction$

### ISSUE THREAD

**Issue by gustavocadev** [QwikDev/qwik#4910]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I expect to be redirected to the query of my form, but it doesn't work, I use sveltekit and it works well I expect the same of Qwik
![image](https://github.com/BuilderIO/qwik/assets/84424661/2f5c8ab3-2da9-4dc9-b1af-20bdb5100f1a)

### Reproduction

https://github.com/gustavocadev/qwik-query

### Steps to reproduce

`pnpm install` followed by `pnpm dev`

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 5.83 GB / 12.92 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.5 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.22621.2070.0), Chromium (115.0.1901.188)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: ^1.2.6 => 1.2.6
    @builder.io/qwik-city: ^1.2.6 => 1.2.6
    undici: 5.22.1 => 5.22.1
    vite: 4.4.0 => 4.4.0
```

**Comment by octet-stream** [comment]
Isn't this similar to https://github.com/QwikDev/qwik/issues/6103? I already sent a PR https://github.com/QwikDev/qwik/pull/6410, but it seem to need further discussion.

**Comment by gioboa** [comment]
@octet-stream yup, thanks
