### ISSUE TITLE
[🐞] useComputed$ needs to do an equals check

### ISSUE THREAD

**Issue by FlatMapIO** [QwikDev/qwik#4918]
### Which component is affected?

Qwik Runtime

### Describe the bug

Currently, computed does not do an equals check, so even if the result is always true, it will still trigger the task to rerun. This is clearly not the expected behavior. I hope useComputed can add an equals option and set it to Object.is, otherwise it seems pointless for it to exist.

### Reproduction

https://stackblitz.com/edit/qwik-starter-2t6x22?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

```tsx
export default component$(() => {
  const countRef = useSignal(0);
  const isGreetOneRef = useComputed$(() => {
    return countRef.value > 1;
  });
  useTask$(({ track }) => {
    track(isGreetOneRef);
    console.log(" run task ");
  });
  return (
    <div>
      <button onClick$={() => (countRef.value = countRef.value + 1)}>
        incr
      </button>
    </div>
  );
});

```

### System Info

```shell
NONE
```

**Comment by shairez** [comment]
Thanks for the report @FlatMapIO !

Reviewed it, seems like it's worth investigating further

**Comment by gioboa** [comment]
Same behavior with v1.5.7.
@Varixo is it fixed in v2? can you check it please? Thanks

**Comment by Varixo** [comment]
> Same behavior with v1.5.7. @Varixo is it fixed in v2? can you check it please? Thanks

We should check this after v2 signals implementation

**Comment by Varixo** [comment]
Thank you for the clear reproduction! This should be fixed in v2 release, so I am going to close that issue
