### ISSUE TITLE
[✨] Valibot Adapter for Qwik

### ISSUE THREAD

**Issue by mees-van-wel** [QwikDev/qwik#4924]
### Is your feature request related to a problem?

[Valibot](https://valibot.dev/) presents a modern approach to data validation. While it parallels Zod in functionality, Valibot stands out due to its modular design and the significant reductions in bundle size (up to 98%) it can achieve through code splitting.

### Describe the solution you'd like

To better leverage Valibot's capabilities within the Qwik framework, I suggest introducing a `valibot$()` function. This function would integrate with `routeAction$()` and `globalAction$()`, accepting a Valibot schema as its parameter.

### Describe alternatives you've considered

While there are other validation libraries available, Valibot's bundle size advantage makes it an attractive choice for performance-focused applications. The direct integration of Zod was an initial consideration given its similarities, but the potential bundle size savings with Valibot make it a compelling option to explore further.

**Comment by brandonpittman** [comment]
Here's the current Zod implementation. Wonder if just swapping out the Zod bits for Valibot would suffice?

https://github.com/BuilderIO/qwik/blob/a6d6532bdc96b3b9b1f9689279c71c7f9cf90ca8/packages/qwik-city/runtime/src/server-functions.ts#L236-L281

**Comment by brandonpittman** [comment]
Trying to add a `valibotQrl` export to Qwik, but getting this error at build.

`"valibotQrl" is part of the package's API, but it is missing a release tag (@alpha, @beta, @public, or @internal)`

Can anyone tell me what to do with this?

**Comment by zanettin** [comment]
pinging @fabian-hiller 😎 hope you can help on this?

**Comment by fabian-hiller** [comment]
In some API file a release tag must be set. I think you @zanettin can help better with this.

@brandonpittman feel free to show me your code, I'll give you feedback and help you add the adapter to Qwik. Miško had already asked me to add it to Qwik Laps. However, I had not yet found the time to do so.

**Comment by shairez** [comment]
solved by #6752
