### ISSUE TITLE
[🐞] Path Resolution Issue: '~/' Prefix Not Resolving Modules Properly

### ISSUE THREAD

**Issue by kralion** [QwikDev/qwik#4948]
### Which component is affected?

Qwik Runtime

### Describe the bug

I am running npm start for the first time, What i expect is the first renfer of Qwik. What actually happening is 
![image](https://github.com/BuilderIO/qwik/assets/66649036/041f5509-8f83-482c-8899-ad13a41caec3)

### Reproduction

https://github.com/Dv-Joan/qwik-issue-repo.git

### Steps to reproduce

Create the Basic app template followed by npm install and finally npm start

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 2.11 GB / 7.85 GB
 Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
 Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.203)
    Internet Explorer: 11.0.19041.1566
```

### Additional Information

Files are there
![image](https://github.com/BuilderIO/qwik/assets/66649036/c8955087-212e-47f1-aa4a-5392309ed409)
This is my **tsconfig.json**
![image](https://github.com/BuilderIO/qwik/assets/66649036/1d6e38ec-574b-41c3-ada3-c6a8443e52b8)
and **i tried this** modification
![image](https://github.com/BuilderIO/qwik/assets/66649036/dbb98ea4-c2cb-4d95-ae82-96f240c6579a)
but it doesn't work. **I have to** use this type of import 
![image](https://github.com/BuilderIO/qwik/assets/66649036/f8fdbd89-51fd-4a9c-9e97-815f564a592e)
to work but on all files **to make it work**

**Comment by sarvex** [comment]
I am facing the same issue

**Comment by mhevery** [comment]
Is this a windows issue?

**Comment by Dv-Joan** [comment]
> Is this a windows issue?

Maybe, i dont try on mac

**Comment by mhevery** [comment]
It would be great if someone with a Windows machine could look into it.

**Comment by Axibord** [comment]
I couldn't reproduce the bug on Windows 11 (in/out WSL), everything works fine.

**Comment by Axibord** [comment]
> It would be great if someone with a Windows machine could look into it.

I couldn't reproduce the bug on Windows 11 (in/out WSL) everything works fine. Maybe W10 path resolution is different 

### System info
```
OS: Windows 11 Pro
Version: 22H2
OS build: 22621.2215
Processor: AMD Ryzen 9 7900X 12-Core 4.70 GHz

node: 18.16.0
npm: 9.6.5
```

**Comment by sarvex** [comment]
@Axibord the problem is easily reproducible on Windows 11 in `powershell`. The path resolution is superceded by the $HOME variable in Windows 11

```powershell
OS: Windows 11 Pro
Version: 22H2
OS build: 22621.2215
Processor: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   2.30 GHz

node: 20.6.1
npm: 9.8.1
pnpm: 8.7.4
```

**Comment by Charlygraphy23** [comment]
I will look into this issue. First, need to identify if the issue is windows only.

**Comment by Charlygraphy23** [comment]
> Reproduction
https://github.com/Dv-Joan/qwik-issue-repo.git



Hi your reproduction link is not working, can you provide a working one.

**Comment by sarvex** [comment]
For me, the problem is with the FS module which is unable to follow the symlink in Windows.

**Comment by mhevery** [comment]
If someone with Windows could try to create a fix I would be happy to provide support.

**Comment by DerTimonius** [comment]
Currently trying to reproduce this issue on Windows 11 with the steps provided in the description:

- creating a new app with the basic template
- change the import of a component from a relative to absolute path.
- start the app
	- no error with git bash
	- no error with Powershell
	- no error with CMD

Maybe it's possible that the issue is either resolved or an isolated issue with Windows 10? @Dv-Joan

**Comment by sarvex** [comment]
@DerTimonius @mhevery the issue is with the fs package being unable to handle Windows symlinks.

**Comment by gioboa** [comment]
@sarvex Is there a specific fs issue related to this problem? Can you post here the link?

**Comment by sarvex** [comment]
@gioboa 

I can put in the steps to reproduce the issue, and the issue is not only with Qwik but also with other frameworks that create project files like Astro or Svelte

1. Create a symlink folder in Windows i.e. something like `%USER_PROFILE%\Sources` to `D:\Sources`
2. Create a new project in %USER_PROFILE%\Sources using the `pnpm create Qwik`
3. Run the project 

You will see problems like files not found, CSS not loaded, etc...

**Comment by gioboa** [comment]
Are you using powershell or WSL2?

**Comment by wmertens** [comment]
@sarvex Looks like nodejs and symlinking on windows isn't a great combo? https://github.com/nodejs/node/issues/18518

I presume that the symlink you created is an actual symlink and not a .lnk file?

**Comment by sarvex** [comment]
@gioboa I am using PowerShell

@wmertens Yeah, I recently realized that symlinking is bad, but the problem only comes with 'pnpm create' and not with any other use cases. Also, I am using the actual symlink using 'New-Item SymbolicLink` command

**Comment by DerTimonius** [comment]
@sarvex I used npm and yarn fyi

**Comment by Dv-Joan** [comment]
> > Reproduction
> 
> https://github.com/Dv-Joan/qwik-issue-repo.git
> 
> 
> 
> 
> 
> 
> 
> Hi your reproduction link is not working, can you provide a working one.

Sorry man, I deleted the repo

**Comment by gioboa** [comment]
Do you have the same issue with the latest version of Qwik (v. 1.3.1) ?

**Comment by Dv-Joan** [comment]
> Do you have the same issue with the latest version of Qwik (v. 1.3.1) ?

I works well with 'npm ...' but with 'pnpm .... ' i have this error

![Console Screenshot](https://github.com/BuilderIO/qwik/assets/66649036/2e1de762-1873-4099-9a5d-1b007e97d0b3)

**Comment by gioboa** [comment]
Did you remove node_modules and install the deps again with pnpm?

**Comment by Dv-Joan** [comment]
> Did you remove node_modules and install the deps again with pnpm?

No, I just follow this docs for pnpm 

![image](https://github.com/BuilderIO/qwik/assets/66649036/22fd3a59-0af9-438d-a1ed-60f6011cb59f)

**Comment by gioboa** [comment]
@kralion Did you solve this issue or is it still open?
