### ISSUE TITLE
[🐞] popovertarget API breaks build

### ISSUE THREAD

**Issue by GrandSchtroumpf** [QwikDev/qwik#4949]
### Which component is affected?

Qwik Runtime

### Describe the bug

When using the popover api typescript complains that "property 'popovertarget' does not exist on type 'ButtonHTMLAttributes<HTMLButtonElement>'"
I know popover api is only supported in chromium and behind flags for Safari & Firefox, but the API won't change anymore and all major browsers are implementing it, so I think it makes sense to support it too as **it breaks build**...

### Reproduction

N/A

### System Info

```shell
System:
    OS: Windows 10 10.0.22623
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 20.59 GB / 31.71 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.3.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1095.0), Chromium (115.0.1901.203)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: ^1.2.7 => 1.2.7
    @builder.io/qwik-city: ^1.2.7 => 1.2.7
    @builder.io/qwik-worker: ^0.0.1 => 0.0.1
    undici: 5.22.1 => 5.22.1
    vite: ^4.4.7 => 4.4.7
```

**Comment by wmertens** [comment]
fixed long ago :)
