### ISSUE TITLE
[✨] Reusable attributes (Directive)

### ISSUE THREAD

**Issue by GrandSchtroumpf** [QwikDev/qwik#4972]
### Is your feature request related to a problem?

Often we want apply the same logic on multiple HTML element regardless of the tag of this element. For example :
```jsx
return <>
  <button ripple onClick$={...}>Click me</button>
  <a ripple>Click me</a>
</>
```
In this example the ripple property would trigger effect on click.

This is currently very difficult to achieve that with Qwik because 
- it should work on server and browser without eager execution with `useVisibleTask$`.
- it shouldn't override other attributes

Other frameworks have similar concept:
- Vue: [custom directives](https://vuejs.org/guide/reusability/custom-directives.html)
- Angular: [attribute directive](https://angular.io/guide/attribute-directives)
- Svelte: [actions](https://svelte.dev/docs/svelte-action)

### Describe the solution you'd like

Several options : 

1. Have a dedicate `directive$` method that support `use*`
```jsx
export const ripple = directive$(() => {
  const el = useElement(); // Access current element
  const theme = useContext(THEME); // Access context
  appendEventListener(el, 'click', $(() => ...)); // Append an event on click that will be serialized
});
export default component$(() => {
  return <>
    <button ripple onClick$={...}>Click me</button>
    <a ripple>Click me</a>
  </>
})
```

2. Provide method to modify the DOM on the server
```jsx
function addRipple(element: HTMLElement, theme: Theme) {
  appendEventListener(element, 'click', $(() => {...})); // add QRL in the `onClick$` of the element
}
export default component$(() => {
  const theme = useContext(THEME);
  const btn = useSignal<HTMLElement>();
  const anchor = useSignal<HTMLElement>();
  addRipple(btn, theme);
  addRipple(anchor, theme);
  return <>
    <button ref={btn} onClick$={...}>Click me</button>
    <a ref={anchor}>Click me</a>
  </>
})
```

3. Mix of both
```jsx
export const ripple = directive$(function ({ theme }: { theme: Theme }) {
  const el = this; // Access current element with this or with a props 
  appendEventListener(el, 'click', $(() => ...)); // Append an event on click that will be serialized
});
export default component$(() => {
  const theme = useContext(THEME);
  return <>
    <button ripple={theme} onClick$={...}>Click me</button>
    <a ripple={theme}>Click me</a>
  </>
})
```

### Describe alternatives you've considered

We can have a merger function : 
```jsx
return <>
  <button {...directive<'button'>({ ref: btn, class: 'btn', onClick$: ... }, ripple(theme) )}>Click Me</button>
  <a {...directive<'a'>({ href: '...', style: '--color: blue' }, ripple(theme))}>Click Me</a>
</>
```
This is what I'm currently doing, but you have to put all the properties in the merger function.

Maybe we can wrap the element with another component and mutate the children like in React, but I didn't manage to do that.

**Comment by shairez** [comment]
Yeah adding more stuff to the core is something we try to avoid unless absolutely necessary, so maybe this could be a userland library.

I think a combination of using a custom hook for configuration and for getting the result and then spreading it is on the component is the easist way to achieve it (similar to what you're doing, but having the configuration happenning outside the JSX)

btw if you need custom events, you can take a similar approach to [the one used in here](https://github.com/BuilderIO/qwik/blob/main/packages/insights/src/components/symbol-tile/index.tsx#L155)

So I'm leaving this one open to see how many 👍 we get, and it could be a good indication that a library is needed

Thanks again!

**Comment by GrandSchtroumpf** [comment]
Thanks for the answer @shairez. I'll be happy to publish a library if we find a good design for that.
I'm suggesting to use this issue to discuss how it should look like, I hope it's ok.

For me a directive should :
- [ ] be attached on an Element
- [ ] be able to use `use*` methods
- [ ] modifies one or many attributes from the Element it's on
- [ ] modification should support `Signal` & store
- [ ] merge attributes when applicable, else override attribute based on order
- [ ] attributes should be serialized

Here is the list the attributes that could be merged : 
- selector: `id`, `class`
- `style`
- events: `onChange$`, `onKeydown`, ...
- let me know if you see other attributes that can accept multiple values in Qwik

On discord @wmertens suggested to do something like Styled component.
So as a first draft I'm thinking about something like that: 

```tsx
// useRipple can only be used on "button" et "a" element
// return value should be a union of the HTMLButtonAttributes & HTMLAnchorAttributes
const useRipple: Directive<"button" | "a"> = () => {
  const active = useSignal(false);
  const position = useSignal({ x: 0, y: 0 });
  const classes = useComputed$(() => active.value ? 'ripple active' : 'ripple');
  useStyles(rippleStyle);
  
  return {
    class: classes,
    style: {
      ['--ripple-x']: position.value.x,
      ['--ripple-y']: position.value.y
    },
    onClick$: $((event, element) => {
      active.value = true;
      position.value = { x: element.clientX - ..., y: element.clientY - ... };
      element.addEventListener('animationend', () => active = false, { once: true });
    })
  }
}

export default component$(() => {
  const color = useSignal('blue');
  const ripple = useRipple();
  // useDirective will merge all attributes and return a component that can be extended
  const Button = useDirective('button', [
    { class: 'btn' },
    cssvar({ color }),
    ripple,
  ]);
  const Anchor = useDirective('a', {
    { class: 'btn', href: "will-be-overridden" },
    ripple,
  });
  return <>
    <Button onClick$={doSomething}>Click Me</Button>
    <Anchor href="final-href">Click Me</Anchor>
  </>
})
```
The `Button` should look like that in the end : 
```html
<style>
  /* Style of the ripple here */
</style>
<button class="btn ripple active" style="--color: blue; --ripple-x: 0; --ripple-y: 0;" onClick$={[doSomethingQRL, rippleQRL]}>
  Click Me
</button>
```
It's not the best devX, but I think it can do the job.
Let me know what you think about it.

**Comment by wmertens** [comment]
I'm going to close this, but if you find that this is a nice way of doing things, perhaps you can add a cookbook entry?
