### ISSUE TITLE
InferModel is @deprecated for -> InferSelectModel & InferInsertModel

### ISSUE THREAD

**Issue by serbyxp** [QwikDev/qwik#5015]
can be updated to 
https://github.com/BuilderIO/qwik/blob/f0a37310aa6c744a95f13aeee275c84b5b726835/packages/insights/src/db/sql-manifest.ts#L1
`import { eq, and, type InferSelectModel, sql } from 'drizzle-orm';`

https://github.com/BuilderIO/qwik/blob/f0a37310aa6c744a95f13aeee275c84b5b726835/packages/insights/src/db/sql-manifest.ts#L9
`): Promise<InferSelectModel<typeof manifestTable>[]> {`

https://github.com/BuilderIO/qwik/blob/f0a37310aa6c744a95f13aeee275c84b5b726835/packages/insights/src/db/sql-manifest.ts#L41
`): Promise<InferSelectModel<typeof manifestTable>> {`

https://github.com/BuilderIO/qwik/blob/f0a37310aa6c744a95f13aeee275c84b5b726835/packages/insights/src/db/query-helpers.ts#L1
`import { sql, type InferInsertModel } from 'drizzle-orm';`

https://github.com/BuilderIO/qwik/blob/f0a37310aa6c744a95f13aeee275c84b5b726835/packages/insights/src/db/query-helpers.ts#L84
`}): InferInsertModel<typeof edgeTable> {`

https://github.com/BuilderIO/qwik/blob/f0a37310aa6c744a95f13aeee275c84b5b726835/packages/insights/src/db/query-helpers.ts#L633
`}): InferInsertModel<typeof routesTable> {`

**Comment by mhevery** [comment]
The latest version of drizzle brakes type inference in Qwik-insights. I need to revert.

**Comment by gioboa** [comment]
I check the actual code and we are using the new types eg. `InferInsertModel`
I close this. Thanks
