### ISSUE TITLE
[✨] granularly disable qwik inspector click to source

### ISSUE THREAD

**Issue by mikehaas763** [QwikDev/qwik#5016]
### Is your feature request related to a problem?

I have a <Text> component that is used to enforce a specific list of text styles allowed on a project. However, every time someone alt-clicks with the qwik inspect, it brings them to that Text component, and not the place where that text component is used.

```tsx
<Text variant="heading-page">My Heading</Text>
```

### Describe the solution you'd like

It would be nice to selectively mark specific components as being exempt from the qwik inspector click to source feature.

### Describe alternatives you've considered

Convert to an inline component, and pass the content as a prop. I'm not sure if inline components are still marked for inspection or not though

**Comment by zanettin** [comment]
Hi @mikehaas763 
If you would like to implement this functionality: here is a good [starting point](https://github.com/BuilderIO/qwik/blob/main/packages/qwik/src/optimizer/src/plugins/click-to-component.html).

Just as a possible way to implement this: if you add the `data-qwik-inspector` attribute manually to your component it's persisted and won't be overwritten. This way you could pass the path to the component you'd expect your devs to land on. If we would pass `"false"` or an empty value, the script could just ignore it and don't navigate.

**Comment by lbensaad** [comment]
Good, I also thought about that. But like that, you will need to change your code for the inspector. Isn't better, if possible of course, to have the the inspector pull the list of parent components as a dropdown list  and you select one of them.
Also is there a way to disable it. It annoys me as I have a bottom navigation menu in exactly that place and I always have to wait for the inspector to disappear in order to be able to click the menu.

**Comment by zanettin** [comment]
Not sure if this dropdown approach would be possible based on your specific example since i think you switch the child based on a prop, right. so the conext is not that easy to resolve.

you totally can disable the inspector if you like: https://github.com/BuilderIO/qwik/pull/2375.

**Comment by kanielrkirby** [comment]
@zanettin Is this issue still open and in need of help? I'd be happy to give it a shot, if so. Just let me know!
