### ISSUE TITLE
[✨] When closing over values in `server$` the values should be marked as readonly

### ISSUE THREAD

**Issue by mhevery** [QwikDev/qwik#5019]
### Is your feature request related to a problem?

Given:
```typescript
export default component$(() => {
  const count = useSignal(0);
  return (
    <button onClick$()={() => {
           server$(() => count.value++); // <== `count` here is a copy
         }}>
      Count: {count.value}
    </button>
  );
});
```

When calling `server$()`, the system serializes values and sends them to the server. Thes values are a copy, which means any mutatations of the values will not be reflected to the client.

A better implementation would be to freeze these objects so that any modification on server will throw an error make it clear to the developer that mutations are not allowed (rather than silent failures in current implementation) 

### Describe the solution you'd like

Any values serialized by `server$()` should be marked as immutable and throw a clear message to the developer that mutation is not allowed.

### Describe alternatives you've considered

n/a

**Comment by gioboa** [comment]
Closed by #5238
