### ISSUE TITLE
[🐞] globalAction$ is not working properly in express server adapter!

### ISSUE THREAD

**Issue by saeedhbi** [QwikDev/qwik#5044]
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm trying to create a shareable `globalAction$` but I don't know which part I'm missing. It's not working.

In my local machine, in `dev` mode everything is running without problem, but in `production` mode, I'm receiving this error:

`SyntaxError: Unexpected token 'o', "[object Asy"... is not valid JSON`

It seems the action is losing the state and inputs are not handled. It is receiving a `{"[object AsyncGenerator": ""}`.

I tried to create a new instance in Stackblitz and there is another error regarding this:

`TypeError: out2Clone.tee is not a function or its return value is not iterable`

It's a simple application that has a `useGetTestGlobalAction` action in the `counter` component and I'm using it in the `hero` component by submitting a button. Do I missing anything?

The stack of errors is this:

`TypeError: out2Clone.tee is not a function or its return value is not iterable
    at cloneBody (file:///home/projects/qwik-starter-fesiaz/node_modules/undici/lib/fetch/body.js:284:36)
    at cloneRequest (file:///home/projects/qwik-starter-fesiaz/node_modules/undici/lib/fetch/request.js:806:23)
    at Request.clone (file:///home/projects/qwik-starter-fesiaz/node_modules/undici/lib/fetch/request.js:715:27)
    at mt (file:///home/projects/qwik-starter-fesiaz/server/entry.express.mjs:31:5247)
    at Object.parseBody (file:///home/projects/qwik-starter-fesiaz/server/entry.express.mjs:31:4727)
    at eval (file:///home/projects/qwik-starter-fesiaz/server/entry.express.mjs:27:255)
    at Object.he [as next] (file:///home/projects/qwik-starter-fesiaz/server/entry.express.mjs:31:3145)
    at ot (file:///home/projects/qwik-starter-fesiaz/server/entry.express.mjs:31:839)
    at Object.he [as next] (file:///home/projects/qwik-starter-fesiaz/server/entry.express.mjs:31:3145)
    at async yt (file:///home/projects/qwik-starter-fesiaz/server/entry.express.mjs:31:5987)`

### Reproduction

https://stackblitz.com/edit/qwik-starter-fesiaz?file=src%2Fcomponents%2Fstarter%2Fhero%2Fhero.tsx

### Steps to reproduce

The production is built and you can see the error with running `npm run serve`.

Also, the `dev` mode has a problem too.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
  npmPackages:
    @builder.io/qwik: latest => 1.2.10 
    @builder.io/qwik-city: latest => 1.2.10 
    undici: 5.22.1 => 5.22.1 
    vite: 4.3.5 => 4.3.5
```

**Comment by gioboa** [comment]
Hi @saeedhbi I faced this error yesterday so I know the resolution.
You need to use node 18 or above. Let me know.
Unfortunately StackBlitz is blocked to node 16.

**Comment by saeedhbi** [comment]
@gioboa I do have version 20.1 on my local machine and the above information is for StackBlitz.

This is my information:

```System:
    OS: Linux 5.15 elementary OS 6.1 Jólnir
    CPU: (4) x64 Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
    Memory: 5.63 GB / 15.52 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 20.1.0 - ~/.nvm/versions/node/v20.1.0/bin/node
    npm: 9.6.4 - ~/.nvm/versions/node/v20.1.0/bin/npm
    pnpm: 8.5.1 - ~/.nvm/versions/node/v20.1.0/bin/pnpm
  Browsers:
    Brave Browser: 100.1.37.113
    Chrome: 116.0.5845.96
  npmPackages:
    @builder.io/qwik: ^1.2.6 => 1.2.6 
    @builder.io/qwik-auth: ~0.1.0 => 0.1.0 
    @builder.io/qwik-city: ^1.2.6 => 1.2.6 
    undici: ^5.22.0 => 5.22.0 
    vite: 4.3.5 => 4.3.5 
```

**Comment by saeedhbi** [comment]
> I cloned your example in my local machine and it's working fine in `dev` and with the `node adapter`
> 
> ```
> System:
>     OS: macOS 13.4.1
>     CPU: (8) arm64 Apple M1
>     Memory: 165.00 MB / 16.00 GB
>     Shell: 5.9 - /bin/zsh
> Binaries:
>     Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
>     Yarn: 1.22.10 - /opt/homebrew/bin/yarn
>     npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
>     pnpm: 8.7.0 - /opt/homebrew/bin/pnpm
> npmPackages:
>     @builder.io/qwik: latest => 1.2.10 
>     @builder.io/qwik-city: latest => 1.2.10 
>     undici: 5.22.1 => 5.22.1 
>     vite: 4.3.5 => 4.3.5 
> ```

It's weird for me. I'm using the mono repo structure but the actions are inside `src` directory. I can't trace the problem.

The only thing that the question for me, is: 

Why I do have `{"[object AsyncGenerator]": ""}` as input? I debug the request and the payload is sending correctly, but inside the action QRL, the input is not the same as the request.

**Comment by saeedhbi** [comment]
OK! I found the problem but I'm not sure if this is happening because of my environment or if there is an actual bug:

The problem is Qwik is passing the body of the request by [this](https://github.com/BuilderIO/qwik/blob/10fe71d16bd5776215cd35983b61b47d7bd6e0a0/packages/qwik-city/middleware/node/http.ts#L63) to internal process. 

```
const getRequestBody = async function* () {
    for await (const chunk of req as any) {
      yield chunk;
    }
  };
```

It seems in my environment when an action wants to fetch in a client, the body is `{"[object AsyncGenerator": ""}` and it will go to the next states and is not handled by **parseBody** properly. So, the QwikCity client fetcher will get an error and the request will be stopped.

Since I do not have time now to troubleshoot this, I just added an express JSON parser middleware to my express server and replaced the generated express file with my usage by a vite post hook plugin:

Change this:
```
const options = {
    method: req.method,
    headers: requestHeaders,
    body: body as any,
    signal: controller.signal,
    duplex: 'half' as any,
  };
```
To:
```
const options = {
    method: req.method,
    headers: requestHeaders,
    body: req.header('Content-Type').includes('application/json') ? JSON.stringify(req.body) : body as any,
    signal: controller.signal,
    duplex: 'half' as any,
  };
```

I'm pretty sure that this hack is not a good idea but it's working for me now. Forward to hearing your idea.

**Comment by jmsegrev** [comment]
I'm having similar issue with `firebase adapter` for POST requests. Since by the time firebase function handler is called the request body was already parsed and its not a readable stream anymore, `getRequestBody` yields nothing.

**Comment by PatrickJS** [comment]
is this still an issue?

**Comment by PatrickJS** [comment]
I don't see the error and the stackblitz is using "latest" version so I'm going to close this
