### ISSUE TITLE
Error boundaries [✨]

### ISSUE THREAD

**Issue by iamhassanfaraji** [QwikDev/qwik#5096]
### Is your feature request related to a problem?

error handing in jsx

### Describe the solution you'd like

in react the "componentDidCatch" lifecycle can receive an error of jsx rendering in production and prevent breaking the whole app
and other jsx rendere 

### Describe alternatives you've considered

dont have other idea

**Comment by gioboa** [comment]
Hi @iamhassanfaraji , can you create a reproducible repo? Can you insert a title to this issue pls?

**Comment by mhuretski** [comment]
https://stackblitz.com/edit/qwik-starter-a6bqm3?file=src%2Froutes%2Findex.tsx

runtime error might occur inside jsx, using QwikCity error resolves in `minimalHtmlResponse(500, "Internal Server Error")`

<img width="689" alt="image" src="https://github.com/BuilderIO/qwik/assets/22213256/ec177163-7a69-4306-a26b-57d7b2273562">

it would be great to have mechanism to handle runtime errors

**Comment by PatrickJS** [comment]
dupe of https://github.com/QwikDev/qwik/issues/3720
