### ISSUE TITLE
[🐞] QwikLoader missing in Storybook

### ISSUE THREAD

**Issue by O-Hooman** [QwikDev/qwik#5157]
### Which component is affected?

Qwik Runtime

### Describe the bug

it seems useVisibleTask$ not working (the code inside is not executed) but useTask$ is working

### Reproduction

https://stackblitz.com/edit/qwik-starter-4bzif2

### Steps to reproduce

pnpm install && pnpm dev

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 38.41 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    pnpm: 8.6.3 - ~/.nvm/versions/node/v16.17.0/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.1
  npmPackages:
    @builder.io/dev-tools: ^0.1.10 => 0.1.10 
    @builder.io/qwik: ^1.2.10 => 1.2.10 
    @builder.io/qwik-city: ^1.2.10 => 1.2.10 
    @builder.io/sdk-qwik: ^0.5.9 => 0.5.9 
    undici: 5.22.1 => 5.22.1 
    vite: 4.3.9 => 4.3.9
```

### Additional Information

qwik v1.1.5 works but v1.2.x does not work

* What should I see?
console log of text "inside task" and "inside visible task"
* What do I click on?
button > Primary on storybook
* What you expect to happen?
console log "inside visible task" executed by useVisibleTask$
* What is happening instead?
console log "inside visible task" not executed (didn't show at console)

**Comment by mhevery** [comment]
can you provide repro instructions?
- What should I see
- What do I click on
- What you expect to happen
- What is happening instead?

**Comment by O-Hooman** [comment]
> can you provide repro instructions?
> 
> * What should I see
> * What do I click on
> * What you expect to happen
> * What is happening instead?


can you provide repro instructions?

* console log of text "inside task" and "inside visible task"
* button > Primary on storybook
* console log "inside visible task" executed by useVisibleTask$
* console log "inside visible task" not executed (didn't show at console)

**Comment by mhevery** [comment]
The application does not work because there is no `<script id="qwikloader">...</script>` on the page. I am not an expert of how this was integrated with storybook, but I am pretty sure that adding that will fix the codebase.

Once fixed it would be great to update the instructions https://qwik.builder.io/docs/integrations/storybook/ for others.

**Comment by shairez** [comment]
seems like this is fixed via https://github.com/literalpie/storybook-framework-qwik/pull/68

closing
