### ISSUE TITLE
[🐞] Bugsnag JS SDK not working

### ISSUE THREAD

**Issue by y471n** [QwikDev/qwik#5191]
### Which component is affected?

Qwik Runtime

### Describe the bug

The Bugsnag SDK throws a timeout when trying the trivial setup example. The network call isn't succeeding in neither dev mode or the production build. 
![Screenshot 2023-09-19 at 10 54 31 AM](https://github.com/BuilderIO/qwik/assets/2056046/3fa3f1c2-7480-4b5d-b209-ca865374b9b0)

### Reproduction

https://stackblitz.com/edit/qwik-starter-dnd29b?file=src%2Froot.tsx

### Steps to reproduce

1. Install
```npm install --save @bugsnag/js```
2. Initialise:
```
import Bugsnag from '@bugsnag/js'
Bugsnag.start({ apiKey: API_KEY})
```
3. Notify error:
```
Bugsnag.notify(new Error('Test error'))
```

### System Info

```shell
NA
```

**Comment by y471n** [comment]
Sorry for the late reply. I am able to integrate Busgnag with NextJS successfully. In QwikJS the connection gets timed-out. It might not be Qwik issue but I might be implementing something wrong here specific to Qwik.

<img width="1011" alt="Screenshot 2023-09-24 at 9 21 05 AM" src="https://github.com/BuilderIO/qwik/assets/2056046/4fdf4c0b-9876-4284-b6ac-739303f38f21">

**Comment by mhevery** [comment]
I need clear reproduction steps; otherwise, I can't help.

**Comment by PatrickJS** [comment]
closing. please add reproduction steps
