### ISSUE TITLE
How do we use script elements

### ISSUE THREAD

**Issue by Nedimko123** [QwikDev/qwik#5232]
I cannot seem to use Nuvo - https://docs.getnuvo.com/sdk/start/:

`
<!DOCTYPE html>
<html>
  <body>
    <script src="https://unpkg.com/nuvo-vanilla-js@latest"></script>
    <script type="text/javascript">
      const settings = {
        developerMode: true,
        identifier: "product_data",
        columns: [
          {
            label: "Product ID",
            key: "product_id",
          },
          {
            label: "Article Name",
            key: "article_name",
          },
        ],
      };

      const nuvoImporter = new window.nuvo.NuvoImporter("Your License Key", settings);

      nuvoImporter.onResults((values, identifier, complete) => {
        console.log("Result:", values);
        console.log("Identifier:", identifier);
        complete();
      });

      nuvoImporter.onCancel(() => {
        console.log("onCancel");
      });

      nuvoImporter.registerEntryInit((row) => {
        return { product_id: { value: row.product_id + " on init" } };
      });

      nuvoImporter.registerEntryChange((row, rowIndex) => {
        return { product_id: { value: row.product_id + " on change" } };
      });

      nuvoImporter.registerColumnHooks("article_name", (hookedRecordValues) => {
        return new Promise((resolve) => {
          setTimeout(() => {
            resolve(
              hookedRecordValues.map(([row, rowIndex]) => {
                return [
                  {
                    value: "#NU" + row,
                    info: [
                      {
                        level: "warning",
                        message: "This is a warning",
                      },
                    ],
                  },
                  rowIndex,
                ];
              })
            );
          }, 0);
        });
      });

      nuvoImporter.launch();
    </script>
  </body>
</html>`

Whenever I try to use nuvo it always goes to the bottom of the page as it is rendered as an iframe, I think. No matter what styling I use

```

export const NuvoImporterComponent = component$((props) => {

	useVisibleTask$(() => {
		const settings = {
			developerMode: true,
			identifier: 'product_data',
			modal: false,
			columns: NuvoRecordListItemColumns,
		}

		const nuvoImporter = new Nuvo.NuvoImporter(import.meta.env.VITE_NUVO_IMPORTER_LICENSE_KEY, settings)


		nuvoImporter.launch()
	})

	return (
		<>
			<div id='nuvo-importer'></div>
		</>
	)
})

export default NuvoImporterComponent
```

**Comment by maiieul** [comment]
Your code isn't properly formatted. Where did you put your script in?

**Comment by mhevery** [comment]
Can you create easier reproduction for us with http://qwik.new

**Comment by tzdesign** [comment]
@Nedimko123 why don't you do a dynamic import and build a clean component which holds state and uses the qwik-life-cycle methods or is this globally? If you use it like this and do client side navigation, it might render again if you place it in a certain location?

If we use scripts in our very large application we use:

```tsx
<script src="https://unpkg.com/nuvo-vanilla-js@latest"></script>{' '}
      <script
        type="text/javascript"
        dangerouslySetInnerHTML={` const settings = { developerMode: true, identifier: "product_data", columns: [ { label: "Product ID", key: "product_id", }, { label: "Article Name", key: "article_name", }, ], };
      const nuvoImporter = new window.nuvo.NuvoImporter("Your License Key", settings);
    
      nuvoImporter.onResults((values, identifier, complete) => {
        console.log("Result:", values);
        console.log("Identifier:", identifier);
        complete();
      });
    
      nuvoImporter.onCancel(() => {
        console.log("onCancel");
      });
    
      nuvoImporter.registerEntryInit((row) => {
        return { product_id: { value: row.product_id + " on init" } };
      });
    
      nuvoImporter.registerEntryChange((row, rowIndex) => {
        return { product_id: { value: row.product_id + " on change" } };
      });
    
      nuvoImporter.registerColumnHooks("article_name", (hookedRecordValues) => {
        return new Promise((resolve) => {
          setTimeout(() => {
            resolve(
              hookedRecordValues.map(([row, rowIndex]) => {
                return [
                  {
                    value: "#NU" + row,
                    info: [
                      {
                        level: "warning",
                        message: "This is a warning",
                      },
                    ],
                  },
                  rowIndex,
                ];
              })
            );
          }, 0);
        });
      });
    
      nuvoImporter.launch();`}
      />
```
