### ISSUE TITLE
[🐞]` pnpm qwik add` added wrong shell scripts in  README.md 

### ISSUE THREAD

**Issue by harshmangalam** [QwikDev/qwik#5253]
### Which component is affected?

Qwik Runtime

### Describe the bug

I have created my README.md and using `pnpm` in my README but once i have added any new adapter i.e netlify it will add `p` before my all scripts now the problem is suppose i have a command `pnpm run dev` it becomes `ppnpm run dev`.

### Reproduction

https://github.com/harshmangalam/qwik-x

### Steps to reproduce

- Add any new adapter
- Verify the README file

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 121.77 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.6.12 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 117.0.5938.132
    Safari: 16.4
```

**Comment by gioboa** [comment]
Closed by #5275
