### ISSUE TITLE
[🐞] Use Promise.allSettled for useTask$

### ISSUE THREAD

**Issue by GrandSchtroumpf** [QwikDev/qwik#5289]
### Which component is affected?

Qwik Runtime

### Describe the bug

It looks like Qwik is using Promise.all to wait for all useTask$ to resolve. This prevent all task to resolve if one of them rejects.
```
at Module.get (<PROJECT>\app\src\service\queries\utils.ts:33:9)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async qrl (<PROJECT>\node_modules\.pnpm\@builder.io+qwik@1.2.12_undici@5.22.0\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:8248:24)
      at async AsyncFunction.useQuery_useTask_VW5jqtKnGPM (<PROJECT>\app\src\service\query.tsx:48:21)
      at async Promise.all (index 1)
      at async Promise.all (index 0)
      at async Promise.all (index 1)
      at async Promise.all (index 1)
      at async Promise.all (index 1)
      at async Promise.all (index 1)
```

I think this is happening here : https://github.com/BuilderIO/qwik/blob/main/packages/qwik/src/core/render/dom/notify-render.ts#L281

### Reproduction

N/A

### System Info

```shell
.
```

**Comment by wmertens** [comment]
AFAIK this is intentional, tasks should never reject

**Comment by GrandSchtroumpf** [comment]
Maybe add a warning then in the console to explain that this is on purpose. It took me sometime to figure out what was going on.
Out of curiosity, why a task should not reject ?

**Comment by wmertens** [comment]
Errors should be handled by the task function, so that expected errors can update the UI, and unexpected errors should break the application so that you can find what's wrong. Can you make a PR with a message that would have helped for you?

**Comment by GrandSchtroumpf** [comment]
It seems like a dangerous way to force developers to handle error catching. Let's say a developer didn't handle error in one of his task, and some analytics API fails in production, then all tasks will fail, breaking the whole app while it might have been harmless.
Except if there is reason specific to Qwik, I think the expected (and safer) solution is to forward the error into the console, as it's managed in any JS runtime.

**Comment by wmertens** [comment]
It's not showing the error in the console? That's a bug then. PR welcome :)

**Comment by wmertens** [comment]
BTW https://github.com/BuilderIO/qwik/pull/1780#discussion_r998567387

**Comment by GrandSchtroumpf** [comment]
The error is forwarded in the console, but if one reject all the other tasks won't resolve even if they could. So even if the app could have work, it won't because `Promise.all` didn't give it the possibility to.

**Comment by wmertens** [comment]
Hmm, I suppose the Promise.all could wrap each task in a console logger and back to allSettled like before.

**Comment by wmertens** [comment]
Did you read Manu's comment?

**Comment by GrandSchtroumpf** [comment]
I did. If you only wait for `Promise.allSettled` you'll loose all errors, so in this case `Promise.all()` seems like a better option. But it comes at the price of rejecting promises that would have work. Sometime it's the expected behavior, but in the case of tasks I don't think it is.

Bad: 
```typescript
// Will never catch
await Promise.allSettled();
```

Better:
```typescript
// Will over catch
await Promise.all();
```

Best:
```typescript
// Will catch only what has rejected
const results = await Promise.allSettled();
for (const result of results) {
  if (result.status === 'rejected') console.error(result.reason);
}
```

**Comment by mhevery** [comment]
I like the idea of adding an error handler to `console.error` the issue and moving on. Any chance we could get a PR for that?

**Comment by PatrickJS** [comment]
I made the pr. merging it now
