### ISSUE TITLE
[🐞] Don't force restore scroll on same page

### ISSUE THREAD

**Issue by GrandSchtroumpf** [QwikDev/qwik#5306]
### Which component is affected?

Qwik City (routing)

### Describe the bug

Currently if I navigation with type pushState & scroll: false then scroll is still restored.
This surely comes from [here](https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/runtime/src/qwik-city-component.tsx#L168). From my understanding, it assumes that same-page navigation means hash modification only, while it could also be a searchParams change.

```jsx
const nav = useNavigation();
const { url } = useLocation();
const updateSearch = $((params: Record<string, string>) => {
  const nextUrl = new URL(url);
  for (const [key, value] of Object.entries(params)) {
    nextUrl.seachParams.set(key, value);
  }
  nav(nextUrl.toString(), { type: 'pushState', scroll: false }); // scroll config ignored
})
```

### Reproduction

qwik.new not working

### System Info

```shell
System:
    OS: Windows 10 10.0.22623
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 24.03 GB / 31.71 GB
  Binaries:
    Node: 20.6.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.3.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.9.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.1095.0), Chromium (118.0.2088.41)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: ~1.2.13 => 1.2.13
    @builder.io/qwik-city: ~1.2.13 => 1.2.13
    undici: ^5.22.0 => 5.22.0
    vite: ~4.4.0 => 4.4.0
```

**Comment by GrandSchtroumpf** [comment]
Qwik.new has not been working since v1 for me, stackblitz is failing to display anything in the preview.Le 12 oct. 2023 15:47, Giorgio Boa ***@***.***> a écrit :
Thanks for reporting that, can you create a reproducible scenario with qwik.new pls ?

**Comment by wmertens** [comment]
Qwik.new works for me, try cheating all application data in the devtools application tab
