### ISSUE TITLE
[🐞] Vercel adapter removes client build output

### ISSUE THREAD

**Issue by danew** [QwikDev/qwik#5372]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

When building a qwik project in Vercel with a turborepository the "dist" folder cannot be found after the build succeeds.

```
Error: No Output Directory named "dist" found after the Build completed. You can configure the Output Directory in your Project Settings.
```

This started happening once we migrated our repository to a monorepo using Turbo. We are using the default deployment details for a Vite project and have just updated the root to be `apps/qwik`.

The weird thing is if we re-deploy the build it always succeeds, but the first build for a given branch always fails.

When I try reproduce it locally the `dist` folder never persists, I have detailed my local reproduction below:

When running `npm run build` the `dist` output folder gets removed during the `build.server` phase.

I verified this using a simple vite plugin which logs whether `dist` exists before (`buildStart`) and after (`buildEnd`), which in this case it does so it must be happening somewhere after this.

### Reproduction

https://github.com/danew/qwik-turborepo

### Steps to reproduce

1. Clone the repository
2. Install dependencies `npm install`
3. Move into app directory `cd apps/qwik`
4. Run the build `npm run build`

You will notice while the build runs that the client output `dist` exists after the "build.client" succeeds but gets removed after the "build.server" phase succeeds.

I have a package patch with the changes I used to debug this in the qwik cli.

### System Info

```shell
System:
    OS: macOS 12.6.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 12.49 GB / 64.00 GB
    Shell: 5.2.15 - /opt/homebrew/bin/bash
  Binaries:
    Node: 18.14.2 - ~/Library/Caches/fnm_multishells/44894_1698762604398/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/44894_1698762604398/bin/yarn
    npm: 9.5.0 - ~/Library/Caches/fnm_multishells/44894_1698762604398/bin/npm
    pnpm: 7.26.3 - ~/Library/pnpm/pnpm
  Browsers:
    Brave Browser: 118.1.59.124
    Chrome: 118.0.5993.117
    Chrome Canary: 120.0.6099.0
    Safari: 16.3
```
```


### Additional Information

_No response_

**Comment by mhevery** [comment]
You are using http://turbo.build, which is not supported. If you want to add support feel free to send PR to fix it.

I think this issue can be closed?

**Comment by danew** [comment]
> You are using http://turbo.build, which is not supported. If you want to add support feel free to send PR to fix it.
> 
> I think this issue can be closed?

The issues isn't directly related to turborepo since the build is just ran within the directory using NPM workspaces.

I just [removed turbo altogether on a branch](https://github.com/danew/qwik-turborepo/tree/npm-workspaces) and still encountered the same problems.

**Comment by danew** [comment]
I have debugged this further and found it is happening within Quick City's Vercel edge adapter.

```ts
      // move the dist directory to the vercel output static directory location
      await fs.promises.rename(clientPublicOutDir, vercelStaticDir);
```
https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/adapters/vercel-edge/vite/index.ts#L100

It's clearly deliberate so I'm curious if it's a case that documentation needs to be updated or this should be fixed.

**Comment by Loshido** [comment]
rewriting the adapter and 
commenting these lines [vercel-edge/vite/index.ts:83-100](https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/adapters/vercel-edge/vite/index.ts#L83-L100)
 **allows to fix the issue**.

You just copy & paste the function exported from adapters/vercel-edge/vite/index.ts (BuilderIO/qwik rep) in a ts file in your adapters folder (in your project directory). 
connect this function to your vite.config.ts from your adapters folder.
You comment the line that moves the dist folder.
But make sure to modify your `vite.config.ts` to put static files in the right folder 
```diff
- qwikVite()
+ qwikVite({
  client: {
    outDir: ".vercel/output/static"
  }
})
```

**Comment by gioboa** [comment]
Hi @danew, did you solve the problem with @Loshido solution?
