### ISSUE TITLE
[🐞] Context gets removed too eagerly

### ISSUE THREAD

**Issue by wmertens** [QwikDev/qwik#5411]
### Which component is affected?

Qwik Runtime

### Describe the bug

When an app doesn't use context during SSR but uses it after resume, the context is not available

### Reproduction

https://qwik.builder.io/playground/#v=1.2.17&f=Q0o0JhbG8IgCyiMSgA6QB6%2BBYRxQHQxioyVDqDSUj8qDpV0dLmicKaHHsRIXFyS8kksqgMGFnsSBFZadhlKykiZMWRCw7AUqw5ZUkbIP0DBNpCAHN2gyMiENGk1gyiUu7WPJg0CDdRSqgQaAQgvclAHXIraI0NKIjkW2GhL8IHvhcQZuTCHaENUQCzXAJukBy5jSVNtog1jNWjvnosTiDHjrC6q%2FGkmdHrDZAXUvMOWWA%2BNesxYa31AbwZ4dzaVDL5cCAA

### Steps to reproduce

Click the "crash" button. You'll see that the $context$ for the parent has not been filled in.

### System Info

```shell
see playground, it crashes in all versions of qwik (for 1.1.5 you'll have to switch to production build)
```

**Comment by wmertens** [comment]
Workaround: add a `useContext` after the provider

**Comment by PatrickJS** [comment]
is this still an issue in v2?

**Comment by devcaeg** [comment]
In `version 1.9.1` this problem continues.

**Comment by gioboa** [comment]
I did a double check with the latest v2 code and it's working fine in `dev` and `preview`.
v2 will be release soon so I marked this issue with `STATUS-3: solved by V2`, thanks.
