### ISSUE TITLE
[🐞] packaged types for qwik don't seem to be perfect

### ISSUE THREAD

**Issue by wmertens** [QwikDev/qwik#5421]
### Which component is affected?

Qwik Runtime

### Describe the bug

The npm package apparently has several issues with the types. See https://arethetypeswrong.github.io/?p=%40builder.io%2Fqwik%401.2.17

### Reproduction

N/a

### System Info

```shell
Any
```

**Comment by shairez** [comment]
@wmertens is this still the case or can be closed?

**Comment by PatrickJS** [comment]
yeah still an issue
https://arethetypeswrong.github.io/?p=%40builder.io%2Fqwik%401.5.5

**Comment by wmertens** [comment]
it's not perfect but it's plenty good now.
