### ISSUE TITLE
[🐞] `.env.local` is not loaded in production mode

### ISSUE THREAD

**Issue by genki** [QwikDev/qwik#5561]
### Which component is affected?

Qwik Runtime

### Describe the bug

I am using fastify adapter for production.
In dev or preview mode, the env vars in `.env` are correctly loaded.
But the production mode runs without the env vars in the `.env.local` file.

I have built the production image using docker like this:

```Dockerfile
FROM node:alpine AS base

RUN corepack enable
RUN mkdir /app
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
COPY server ./server
COPY dist ./dist
COPY .env .env.local
COPY node_modules ./node_modules

ENV NODE_ENV=production
EXPOSE 3000
ENTRYPOINT ["pnpm"]
CMD ["serve"]
```

If I manually provide the env vars as like as `ENV FOO=BAR` in the Dockerfile then the server can see it correctly.
Just the `.env.local` is ignored.

### Reproduction

https://github.com/genki/qwik-app/tree/prod_env

### Steps to reproduce

* git clone the repo above and prepare the docker environment.
* locate the qwik repo to `../clone/qwik` relatively from the app dir.
* And then type command in the app dir:
```
pnpm install
make image
make run
```
Open browser and see `http://localhost:3000` then you can see the problem like this:
<img width="395" alt="スクリーンショット 2023-12-12 4 57 03" src="https://github.com/BuilderIO/qwik/assets/4876/57bb641a-24b8-4213-8abf-d9a983f107a4">

And this is the expected result we can see in dev/preview mode.
<img width="413" alt="スクリーンショット 2023-12-12 4 55 42" src="https://github.com/BuilderIO/qwik/assets/4876/5383ca6b-82c0-4a68-8933-711dc8b9b31a">

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M2
    Memory: 62.33 MB / 24.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - /opt/homebrew/bin/npm
    pnpm: 8.8.0 - /opt/homebrew/bin/pnpm
    bun: 1.0.16 - ~/.bun/bin/bun
  Browsers:
    Chrome: 119.0.6045.199
    Safari: 17.1
  npmPackages:
    @builder.io/qwik: file:../clone/qwik/packages/qwik/dist => 1.2.19-dev20231205234031 
    @builder.io/qwik-city: file:../clone/qwik/packages/qwik-city/lib => 1.2.19-dev20231205234031 
    undici: ^5.28.2 => 5.28.2 
    vite: ^5.0.6 => 5.0.7
```

**Comment by carlostobon** [comment]
I found myself in that exact situation couple of weeks ago. Thing is it seems very few people deploy using docker and more specifically fastify. In dev mode use .env.local to place your envs and when production it works placing them in docker-compose.yml using enviroment:

They wont be .env vars exactly but shell vars. The question reminds unresolved, is it an issue  fastify, qwik or just the integration.

**Comment by gioboa** [comment]
Thanks @carlostobon is there an open issue on the fastify repo about .env.local issue?

**Comment by carlostobon** [comment]
I really don't know but it's worth checking.

**Comment by genki** [comment]
@carlostobon Thank you sharing your experience :)

**Comment by carlostobon** [comment]
🙏
