### ISSUE TITLE
[🐞] [Optimizer Error] RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds

### ISSUE THREAD

**Issue by yasserlens** [QwikDev/qwik#5565]
### Which component is affected?

Qwik Runtime

### Describe the bug

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at new NodeError (node:internal/errors:393:5)
    at boundsError (node:internal/buffer:84:11)
    at Buffer.readUInt16LE (node:internal/buffer:243:5)
    at Object.validate (/.../node_modules/@builder.io/qwik/optimizer.cjs:123:35)
    at finder (/.../node_modules/@builder.io/qwik/optimizer.cjs:2467:38)
    at Array.find (<anonymous>)
    at detector (/.../node_modules/@builder.io/qwik/optimizer.cjs:2468:17)
    at lookup (/.../node_modules/@builder.io/qwik/optimizer.cjs:2471:18)
    at getInfoForSrc (/.../node_modules/@builder.io/qwik/optimizer.cjs:2493:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'

### Reproduction

See this stackblitz
https://stackblitz.com/edit/qwik-starter-fqky5z?file=src%2Froot.tsx

### Steps to reproduce

Add a tag similar to the one below at root layout:
<script async type="text/javascript" dangerouslySetInnerHTML={`
			(function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function(){var o={ti:"12345678"};o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=="loaded"&&s!=="complete"||(f(),n.onload=n.onreadystatechange=null)},i=d.getElementsByTagName(t)[0],i.parentNode.insertBefore(n,i)})(window,document,"script","//bat.example.com/bat.js","uetq");
		`}></script>

### System Info

```shell
System:
    OS: macOS 13.2
    CPU: (12) x64 Apple M2 Pro
    Memory: 9.35 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - ~/.nvm/versions/node/v18.11.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.11.0/bin/npm
    pnpm: 7.9.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 120.0.6099.71
    Safari: 16.3
  npmPackages:
    @builder.io/partytown: ^0.8.0 => 0.8.1 
    @builder.io/qwik: ^1.2.13 => 1.2.18 
    @builder.io/qwik-city: ^1.2.13 => 1.2.18 
    undici: ^5.22.1 => 5.27.2 
    vite: ^4.4.0 => 4.5.0
```

### Additional Information

This isn't a critical bug as it only happens locally - since the optimizer only runs in Dev mode. But annoying since this appears on every single page load. especially if the script above was added at root.

**Comment by wmertens** [comment]
Interesting. Could you make a more specific test case, as short as possible?

Note that in the playground it doesn't seem to happen, so maybe there's an issue with the Rust build, or wasm is more forgiving:

https://qwik.builder.io/playground/#v=1.4.0&f=7VZNb8IwDP0rLAeUSFYYbGMfVS5ISEzauIydEBIdDRCEWmhSUNX2v89O22naYbcdJnFpY8VOXhL7PX9LmuHg8U%2BThvqHiakR2FVqDi0vUBIoRmnc24WnsJ5jqLbxRmOp2n3%2Bpt1zjPwymb2%2BqGLZ4e2b8jNE4CCFTBQnpJQ1xGCC8zxbKPqU5XwBa%2FXlXTslqnDmifUHN7d3w%2FsHVgWJPHp%2F8JGkHu%2FjGU%2BEt%2BUhs1vOqCshzmCiglhFsq6%2F8V77SnYCYmnTlUrx74%2Bl%2BjhK4j2GKBqge5T79me1pZP9RGWVQxqU3s2rUWC7XXulFKMldMQai%2B6Y9IeVJV9z2va3TUgWELBBwMjtDVo7ymfhZooKgbjn1wswEtUEJ6ZJpKVBOUndSGMjoDlep6gEP3uKgqghLmDNIwHr9T5CJxt5kAjO2zuLU5l2RyaCzrJq866OIqtuJy%2B88V954xM
