### ISSUE TITLE
[🐞] Type inference broken after upgrading to 1.3.1

### ISSUE THREAD

**Issue by blakeley** [QwikDev/qwik#5599]
### Which component is affected?

Qwik Runtime

### Describe the bug

The following code

```tsx
const Button = component$<PropsOf<"button">>((props) => (
  <button {...props}>
    <Slot />
  </button>
))

const Caller = component$(() => (
  <Button
    onClick$={(event) => {
      console.log(event)
    }}
  >
    Hello
  </Button>
))
```

results in `event` having an implicit `any` type, incorrectly.

### Reproduction

https://stackblitz.com/edit/qwik-starter-avfhkx?file=src%2Fcomponents%2Fstarter%2Fcounter%2Fcounter.tsx,package.json

### System Info

```shell
N/A
```

**Comment by wmertens** [comment]
I don't understand, it's working fine in the playground?

https://qwik.builder.io/playground/#v=1.3.1&f=Q0o0xgZYE40OqCQtKPZP01EAJWi8aQjiWSdwAwHoXYQhNlAzbJQgrQclOzsNDXADAhwioGCwgcgoVOvp6YFlaqGuBdsKdjK87cGlqUk4wYINhbgFbBC8nq7WSC0DqoPHBQggtxUgsmCJ2logBXEHOBbAjoCYCXbEaJIfekkeAA
