### ISSUE TITLE
Should useTask be executed first or RouteLoader be executed first

### ISSUE THREAD

**Issue by dph229563** [QwikDev/qwik#5604]
### Is your feature request related to a problem?

I use useTask to send asynchronous requests to retrieve data, and it uses the data obtained from RouteLoader as parameters. However, useTask does not always succeed, nor does it always fail. So would you like to confirm if useTask will be executed before RouteLoader?

### Describe the solution you'd like

I use useTask to send asynchronous requests to retrieve data, and it uses the data obtained from RouteLoader as parameters. However, useTask does not always succeed, nor does it always fail. So would you like to confirm if useTask will be executed before RouteLoader?

### Describe alternatives you've considered

I use useTask to send asynchronous requests to retrieve data, and it uses the data obtained from RouteLoader as parameters. However, useTask does not always succeed, nor does it always fail. So would you like to confirm if useTask will be executed before RouteLoader?

**Comment by gioboa** [comment]
Hi @dph229563, can you create a basic reproduction repo with [qwik.new](qwik.new) pls?

**Comment by dph229563** [comment]
Hi @gioboa https://stackblitz.com/edit/qwik-starter-xb6vkc?file=src%2Froutes%2Flayout.tsx
I created a demo

**Comment by gioboa** [comment]
Can I simulate the case with `pnpm preview`?

**Comment by PatrickJS** [comment]
this will be different in v2
