### ISSUE TITLE
[🐞]  Testing with vitest gives a  ReferenceError: document is not defined and  ReferenceError: window is not defined

### ISSUE THREAD

**Issue by bovandersteene** [QwikDev/qwik#5625]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

When creating tests with Vitest and configuring it with Qwik, a significant challenge arises when initiating DOM manipulations. Specifically, using functions like `useVisibleTask$` to manipulate elements on the window or document object results in a `ReferenceError: document is not defined`.

Upon conducting further research, I discovered that the tests are running in a node environment where the window or document object is absent. This absence appears to be a gap in the test setup.

I attempted to address this issue by adding JSDOM to the global context (globalThis), but encountered additional problems in the process. It's unclear whether there is a solution that I might have overlooked or if this is an aspect not yet implemented. It's crucial to find a resolution as testing this logic is an essential part of our requirements.

```
import { JSDOM } from 'jsdom';

const { window } = new JSDOM(); 
console.log(window.location);
globalThis.window = window;
globalThis.document = window.document;
```

Bellow the reproduction of the problem in a smaller piece of code.

**component**
```typescript
import { component$, useVisibleTask$ } from "@builder.io/qwik";

export const UseVisibleTaskComponent = component$(() => {
  useVisibleTask$(() => {
    console.log("the visible task");
    // This is failing
    // ReferenceError: window is not defined
    console.log(window.location.href);
    // ReferenceError: document is not defined
    console.log(document.activeElement?.id);
  });

  return (
    <div>
      I just do the is visible task and try to access the window object
      <div class="icon"> "⭐" </div>
    </div>
  );
});
```

**test**
```
import { createDOM } from "@builder.io/qwik/testing";
import { test, expect } from "vitest";
import { UseVisibleTaskComponent } from "./usevisibletask";

export const document: any = {};
test(`[UseVisibleTaskComponent]: Should render ⭐`, async () => {
  const { screen, render } = await createDOM();
  await render(<UseVisibleTaskComponent />);
  expect(screen.outerHTML).toContain("⭐");
});

```

### Reproduction

https://github.com/bovandersteene/qwik-vitest

### Steps to reproduce

this issue is reproduced in the following library: `https://github.com/bovandersteene/qwik-vitest`

command to run the tests:`npm run test.unit`

### System Info

```shell
System:
    OS: macOS 14.2
    CPU: (12) arm64 Apple M2 Max
    Memory: 3.34 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 17.2
  npmPackages:
    @builder.io/qwik: ^1.3.1 => 1.3.1 
    @builder.io/qwik-city: ^1.3.1 => 1.3.1 
    undici: ^5.26.0 => 5.28.2 
    vite: ^5.0.6 => 5.0.10
```

**Comment by gioboa** [comment]
@bovandersteene Did you solve this error?
