### ISSUE TITLE
[✨] Allow using GET with server$

### ISSUE THREAD

**Issue by manvalls** [QwikDev/qwik#5656]
### Is your feature request related to a problem?

POST requests are not easily cacheable

### Describe the solution you'd like

A way to tell server$ to use GET instead of POST

### Describe alternatives you've considered

Considered just using an endpoint, but I love the streaming functionality

**Comment by wmertens** [comment]
Typically I'd cache on the client side in this case.

Doing a GET implies putting the variables in the URL and listening for GET in the handler as well. That latter could be a little bit annoying but probably ok.

I suppose we could do it, what do you think @mhevery ?

**Comment by PatrickJS** [comment]
server$ needs a config for other features like changing origin, adding headers, query params etc

**Comment by wmertens** [comment]
@PatrickJS I propose a default config via the qwik city provider and then maybe the first argument. Right now that can optionally be an abort signal and we could also make it be an options object
