### ISSUE TITLE
[🐞] useLocation does not re-trigger useTask$() in static adapter output

### ISSUE THREAD

**Issue by mrclay** [QwikDev/qwik#5820]
### Which component is affected?

Qwik City (routing)

### Describe the bug

When trying to track location changes, the `useTask$` hook fails to re-fire the hook body if the project is built with the static adapter.

Example component code:
```ts
  const loc = useLocation();
  useTask$(({ track }) => {
    track(() => loc.url);
    console.log(1);
  });
```
In dev mode, this works, but after `npm run build` the code in `dist` does not re-call the useTask$ given function.

### Reproduction

https://stackblitz.com/edit/qwik-starter-oaexpi?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

```
npm ci
npm run build.client
npm run build.server
npx serve dist
```
View http://localhost:3000. When clicking the links, the state should update with the useLocation() value.

### System Info

```shell
  System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 77.03 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.1 - ~/.nvm/versions/node/v21.6.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.1/bin/npm
    pnpm: 8.5.0 - ~/Library/pnpm/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 121.0.6167.139
    Safari: 17.2.1
  npmPackages:
    @builder.io/qwik: ^1.4.3 => 1.4.3 
    @builder.io/qwik-city: ^1.4.3 => 1.4.3 
    undici: ^6.6.0 => 6.6.0 
    vite: ^5.0.12 => 5.0.12
```

**Comment by wmertens** [comment]
This definitely looks like a bug. I presume this does work with the node adapter?

**Comment by mrclay** [comment]
I've not tested the node adapter specifically. It works with `npm run dev`.

**Comment by gioboa** [comment]
@mrclay  Did you solve the problem?
