### ISSUE TITLE
Why are generic conditional types not working?

### ISSUE THREAD

**Issue by Nedimko123** [QwikDev/qwik#5832]
Let's say I have this:

```
type ABC<T extends 'string' | 'note'> = {
    id: string
    inputType: T
} & (T extends 'note' ? { customerUid: string } : { customerUid?: never })

function getField<T extends 'string' | 'note'>(props: ABC<T>) {}
```

Now when I call it:
```

// Valid usages
getField({ id: 'ID', inputType: 'string' })
getField({ id: 'ID', inputType: 'note', customerUid: 'customer123' })

// Error, customerUid is required for 'note'
getField({ id: 'ID', inputType: 'note' }) 
```

But if I do the same with the component$ from qwik:

```
const TestingComponent = component$(<T extends 'string' | 'note'>(props: ABC<T>) => {
    return <></>
})

```

It's not gonna worK:
```

export default component$(() => {
    return (
        <>
     <TestingComponent id="" inputType="note" /> // should error out but it does not
            <TestingComponent id="" inputType="note" customerUid={'123'} /> //valid
            <TestingComponent id="" inputType="string" /> // should not error out
                <TestingComponent id="" inputType="string" customerUid={'123'} />// this should error out but it does not
        </>
    )
})

```

**Comment by wmertens** [comment]
I'm not sure, it is working in the playground:

https://qwik.dev/playground/#f=7VZNi8IwFLznVzx62HTBw657WYqt%2BAne6w8QUiUgiq2etP%2FdeUm1aRVpjoLHtMlk5uVlJm7T%2FPT%2F%2FbpGCHN%2Bo%2FFkkMIhcIVUQdImvaQLyd3%2BmMkEwlmyVlH1CuABJzTf6YhSUdIXhQ6CWUZDZnFCLsM1l%2FVi0Imaf4YRDJ%2BtrPwW4n7asLK5zrbqJbWwesQYCQmagUoh9JrC9WpbZLY5kFdIOa1wC%2BE6Bb7coMOzESUXU9lzFd33AaEOsw2VXlOrvI1%2B%2B38GxxKZ5fk%2Bb0yFkaOZDiedI9aR3RVc530ZG5ptm6ackbtNHY%2Bx6wNelWw5RsJNxzI8bKZ9OR7YaRUHQS0pDphKgKbnUhV48SCykYYoCocQ3q3IPiQYMgUTfVGdmsdnycdS2p1MEHRHs5VrscQWNVN%2FrOfcAH%2FkZO1UicoU%2BIw%2BPv5%2BPn4F

all the error cases you mention have error lines
