### ISSUE TITLE
How should I combine useAuthSession with a simple axios wrapper?

### ISSUE THREAD

**Issue by MohammadMiras** [QwikDev/qwik#5902]
I want to get the JWT that is inside the session and add it to the headers of the requests that I send to the API, but I can't use useAuthSession in the Axios configuration file

```
axiosApi.interceptors.request.use(config => {
    config.headers["Accept"] = "application/json"
    config.headers["X-Client"] = "Qwik"
    return config
})
```
I get this error when I use `UseAuthSession` 

```
Error: Code(20): Calling a 'use*()' method outside 'component$(() => { HERE })' is not allowed. 'use*()' methods provide hooks to the 'component$' state and lifecycle, ie 'use' hooks can only be called synchronously within the 'component$' function or another 'use' method.
```
I understand the reason for this error, but is there any way I can get the session?

**Comment by gioboa** [comment]
Hi @MohammadMiras you can read the session [like this](https://qwik.dev/docs/integrations/authjs/#useauthsession) in your component and then you can use the signal to set the header.
This solves you problem so I'll close this, feel free to re-open it if it's still an issue for you.
