### ISSUE TITLE
[📖]  useVisibleTask 

### ISSUE THREAD

**Issue by b-rahmani** [QwikDev/qwik#5926]
### Suggestion

we use useVisibleTask to create an instance of swiper in qwik for use swiper but we have a warning in the console :
warning: useVisibleTask$() runs eagerly and blocks the main thread, preventing user interaction until the task is finished

we try to use other methods such as useOnDocument and useTask,... But none of them work. 
 also, I have the same issue with reading URL search params and using useVisibleTask

**Comment by wmertens** [comment]
They're warnings from eslint, you should have eslint support enabled in your editor so you see it as you write it.

You can disable the rule per line to indicate you understand the tradeoffs. 

BTW Qwik UI will have a carousel so you could just leave it for now and use that when it's released.

**Comment by thejackshelton** [comment]
> ### Suggestion
> we use useVisibleTask to create an instance of swiper in qwik for use swiper but we have a warning in the console : warning: useVisibleTask$() runs eagerly and blocks the main thread, preventing user interaction until the task is finished
> 
> we try to use other methods such as useOnDocument and useTask,... But none of them work. also, I have the same issue with reading URL search params and using useVisibleTask

@b-rahmani if you'd like to try out a native qwik solution, feel free to take a look at my fork. I have completely replaced swiper with it on a client site

https://github.com/thejackshelton/qwik-ui/tree/feat/carousel/packages/kit-headless/src/components/carousel
https://ramedia.us/about/
