### ISSUE TITLE
[🐞] Error on response attempting to close WritableStream with Bun adapter

### ISSUE THREAD

**Issue by octet-stream** [QwikDev/qwik#5929]
### Which component is affected?

Qwik City (routing)

### Describe the bug

When using Qwik with Bun adapter (Bun.serve) with disabled SSG, the server throws an error attempting to close locked `WritableStream`. From what I can tell, the stream becomes locked after the `pipeTo` call [here](https://github.com/BuilderIO/qwik/blob/420f382a87a9f28829c28a46fdefab0b9430f56e/packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts#L443) and it stays on that stage when `writebleStream.close()` is called [here](https://github.com/BuilderIO/qwik/blob/420f382a87a9f28829c28a46fdefab0b9430f56e/packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts#L476). The server itself however responds without any issue, this error for some reason just shows up in logs, but I get this during every server response response.

### Reproduction

https://github.com/octet-stream/qwik-bun-stream-issue

### Steps to reproduce

1. Clone this repository;
2. Install dependencies via `bun i`;
3. Build the project for production `bun run build`;
4. Start the app via `bun run serve`;
5. Open [http://localhost:3000](http://localhost:3000) in your browser;

After the main page shows up, look at the terminal and you'll see following error:

```
$ bun server/entry.bun.js
Server started: http://localhost:3000/
636 |     } finally {
637 |       await stream.ready;
638 |       await stream.close();
639 |       await pipe;
640 |     }
641 |     await writableStream.close();
                          ^
TypeError: WritableStream.close method can only be used on non locked WritableStream
      at writableStreamCloseForBindings (:1:21)
      at /Users/octetstream/projects/qwik-bun-stream-issue/server/entry.bun.js:641:11
```

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 62.06 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.2 - ~/Library/Caches/fnm_multishells/2006_1708258753953/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - ~/Library/Caches/fnm_multishells/2006_1708258753953/bin/npm
    pnpm: 8.15.4 - /opt/homebrew/bin/pnpm
    bun: 1.0.29 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 122.0.6261.94
    Safari: 17.3.1
  npmPackages:
    @builder.io/qwik: ^1.4.5 => 1.4.5 
    @builder.io/qwik-city: ^1.4.5 => 1.4.5 
    undici: * => 6.6.2 
    vite: ^5.0.12 => 5.1.4
```

**Comment by devcaeg** [comment]
@wmertens Do you know if this error is caused by Bun or by Qwik?

**Comment by devcaeg** [comment]
The error occurs in this line of code.

https://github.com/QwikDev/qwik/blob/7627cf5438e4c13404abe3f3af1f52fbde3eb997/packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts#L483C5-L483C34

For some reason, at that line, "writableStream" is in "locked" state, and therefore cannot be closed.

**Comment by octet-stream** [comment]
> Do you know if this error is caused by Bun or by Qwik?

I'm not sure, but I tried Qwik with Node.js servers and I don't get this error, so it might be.

**Comment by octet-stream** [comment]
Also, for some reason this error is cached somewhere (I don't remember where exactly) and then just logged to console.

**Comment by wmertens** [comment]
Well, open for PRs :)

**Comment by devcaeg** [comment]
If before executing `await writableStream.close();` it is verified that it is not in `locked` state, the error would be avoided. But I am not sure if this could cause other errors.

```ts
if (!writableStream.locked) {
    await writableStream.close();
}
```

**Comment by PatrickJS** [comment]
well if lock is true then it will throw an error correct? unless this error will only throw in bun

**Comment by devcaeg** [comment]
Yes, if `locked` is `true`, then an error will occur when trying to execute `close()`.

**Comment by PatrickJS** [comment]
what about
```js
if (writableStream.locked) {
    writableStream.releaseLock();
}
await writableStream.close();
```

**Comment by PatrickJS** [comment]
ChatGPT 😏 suggested this after I asked it to account for every gotcha haha
```tsx
export function renderQwikMiddleware(render: Render) {
  return async (requestEv: RequestEvent) => {
    // Your existing code...

    if (requestEv.headersSent) {
      return;
    }
    const isPageDataReq = requestEv.sharedMap.has(IsQData);
    if (isPageDataReq) {
      return;
    }
    const requestHeaders: Record<string, string> = {};
    requestEv.request.headers.forEach((value, key) => (requestHeaders[key] = value));

    const responseHeaders = requestEv.headers;
    if (!responseHeaders.has('Content-Type')) {
      responseHeaders.set('Content-Type', 'text/html; charset=utf-8');
    }

    const trailingSlash = getRequestTrailingSlash(requestEv);
    const { readable, writable } = new TextEncoderStream();
    const writableStream = requestEv.getWritableStream();
    const pipe = readable.pipeTo(writableStream, { preventClose: true });
    const stream = writable.getWriter();
    const status = requestEv.status();
    try {
      // Your rendering logic...

      if (typeof (result as any as RenderToStringResult).html === 'string') {
        await stream.write((result as any as RenderToStringResult).html);
      }
      requestEv.sharedMap.set('qData', qData);
    } finally {
      try {
        await stream.ready;
        await stream.close();
        console.log('Writer closed successfully');
      } catch (error) {
        console.error('Error closing the writer', error);
      }

      try {
        await pipe;
        console.log('pipe operation completed successfully');
      } catch (error) {
        console.error('Error in pipe operation', error);
        if (writableStream.abort) {
          writableStream.abort(error);
        }        
      }

      if (!writableStream.locked) {
        try {
          await writableStream.close();
          console.log('Stream closed successfully');
        } catch (error) {
          console.error('Error occurred when closing the writable stream', error);
        }
      } else {
        console.error('The writable stream is locked.');
        // Wait 2 seconds
        const waitTime = 2000l
        await new Promise(resolve => setTimeout(resolve, waitTime));

        if (writableStream.locked) {
          try {
            stream.releaseLock();
            console.log('The writer has been released, trying to close the stream again');
            await writableStream.close();
          } catch (error) {
            console.error('Error occurred when forcibly trying to close the writable stream', error);
          }
        }
      }
    }
  };
}

```

**Comment by devcaeg** [comment]
In this `WritableStream` does not have the `relaseLock()` function.

```ts
WritableStream {
  locked: true,
  abort: [Function: abort],
  close: [Function: close],
  getWriter: [Function: getWriter],
}
```

**Comment by PatrickJS** [comment]
maybe type os outdated?
https://nodejs.org/api/webstreams.html#readablestreamdefaultreaderreleaselock
https://developer.mozilla.org/en-US/docs/Web/API/WritableStreamDefaultWriter/releaseLock

**Comment by PatrickJS** [comment]
even if we do this it's weird that it's only bun. maybe something else is wrong. we have another team using bun with no issues

**Comment by devcaeg** [comment]
It does not seem to be a type problem, since I try to execute `releaseLock` (both in `writableStream` and `stream`) and I get the error that this function does not exist.

**Comment by devcaeg** [comment]
Maybe I'm wrong, but I think they are different.

https://developer.mozilla.org/en-US/docs/Web/API/WritableStreamDefaultWriter

https://developer.mozilla.org/en-US/docs/Web/API/WritableStream

**Comment by devcaeg** [comment]
> oh i see ChatGPT got releaseLock from `stream` when you getWriter()
> 
> ```js
>             writableStream.getWriter().releaseLock();
>             console.log('The writer has been released, trying to close the stream again');
>             await writableStream.close();
> ```

The problem is when trying to execute `getWriter()` when `locked` is `true`, this causes an error.

**Comment by octet-stream** [comment]
> even if we do this it's weird that it's only bun. maybe something else is wrong. we have another team using bun with no issues

Do they use Bun.serve as production server with Qwik? With which version of Bun and Qwik?

**Comment by PatrickJS** [comment]
@devcaeg you can access the reference with `stream.releaseLock();`

**Comment by devcaeg** [comment]
> @devcaeg you can access the reference with `stream.releaseLock();`

Are you using `Node` or `Bun`? Because maybe Bun for some reason does not incorporate `releaseLock`.

**Comment by PatrickJS** [comment]
I'm going to download the repro and try it

**Comment by PatrickJS** [comment]
yeah it looks like bun doesn't have releaseLock

**Comment by octet-stream** [comment]
I see this method on WritableStream on v1.1.8

<img width="598" alt="image" src="https://github.com/QwikDev/qwik/assets/7884558/d0d63321-314a-42f1-abbc-545ca275dc0f">

**Comment by PatrickJS** [comment]
I tried 1.1.8 not working. maybe we need to ping bun guys

**Comment by devcaeg** [comment]
I wrote in `Bun` discord and `Jarred` replied the following:

`releaseLock` is a property of `ReadableStreamDefaultReader`, not on `WritableStream` afaik

**Comment by PatrickJS** [comment]
makes sense

**Comment by octet-stream** [comment]
Yes, I see this error on 1.1.8 too. Thing is, unlike Node.js, Bun does not have TextEncoderStream, and Qwik polyfills it. I am trying to figure out if that's where the problem occurs.

**Comment by PatrickJS** [comment]
oh lets just ask bun to add TextEncoderStream

**Comment by devcaeg** [comment]
https://bun.sh/docs/runtime/nodejs-apis#textencoderstream 😅

**Comment by octet-stream** [comment]
Let's figure out if the issue occurs because of this polyfill first :)

**Comment by octet-stream** [comment]
Here's the polyfill: https://github.com/QwikDev/qwik/blob/bb8b7a94ccb81b2543ace194c823219a67e6891d/packages/qwik-city/middleware/bun/index.ts#L21-L53

I see from the usage of it that it should return a value, which this polyfill is not doing.

**Comment by PatrickJS** [comment]
yeah I asked chatgpt to give me a better polyfil and it works

**Comment by PatrickJS** [comment]
the chatgpt version was
```js
var TextEncoderStream = class {
  constructor() {
    this._encoder = new TextEncoder();
    this._writer = null;
    this.ready = Promise.resolve();
    this.reader = null;
    this.closed = false;

    this.readable = new ReadableStream({
      start: controller => {
        this.reader = controller;
      }
    });

    this.writable = new WritableStream({
      write: async (chunk) => {
        if (chunk != null && this.reader) {
          let encoded = this._encoder.encode(chunk);
          this.reader.enqueue(encoded);
        }
      },
      close: () => {
        this.reader.close();
        this.closed = true;
      },
      abort: (reason) => {
        this.reader.error(reason);
        this.closed = true;
      }
    });
  }
};
```

**Comment by octet-stream** [comment]
Yes, it seem to work.

**Comment by PatrickJS** [comment]
@octet-stream can you make a pr (you can edit in github directly) and I'll update the pr if needed

**Comment by octet-stream** [comment]
Sure, why not.

**Comment by devcaeg** [comment]
Great! I didn't realize that `Qwik` had this polyfill to make `Bun` work.

**Comment by PatrickJS** [comment]
yup i didn't realize either

**Comment by octet-stream** [comment]
I actually did, when I was investigating this problem back March, but I completely forgot to mention it in this issue, sorry.

**Comment by PatrickJS** [comment]
here is a pr example https://github.com/QwikDev/qwik/pull/6308

I want you to make a pr so you guys get contributes 😁

**Comment by octet-stream** [comment]
Here comes the PR :)

**Comment by devcaeg** [comment]
I am satisfied with the simple fact that the error is solved, haha.  Thank you both very much.

**Comment by PatrickJS** [comment]
@devcaeg @octet-stream 
we want to get a few more features in before the next release. so what you can do is add the polyfill yourself before `createQwikCity` runs and you should be good to go

**Comment by octet-stream** [comment]
You mean the polyfill will be exposed from Qwik to be installed manually?

**Comment by PatrickJS** [comment]
no I meant for now until the next release. in your codebase look where `createQwikCity` is ran then above the file define TextEncoderStream globally on globalThis.TextEncoderStream if it's not defined

**Comment by octet-stream** [comment]
Ah, sure.

**Comment by PatrickJS** [comment]
yeah, that way you guys aren't blocked and waiting for the next release 👍

**Comment by devcaeg** [comment]
Thank you!

**Comment by octet-stream** [comment]
By the way, here's the issue in Bun asking for TextEncoderStrea/TextDecorerStream https://github.com/oven-sh/bun/issues/5648 I'll comment it here to add a reference. There's even a polyfill: https://github.com/oven-sh/bun/issues/5648#issuecomment-1824093837

**Comment by PatrickJS** [comment]
oh awesome they had a polyfill

**Comment by PatrickJS** [comment]
ok ChatGPT make the encoder version based on the code in that bun issue decoder version
```js
export class PolyfillTextEncoderStream extends TransformStream<string, Uint8Array> {
  constructor() {
    const encoder = new TextEncoder();
    super({
      transform(chunk: string, controller: TransformStreamDefaultController<Uint8Array>) {
        const encoded = encoder.encode(chunk);
        if (encoded.byteLength > 0) {
          controller.enqueue(encoded);
        }
      },
      flush(controller: TransformStreamDefaultController<Uint8Array>) {
        // When the stream is finished, we don't have any cleanup to do.
        // We don't need to enqueue any data because TextEncoder.encode doesn't have any state.
      }
    });
  }
}
```

**Comment by devcaeg** [comment]
I think the latter is better. Anyway, the best thing is for `Bun` to add compatibility, hopefully it won't take too long.

**Comment by devcaeg** [comment]
In the latest versions of `Bun`, `TextEncoderStream` and `TextDecoderStream` compatibility has been added, so this polyfill is no longer necessary.

**Comment by gioboa** [comment]
Thanks for the update
