### ISSUE TITLE
[🐞] <Resource> passed as prop does not render in correct position

### ISSUE THREAD

**Issue by EatChangmyeong** [QwikDev/qwik#5940]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

I was trying to pass some JSX as a prop when I encountered this bug (I couldn't use `<Slot />` because I needed to inspect the passed JSX).

If I understand correctly, any value passed as a prop should be serializable, and JSX (more specifically the `type JSXOutput = JSXNode | string | number | boolean | null | undefined | JSXOutput[];`) *is* serializable:
* [`_verifySerializable`](https://github.com/BuilderIO/qwik/blob/1995753ff587d9938dcc08515ca64693a805d14f/packages/qwik/src/core/state/common.ts#L38) explicitly lists nullish values (`null` and `undefined`), (contiguous) arrays, booleans, strings and numbers
* the [`serializers`](https://github.com/BuilderIO/qwik/blob/1995753ff587d9938dcc08515ca64693a805d14f/packages/qwik/src/core/container/serializers.ts#L533) array includes `JSXNodeSerializer` that takes care of remaining `JSXNode`s

In the following reproduction, the app component takes two copies of JSX `<Inner />` that has a `<Resource>` call inside, and passes them to `Outer`, one as a slotted child and the other as the `content` prop. `Outer` tries to render each JSX in a `<div>`.

**Expected behavior**: in the HTML tab, each JSX should be rendered in its respective `<div>`.
**Actual behavior**: the `content` JSX is rendered *outside of* its `<div>`.

This bug only happens in server-side rendering; both JSX renders correctly if I insert a `useVisibleTask$` to force client-side rendering.

Please feel free to close this issue if my understanding is wrong or I made a mistake somewhere else.

### Reproduction

https://qwik.dev/examples/introduction/hello-world/#f=7VY7DsIwDJ3ts0SNEJ1Q0h0WBhYOwFwWKlWKcneeP6TNzITE1vpb2%2B%2B53oFmHI9tUEw6mcvtfl1ewG5g2gAROqRCJUAP6KtJ%2BAuUMSUk1EWijMwlnWdZLHGqUFJ7g2FUy4lRCFuXzTV3Uf1KQUUe8rSvqupA0H%2FSMydJJYhux44Li4YY3L26Dk3cEttX9Yl91JIWFtji0HcMN4sDotCHV62FRFgvC%2B4Q%2BA36WCF7zmKAn8Ejl1WcV0jjn30%2Fy743

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 1.16 GB / 7.86 GB
  npmPackages:
    @builder.io/qwik: ^1.4.5 => 1.4.5
    @builder.io/qwik-city: ^1.4.5 => 1.4.5
    undici: * => 6.6.2
    vite: ^5.0.12 => 5.1.4
```

**Comment by wmertens** [comment]
Thank you for the clear repro, that's definitely a bug.

**Comment by wmertens** [comment]
This is fixed in v2: https://qwikdev-build-v2.qwik-8nx.pages.dev/playground/#f=7VY7DsIwDJ3ts0SNEJ1Q0h0WBhYOwFwWKlWKcneeP6TNzITE1vpb2%2B%2B53oFmHI9tUEw6mcvtfl1ewG5g2gAROqRCJUAP6KtJ%2BAuUMSUk1EWijMwlnWdZLHGqUFJ7g2FUy4lRCFuXzTV3Uf1KQUUe8rSvqupA0H%2FSMydJJYjuh5AJi4YY3L26Dk3cEttX9Yl91JIWFtji0HcMN4sDotCHV62FRFgvC%2B4Q%2BA36WCF7zmKAn8Ejl1WcV0jjn30%2Fy743
