### ISSUE TITLE
[🐞] SPA resume (probably) needs to be fixed for upcoming v2 changes

### ISSUE THREAD

**Issue by jordanw66** [QwikDev/qwik#5983]
### Which component is affected?

Qwik City (routing)

### Describe the bug

# Explanation
SPA resume (popstate after refresh/reload) needed to exist outside of Qwik in order to keep it simple and not pull in anything that is not already being used on a page.

For this reason, when a popstate occurs on a page where SPA context was lost, it only directs the page back into the `useNavigate` pipeline when an already-existing `useNavigate` context exists on the page, and falls back to `location.href` refreshing.

This functionality solves all cases:
- No SPA-related code loaded on MPA-only pages.
- Pages with `useNavigate` ctx will be restored into the SPA pipeline.
- Edgecase of "leaf node" which is arrived at via Link/`useNavigate`, but does not contain either, and a refresh occurs. It isn't possible to differentiate this page from a purely MPA during SSR, no `useNavigate` ctx can be included.

# Problem
The simple and quick way of hooking back into the `useNavigate` ctx was to:
- Check the page for a `Link`, specifically an `a` element with the attribute `q:key="AD_1"`.
- This elm then gets duplicated in a way that is invisible, and a new attribute `q:nbs` (**N**av **B**oot**S**trap) would be attached.
- This attr tells the Link component to ignore the `href` attr and instead call: `nav(location.href, { type: 'popstate' })`
- The modified Link elm gets `click()` and is pushed through the loader normally, resuming the app, everything just works.

This was simple even though it only works if the official Link component is present, and I didn't understand internals enough to decipher and jiu-jitsu a hand-crafted way to directly detect and hook any case of `useNavigate` ctx on the page from the `qwik/json` in the time available. (that would've needed adapting to v2 as well)

With the upcoming Qwik v2 changes as they appear in this blog post: https://www.builder.io/blog/qwik-2-coming-soon. It appears the current method of detecting a Link described above ***might*** not work anymore. Specifically because it relies on a `q:key` attribute on the `a` element. Can someone confirm this?

# Solution(s)
If this does turn out to be an issue, some possible solutions:
- ***Simplest***: add new attr to the `Link` component's `a` element with a magic string and use that to select a Link on the page.
- ***Harder/Ideal***: Jiu-jitsu a way to detect any case of `useNavigate`, even with just `nav()` or custom Links, and somehow hook into this directly. This would remove dependence on the official `Link` component.

Unfortunately I do not currently have the time it would require to setup a dev environment on v2 and investigate and adjust this behavior. Hopefully the few minutes it took to explain this issue in detail is helpful to someone in solving this.

For reference, here are the current parts of the code that are described above:

https://github.com/BuilderIO/qwik/blob/157f7b01df22448638f7cc55546a051aa4eea5f0/packages/qwik-city/runtime/src/spa-init.ts#L74-L78

https://github.com/BuilderIO/qwik/blob/157f7b01df22448638f7cc55546a051aa4eea5f0/packages/qwik-city/runtime/src/link-component.tsx#L70-L72

### Reproduction

N/A

### System Info

```shell
N/A
```

**Comment by wmertens** [comment]
Thanks Jordan! Question: how about always including the spa context, would that also solve it? Is it that huge?

**Comment by wmertens** [comment]
Hmm I'm afraid I don't understand. Apart from the contexts' data that Link uses,  what needs to be shipped to the client to enable SPA?

**Comment by PatrickJS** [comment]
partially fixed https://github.com/QwikDev/qwik/pull/6022
