### ISSUE TITLE
[🐞]icons not working in production  or in preview mode

### ISSUE THREAD

**Issue by Web2Integrators** [QwikDev/qwik#6000]
### Which component is affected?

Qwik Runtime

### Describe the bug

  <HiBars3Solid class="text-3xl" /> this works in dev mode but not in production or preview mode

### Reproduction

https://github.com/Web2Integrators/bug-icons

### Steps to reproduce

clone above repo

npm i
npm run dev will work.
npm run preview will not work.

### System Info

```shell
n/a
```

**Comment by Priyang1310** [comment]
fixes #6000

**Comment by gioboa** [comment]
> fixes #6000

Is it solved?

**Comment by Web2Integrators** [comment]
Yes.
Its resolved .I guess after the release of 1.5.*.



From: Giorgio Boa ***@***.***>
Date: Monday, June 17, 2024 at 3:22 PM
To: QwikDev/qwik ***@***.***>
Cc: Jay ***@***.***>, Author ***@***.***>
Subject: Re: [QwikDev/qwik] [🐞]icons not working in production or in preview mode (Issue #6000)

fixes #6000<https://github.com/QwikDev/qwik/issues/6000>

Is it solved?
