### ISSUE TITLE
[🐞] Qwik Insights returns 500 error for fetching data/strategy

### ISSUE THREAD

**Issue by intellix** [QwikDev/qwik#6012]
### Which component is affected?

Qwik Insights

### Describe the bug

During the build process, I'm seeing a warning message that insight data failed to load. When I run a cURL locally to fetch the insights, it just responds with a 500 error. I've got quite a few insight projects (created some new ones for other sites we're working on) and they all return a 500 error.

I've tried multiple projects (one that was collecting data for some time) and even brand newly created insight projects

For example, this returns a 500:
```
curl -X GET https://qwik-insights.builder.io/api/v1/i7ad7k2w80/bundles/strategy/
```

### Steps to reproduce

```
curl -X GET https://qwik-insights.builder.io/api/v1/i7ad7k2w80/bundles/strategy/
```

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 343.95 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.volta/tools/image/node/20.11.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.19.4 - ~/.volta/tools/image/npm/8.19.4/bin/npm
    pnpm: 8.15.3 - ~/.volta/tools/image/pnpm/8.15.3/bin/pnpm
  Browsers:
    Chrome: 122.0.6261.129
    Edge: 122.0.2365.80
    Safari: 17.3.1
  npmPackages:
    @builder.io/partytown: ^0.10.0 => 0.10.0 
    @builder.io/qwik: workspace:^ => 1.5.1 
    undici: * => 6.6.2 
    vite: ^5.1.4 => 5.1.4
```

**Comment by wmertens** [comment]
@mhevery could you take a look?

**Comment by gioboa** [comment]
I tested and it's working fine now.
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
