### ISSUE TITLE
[🐞] Missing "export" in some types

### ISSUE THREAD

**Issue by devcaeg** [QwikDev/qwik#6049]
### Which component is affected?

Qwik Runtime

### Describe the bug

Every time I reinstall qwik I have to go to the file `core.d.ts` and add an `export` to the line `declare interface SyncQRL`, I also have to add an `export` to the line `declare interface QRLDev`.
I also have to go to the `package.json` file and in the `exports` list in the `./build` I have to add `"types": "./build/index.d.ts"`

If I don't do this, TypeScript errors occur in my project. For example, if I try to use `isBrowser` or `isServer` I get the following error `Could not find a declaration file for module '@builder.io/qwik/build'`.

It should be noted that I use `Bun` as a package installer.

### Reproduction

no-link

### System Info

```shell
System:
    OS: macOS 14.4
    CPU: (8) arm64 Apple M2
    Memory: 60.92 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.1 - ~/.nvm/versions/node/v21.7.1/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v21.7.1/bin/npm
    pnpm: 8.15.5 - /opt/homebrew/bin/pnpm
    bun: 1.0.35 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 123.0.6312.58
    Edge: 123.0.2420.53
    Safari: 17.4
  npmPackages:
    @builder.io/qwik: 1.5.1 => 1.5.1 
    @builder.io/qwik-city: 1.5.1 => 1.5.1 
    undici: 6.10.1 => 6.10.1 
    vite: 5.2.6 => 5.2.6
```

**Comment by wmertens** [comment]
fix is on , thanks for reporting.
