### ISSUE TITLE
[🐞] The CJS build of Vite's Node API is deprecated

### ISSUE THREAD

**Issue by auditmn** [QwikDev/qwik#6057]
### Which component is affected?

Qwik Runtime

### Describe the bug

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

### Reproduction

https://github.com/vitejs/vite/discussions/13928

### Steps to reproduce

Run any npm command like:

- npm start; or
- npm build

### System Info

```shell
Windows 11, VS Code Integrated Terminal
```

### Additional Information

Can be resolved just by changing the naming of vite.config.ts to vite.config.mts, whereas nothing has to be changed on the code

**Comment by PatrickJS** [comment]
qwik is in the list. if you have "type": "module" in your package.json it's esm
