### ISSUE TITLE
[🐞] Bun adapter breaks / hangs build

### ISSUE THREAD

**Issue by Twiggeh** [QwikDev/qwik#6058]
### Which component is affected?

Starters / CLI

### Describe the bug

I am running the cli to add bun, but when I try to build and run the server it breaks / hangs on the build.

This happens because TS errors on the `entry.bun.ts` file, since `Bun` is not defined there. 
The bun docs are also lacking one property that needs to be added in the `tsconfig.json`, `bun-types` inside 
```json
"compilerOptions" : { "types": ["node", "vite/client", "bun-types"]  }
```

I would like to make a PR for this issue.

### Reproduction

https://github.com/Twiggeh/qwik-report

### Steps to reproduce

`nix develop`
`bun run install`
`bun run build` // crashes / hangs => ctrl + c 
`bun run serve` // 404 index.html missing

### System Info

```shell
System:
    OS: Linux 6.6 NixOS 24.05 (Uakari) 24.05 (Uakari)
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Memory: 17.73 GB / 30.78 GB
    Container: Yes
    Shell: 5.2.26 - /run/current-system/sw/bin/bash
  Binaries:
    Node: 20.11.1 - /run/current-system/sw/bin/node
    npm: 10.2.4 - /run/current-system/sw/bin/npm
    bun: 1.0.29 - /nix/store/jk432rp4sfm9y912yy071cxdx30bbhvm-bun-1.0.29/bin/bun
  Browsers:
    Brave Browser: 122.1.63.162
  npmPackages:
    @builder.io/qwik: ^1.5.1 => 1.5.1 
    @builder.io/qwik-city: ^1.5.1 => 1.5.1 
    undici: * => 6.10.2 
    vite: ^5.1.4 => 5.2.6
```

**Comment by gioboa** [comment]
I tested and it's working fine with the latest version.
This PR https://github.com/QwikDev/qwik/pull/6185 solved the issue I think.
Feel free to re-open it if it's still an issue for you.
