### ISSUE TITLE
[📖]Could add a demo like "Learn Next.js"?

### ISSUE THREAD

**Issue by zwl1619** [QwikDev/qwik#6075]
### Suggestion

Could add a demo like "Learn Next.js"?
https://nextjs.org/learn

**Comment by notcod** [comment]
Somebody started, not sure who @ https://www.learn-qwik.com/

**Comment by gioboa** [comment]
Nice @notcod , I think we can close this.
@zwl1619 feel free to reopen it if it's still an issue for you. Thanks
