### ISSUE TITLE
[🐞] View transition and scroll restore conflicts

### ISSUE THREAD

**Issue by jordanw66** [QwikDev/qwik#6076]
### Which component is affected?

Qwik Runtime

### Describe the bug

Not sure what the issue is yet but it's alluded to in this issue (my comment): https://github.com/BuilderIO/qwik/pull/6068#issuecomment-2028448433

Essentially, every SPA navigate in Qwik City automatically invokes a view transition (it's enabled by default) unless the QwikCity component's `viewTransition` prop is explicitly set to `false`. However, view transitions are effectively disabled by some CSS Manu originally added. When that CSS was removed, the scroll restore tests failed, suggesting that even Chrome's basic view transition effect somehow clashes with scroll restore.

I think it might be some kind of race condition as mentioned here: https://stackoverflow.com/a/76973540

Which would make this an issue in Qwik core, relevant code might be here: https://github.com/BuilderIO/qwik/blob/fd2ccbd641c12afce90ec45696c9d598cd4a34d7/packages/qwik/src/core/render/dom/visitor.ts#L1173-L1179

I don't think this is a large issue and probably easy to fix, if nobody gets to it I will eventually when I have time to investigate. Opening this issue so it's not forgotten.

### Reproduction

N/A

### System Info

```shell
N/A
```

**Comment by gioboa** [comment]
Thanks @jordanw66  Can you create a basic reproduction pls?
