### ISSUE TITLE
[✨] Improve playground or sandbox

### ISSUE THREAD

**Issue by RaiVaibhav** [QwikDev/qwik#6081]
### Is your feature request related to a problem?

While relying on playground to understand qwik step by step, a lot of time I rely on the output section of playground or sandbox, mostly `html` and `symbols`

For in tutorial if I visit the `optmizer` section then most of the time it was instructed to look at the `symbols`, these are important for me to understand `qwik` behind the hood.

### Describe the solution you'd like

**Proposal**

- In output section of playground, as per the code-block in view, show the selected path on the left side i.e., using scroll to view and setting the path as a selected and changing the text color ?
- In output section of playground, we should have an option to copy the code from the code-block?
- Layout should be resizable?
- On mobile screen, if user click on path, then the code block should open in something like drawer (I am not sure this is needed right now because most of the people don't code on mobile :P) ?

### Describe alternatives you've considered

NA

### Additional context

The first point I have mentioned here in [discord](https://discord.com/channels/842438759945601056/842438761287254019/1223977671512555520), rest is easily reproducible.

Also I am not good in UX and UI, but for me using the output section is like using the devtools to understand the qwik.

**Comment by RaiVaibhav** [comment]
I am looking forwards to the response and I would be highly interested in working on problems.

**Comment by wmertens** [comment]
PRs always welcome 🤗 I love the playground too and I do use it on mobile a lot.

Happy to explain things that aren't clear

**Comment by RaiVaibhav** [comment]
Great, will start working on this 👍
