### ISSUE TITLE
SCOPED SLOTS[✨]

### ISSUE THREAD

**Issue by jermsam** [QwikDev/qwik#6097]
### Is your feature request related to a problem?

There is currently no way to pass down component state to it's  children through slots. For instance, If you have a data table and you want the ability to provide slots for the table's cell content, there is hardly a way to do so with the current API using Slot.

### Describe the solution you'd like

Proposed api:

```ts
<Slot name={'cell'} props={cellData}/> 
```
just like In vue:

```ts
<slot v-bind:cell="cellData"/>
```
And that would allow us to use slots like:

```ts
<div q:slot={'cell'} q:prop={cellData}> // proposed api
{cellData.label}
</div>
 ```
Just as in vue:

```ts
<template #cell={props}>
<div>
{{props.cellData.label}}
</div>
<template>
```

### Describe alternatives you've considered

Render Functions with Props:
```ts
import {$, component$, JSXChildren, QRL, useSignal} from '@builder.io/qwik';

export interface CellData {
  label?: string
}
export interface Props {
  renderCell$: QRL<(cellData: CellData)=>void>
}

const CustomComponent = component$<Props>((props) => {
const cellData = useSignal<CellData>({label: 'Hi What!!!'})

  const renderFn = $(async ()=>{
    if(!props.renderCell$)  return null
    return await props.renderCell$(cellData.value)
  })

  return (
    <div>
      <div>Cell Title: </div>
      {renderFn() as JSXChildren}
    </div>
  );
});

export default CustomComponent;
```
so then:

```ts

const MyCustomCellComponent = component$(() => {

  return <CustomComponent
        renderCell$={(cellData) => (
          <div>{ cellData.label }</div>
        )}
      />
});
```
and

```ts

const TheirCustomCellComponent = component$((props: any) => {

  return <CustomComponent
        renderCell$={(cellData) => (
          <button>{ cellData.label }</button>
        )}
      />
});

```

Look at all this JS for a basic feature .

**Comment by wmertens** [comment]
I'm sorry, I don't understand how the props would be used. A slot is a virtual placeholder, it gets replaced by the child for the slot.

**Comment by jermsam** [comment]
@wmertens with the proposed API: We will be able to define CustomComponents like:
```ts
const CustomComponent = component$(() => {
const cellData = useSignal({label: 'Hi What!!!'})
 return (
    <div>
      <div>Cell Title: </div>
      <Slot name={'cell'} :cell-data={cellData.value}/>
    </div>
  );
})
```
and use it like:
```ts
const MyCustomCellComponent = component$(() => {

  return <CustomComponent q:slot={'cell'} q:prop={cellData}>
   <div>{ cellData.label }</div>
  </CustomComponent>
});
```
and
```ts
const TheirCustomCellComponent = component$(() => {

  return <CustomComponent q:slot={'cell'} q:prop={cellData}>
   <button>{ cellData.label }</button>
  </CustomComponent>
});
```

**Comment by jermsam** [comment]
@wmertens . Here is where the idea is coming from.
https://vuejs.org/guide/components/slots.html#scoped-slots

**Comment by wmertens** [comment]
Yeah I don't think this matches the Qwik architecture well. Is it so bad to use render functions instead, combined with context?

Remember that slots will use the context from the slot parent, which is deeper than the real parent.
So if you have a context `cellDataCtx`, you can read from it in the slotted cell component.

**Comment by gioboa** [comment]
Thanks @jermsam and @wmertens for this interesting discussion.
The issue is stale and I think our [Discord server](https://qwik.dev/chat) is perfect for this kind of discussions. :+1:
