### ISSUE TITLE
[🐞] Extremely unpleasant jumps and flashes for a simple HTML input

### ISSUE THREAD

**Issue by Nefcanto** [QwikDev/qwik#6106]
### Which component is affected?

Qwik Runtime

### Describe the bug

I was creating a login form with Qwik. I had to do some validation. I ended up with a very jumpy and flashy field that was not responsive to some characters. This is how it looks:

[Video](https://github.com/BuilderIO/qwik/assets/12782347/ceb1079f-957f-4e97-a059-27664fc48b03)

### Reproduction

https://stackblitz.com/edit/qwik-starter-wtnwdb?file=src%2Froutes%2Findex.tsx,src%2Froutes%2Flayout.tsx

### Steps to reproduce

1- Create a Qwik project
2- Paste this code:

```
  const phone = useSignal('');
  const isPhoneEmpty = useComputed$(() => phone.value?.trim() === '');
  const isPhoneInvalid = useSignal(
    () => phone.value?.trim() !== '' && phone.value.length != 11
  );
  return (
    <>
      <input
        value={phone.value}
        onKeyDown$={(e) => (phone.value = e.target.value)}
      />
      {isPhoneEmpty && <div>Phone can not be mepty</div>}
      {isPhoneInvalid && <div>Phone is invalid</div>}
    </>
  );
```

3- Test it with writing fast in it

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    @builder.io/qwik: ^1.4.3 => 1.4.3 
    @builder.io/qwik-city: ^1.4.3 => 1.4.3 
    undici: 5.28.2 => 5.28.2 
    vite: 4.5.2 => 4.5.2
```

**Comment by wmertens** [comment]
- you're using useSignal the second time when you should use useComputed$
- you should use the onInput$ event. This may be why it is jumpy.
- you should test the boolean signals by reading `.value`. This might be causing rerenders which also might cause the jumpiness.

Then generically:
- you should use the second argument to events, it is correctly typed too.
- `bind:value={signal}` implements this for you. 
- for forms, consider using modular-forms
- for small reproductions that don't use routing, it's nicer to use https://qwik.dev/playground because you can easily see the generated code

Let me know if you still have trouble after this.

**Comment by wmertens** [comment]
@Nefcanto any update?

**Comment by Nefcanto** [comment]
@wmertens, today I got a chance (time) to test it. The main point was to use `onInput$` instead of `onKeyDown$` as you mentioned. While I found that the `onInput$` is defined [here](https://qwik.dev/docs/guides/qwik-nutshell/#components), it would be awesome if it got its own section on the [Events page](https://qwik.dev/docs/components/events/#events) too. Because I used `onKeyDown$` instead of `onChange$` based on the content of that page and based on `on{EventName}$` formula.

Thank you.

**Comment by wmertens** [comment]
@Nefcanto great to hear it's good now!

If you could spare some time to update the events page so it would have stood out to you, that would be great too!

**Comment by Nefcanto** [comment]
@wmertens, sorry to answer late. I would love to, but I'm afraid I can't. As I have mentioned many times, I was not able to run a successful clone of Qwik.
