### ISSUE TITLE
[✨] Remove the initial lag for `useAuthSignin`

### ISSUE THREAD

**Issue by Nefcanto** [QwikDev/qwik#6128]
### Is your feature request related to a problem?

This is the code we use for sign-in:

```
    const signIn = useAuthSignin

    return signIn.isRunning
        ?
        <span>Signing in ...</span>
        :
        <Form action={signIn}>
            <input
                name="providerId"
                type="hidden"
                value="keycloak"
            />
            <input
                name="options.callbackUrl"
                type="hidden"
                value="/dashboard"
            />
            <input type="submit" />
        </Form>
```

The problem is that there is a lag between the user's click, and the `isRunning` becoming true. So, user clicks, and for a small amount of time nothing happens and then we see the progress message being shown.

### Describe the solution you'd like

The `useAuthSigning().isRunning` should become true as soon as the user interacts with the page for signing in (cliks the button, submits the form)

### Describe alternatives you've considered

One option is that we wrap the whole `<Form` inside a division and use `onClick$` to set our own progress and act based on that. But that does not give us the result. Where can we set the progress to false?

**Comment by PatrickJS** [comment]
using sync$ and onClick$ you toggle a loader to be visible
