### ISSUE TITLE
[🐞] prisma integration

### ISSUE THREAD

**Issue by 20181020076** [QwikDev/qwik#6132]
### Which component is affected?

Qwik Runtime

### Describe the bug

i am using prisma but it is not working
![image](https://github.com/QwikDev/qwik/assets/55093625/fe5b414a-933b-4539-bbfa-7576c32a573b)

### Reproduction

https://github.com/Wiliamfm/paramo_p1

### Steps to reproduce

npm run qwik add prisma
npm run build

### System Info

```shell
qwik chrome
```

**Comment by JerryWu1234** [comment]
I can't access https://github.com/Wiliamfm/paramo_p1, 
please help me check

**Comment by pedrosorrentino** [comment]
Hello! i have the same error when using Prisma and the adaptar of static site generation. Any ideas? Thx so much

**Comment by JerryWu1234** [comment]
> Hello! i have the same error when using Prisma and the adaptar of static site generation. Any ideas? Thx so much

Can you offer a small reproduce?
