### ISSUE TITLE
[🐞] Weird behavior when accessing props value in differents way

### ISSUE THREAD

**Issue by Wykks** [QwikDev/qwik#6133]
### Which component is affected?

Qwik Optimizer (rust)

### Describe the bug

I'm not sure how to describe it best, when accessing a value from a props in a specific way, Qwik behave differently on update, which in some case can crash the app if not expected.

### Reproduction

https://stackblitz.com/edit/qwik-starter-usz5pr?file=src%2Froutes%2Fmy-stuff-modal.tsx

### Steps to reproduce

See comments in repro 

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    @builder.io/qwik: 1.5.2 => 1.5.2 
    @builder.io/qwik-city: 1.5.2 => 1.5.2 
    undici: 5.28.2 => 5.28.2 
    vite: 4.5.2 => 4.5.2
```

**Comment by wmertens** [comment]
can you explain exactly what errors you're getting? Also, try updating qwik-ui

**Comment by Wykks** [comment]
@PatrickJS Can you elaborate a bit why this is "not planned" ? :sweat_smile: 
I believe this is a important issue in Qwik. Quite easy to workaround, but not that easy to debug.  I spent hours to identify the bug and make that reproduction, I could have spend more hours to narrow it more but closing this like that is not motivating...
