### ISSUE TITLE
[🐞] service-worker.js pre-populates the cache for some bundles that are not present on the current page

### ISSUE THREAD

**Issue by maiieul** [QwikDev/qwik#6150]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

This is a bug first encountered in Qwik UI in preview and prod. It seems to me to be a build issue, not sure if it's Rollup, Vite or the optimizer.

When our application has multiple entry files and multiple context providers, it seems that the service worker starts fetching and pre-populating the cache for some bundles that are not needed on the page.

<img width="1470" alt="image" src="https://github.com/QwikDev/qwik/assets/45822175/2e7af80a-7121-4bb6-8c10-f8855dc77e2f">

As showcased in the screenshot, I understand that the `context.id-DK1jWIYg.js` containing the `"context-2"` context is downloaded through the service-worker and placed in the cache for later use. Is this the intended behavior? I feel like Qwik should be smart enough to understand that context-2 is not needed on page /1, and therefore should only be loaded on page /2.

### Reproduction

https://github.com/maiieul/qwik-service-worker-dowloads-external-bundles

### Steps to reproduce

- pnpm i
- pnpm preview

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M2
    Memory: 5.92 GB / 24.00 GB
    Shell: 3.7.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 21.7.3 - /opt/homebrew/bin/node
    npm: 10.5.0 - /opt/homebrew/bin/npm
    pnpm: 8.14.0 - /opt/homebrew/bin/pnpm
    bun: 1.1.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 124.0.6367.62
    Safari: 17.4.1
  npmPackages:
    @builder.io/qwik: ^1.5.2 => 1.5.2 
    @builder.io/qwik-city: ^1.5.2 => 1.5.2 
    undici: * => 6.13.0 
    vite: ^5.1.6 => 5.2.9 
```

### Additional Information

I created this reproduction from a scary "bug" we are encountering in Qwik UI.
https://github.com/qwikifiers/qwik-ui/issues/719

**Comment by maiieul** [comment]
Heads up 👆

The Qwik UI issue above (https://github.com/qwikifiers/qwik-ui/issues/719) might give more context on the consequences of this issue.

**Comment by notcod** [comment]
I had that issue because of Cloudflare cache I used. Are you using cloudflare?

**Comment by maiieul** [comment]
@notcod I provided a reproduction that shows this behavior on `pnpm preview`. But we do encounter a related issue in qwik UI that might be caused by cloudflare.

**Comment by gioboa** [comment]
I checked the code and it's working as expected.
[generateLinkBundles](https://github.com/QwikDev/qwik/blob/281de9701ecae0affcf18447985646917a2ef373/packages/qwik-city/buildtime/runtime-generation/generate-service-worker.ts#L95) is populating the system to prefetch bundles related to links.

I also found a dependency here, `context.id` imports are in the same file.
Anyway, that file will be download in any case because of the prefetch mentioned before.
![image](https://github.com/QwikDev/qwik/assets/35845425/eb2a616b-5291-4330-9120-f765c001509c)

**Comment by gioboa** [comment]
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
Thanks @maiieul

**Comment by maiieul** [comment]
Thanks Giorgio for looking into this! I'm going to re-open because I think your screenshot actually also describes the issue here. 

I don't think that 
<img width="429" alt="image" src="https://github.com/user-attachments/assets/e44c5151-df07-43a5-9377-27b7accef85c">
should be included on route /1, where this code isn't needed as far as I can tell.

In the reproduction, the context-ids code is written in separate files (e.g. https://github.com/maiieul/qwik-service-worker-dowloads-external-bundles/blob/main/src/routes/1/context.id.tsx). But even if it was written in the same file, it should be possible for Qwik to output each context related code into separate bundles, no?

This might not seem like a big issue on this reproduction, but on bigger apps it might mean downloading a lot more code than necessary. If it's only contextProvider code, then maybe it's not that big of a deal. But if it's code that touches context, then the leak could potentially lead to 2 or 3 times more code *loaded* on the client, and maybe even *executed* if there are visible tasks.

**Comment by gioboa** [comment]
Can you try with the new service worker pls?

**Comment by maiieul** [comment]
We had tried that on Qwik UI as well with Jack but that didn't change much. I'll try with the reproduction here.

**Comment by gioboa** [comment]
> Can you try with the new service worker pls? [PrefetchGraph](https://qwik.dev/api/qwik/#prefetchgraph) [PrefetchServiceWorker](https://qwik.dev/api/qwik/#prefetchserviceworker)

I tested with the latest Qwik code and the new Service worker and it's working correctly.
There is no evidence of `"page 2 things"` in the `page 1` route and vice-versa.
So I'm closing this issue, more than happy to help you in the Qwik UI project for that.
