### ISSUE TITLE
[🐞] Warning and errors when validating the generated HTML using Nu Html Checker

### ISSUE THREAD

**Issue by helabenkhalfallah** [QwikDev/qwik#6175]
### Which component is affected?

Qwik Runtime

### Describe the bug

Hello, by validating the HTML generated using [Nu Html Checker](https://validator.w3.org/nu/#textarea), it generates several warnings and errors: 

The source code: 
```js
import { component$ } from '@builder.io/qwik';

export default component$(() => {
  return (
    <main>
      <h1>Qwik</h1>
      <section>
        <h2>Core features</h2>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
        </p>
      </section>
    </main>
  );
});
```

The generated HTML:
```js
<!doctype html>
<html
  q:container="paused"
  q:version="1.5.2-dev20240418142224"
  q:render="ssr-dev"
  q:base="/repl/1lsst7gz46v/build/"
  q:manifest-hash="vhqpfk"
>
  <!--qv q:key=0t_1--><head q:head>
    <title q:head>Hello Qwik</title>
  </head>
  <body>
    <!--qv q:id=0 q:key=Ncbm:0t_0-->
    <main q:key="4e_0">
      <h1>Qwik</h1>
      <section>
        <h2>Core features</h2>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat.
        </p>
      </section>
    </main>
    <!--/qv-->
  </body>
  <!--/qv-->
  <script type="qwik/json">
    {"refs":{},"ctx":{},"objs":[],"subs":[]}
  </script>
</html>
```

The playground [link](https://qwik.dev/examples/introduction/hello-world/#f=7ZbBDoIwDIZfpQ9gNBoTL8aLV68%2BwAIzNmEMhPn8fh0g%2BAAeTLwN1nXr1n5%2FF0mzPxy%2BmTRjqIaPOdztaQiLwfRvxOAikPvudDaQ3Uj4BA4x3y2mm3kscsEQ2Wu6FGBVFWEAegAL%2B1V%2BChMtnIgrtdGusJbEV8okLGWBeE1diLDa200Ax0JLLXMPklXMzoEoZtcmtJBbqPg2ubVce%2FG1BnybEDN48unCStoE3%2BpIS5NKSOofhSI3lpJA24UiDp7NCO2wnbJLbTAW77LcRQ6XA2Crfi1z%2BJTf%2B40%2F7u64me7anvpfnz9Zny8).

The W3C check results:

![image](https://github.com/QwikDev/qwik/assets/1331451/471464c7-2a34-4ac0-b7b7-71f77bcb851e)
![image](https://github.com/QwikDev/qwik/assets/1331451/23a13341-ab0c-4cc8-a3e3-4650b8417e29)

I can also reproduce the same issues when analyzing the html of some websites using Qwik.
![image](https://github.com/QwikDev/qwik/assets/1331451/3763d1d8-504c-4618-9317-d46d90ec3ca7)

Thank you so much for your help :) :) 

### Reproduction

https://qwik.dev/examples/introduction/hello-world/#f=7ZbBDoIwDIZfpQ9gNBoTL8aLV68%2BwAIzNmEMhPn8fh0g%2BAAeTLwN1nXr1n5%2FF0mzPxy%2BmTRjqIaPOdztaQiLwfRvxOAikPvudDaQ3Uj4BA4x3y2mm3kscsEQ2Wu6FGBVFWEAegAL%2B1V%2BChMtnIgrtdGusJbEV8okLGWBeE1diLDa200Ax0JLLXMPklXMzoEoZtcmtJBbqPg2ubVce%2FG1BnybEDN48unCStoE3%2BpIS5NKSOofhSI3lpJA24UiDp7NCO2wnbJLbTAW77LcRQ6XA2Crfi1z%2BJTf%2B40%2F7u64me7anvpfnz9Zny8

### Steps to reproduce

Copy/paste the generated html in the [Nu Html Checker](https://validator.w3.org/nu/#textarea).

### System Info

```shell
I used the playground on chrome (Version 124.0.6367.61) and desktop.
```

**Comment by PatrickJS** [comment]
I made an issue in their repo https://github.com/validator/validator/issues/1722
