### ISSUE TITLE
[🐞] lib mode do not respect custom lib.entry in vite config

### ISSUE THREAD

**Issue by diecodev** [QwikDev/qwik#6177]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

When you try to overwrite the entrypoints in vite.config.ts file in lib mode, the optimizer just replace your specified entrypoint for the default, disrespecting the one you specified. I take a look to the optimizer.js file and the error occurs in here `line 1870`:
<img width="1408" alt="image" src="https://github.com/QwikDev/qwik/assets/51871681/fbb6b604-3c9e-4dcc-93b2-07d2f013421c">
 

### Reproduction

https://github.com/diecodev/qwik-date/blob/main/vite.config.ts

### Steps to reproduce

- create a qwik component library project
- edit vite config file and add a custom lib.entry object or array ~ you can do this in vite, is in the [docs](https://vitejs.dev/config/build-options.html#build-lib) ~ (only if you pass a custom string as entry point this is gonna be the entry, otherwise always is gonna be replaced by 'src/index.ts'

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M2
    Memory: 67.77 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/Library/Caches/fnm_multishells/28998_1714366621848/bin/node
    Yarn: 1.22.21 - ~/Library/Caches/fnm_multishells/28998_1714366621848/bin/yarn
    npm: 10.5.0 - ~/Library/Caches/fnm_multishells/28998_1714366621848/bin/npm
    pnpm: 9.0.6 - ~/Library/Caches/fnm_multishells/28998_1714366621848/bin/pnpm
    bun: 1.1.6 - ~/.bun/bin/bun
  Browsers:
    Chrome: 124.0.6367.91
    Safari: 17.4.1
  npmPackages:
    @builder.io/qwik: 1.5.2 => 1.5.2
    undici: * => 6.14.1
    vite: ^5.1.6 => 5.2.10
```

### Additional Information

Fix this is very easy, you only need to check when the lib mode is activate if the `inputOpts.input` parameter in the `normalizeOptions` function is type Object or Array and make the proper handling for each case.

**Comment by PatrickJS** [comment]
fixed by https://github.com/QwikDev/qwik/pull/6178

**Comment by diecodev** [comment]
I just forgot to closr this issue. Thank you.
