### ISSUE TITLE
[📖] replace p element in starters

### ISSUE THREAD

**Issue by PatrickJS** [QwikDev/qwik#6235]
### Suggestion

you can't use div in p tag which creates a gotcha

**Comment by JerryWu1234** [comment]
could you tell about it more ?

**Comment by PatrickJS** [comment]
this is the gotcha https://github.com/QwikDev/qwik/pull/6236/commits/61516f4c78a1bc536b8cd87d15a9dd06b7e040aa

if you make an empty app and add divs inside the p element it wont work (this is how html works)
