### ISSUE TITLE
[📖] Sidebar Issue

### ISSUE THREAD

**Issue by nermalcat69** [QwikDev/qwik#6264]
### Suggestion

<img width="648" alt="image" src="https://github.com/QwikDev/qwik/assets/73933669/04337652-8b38-4054-be67-233c6203fc34">

How to reproduce: [video link](https://cdn.discordapp.com/attachments/1153951236974977024/1237423897591283763/Screen_Recording_2024-05-07_at_8.49.43_PM.mov?ex=663b984f&is=663a46cf&hm=a26d264bf069095ed774ec0904006422acd1cd63a34c65156d8664a769668286&)

**Comment by nermalcat69** [comment]
Browser: Safari Version 17.4.1

**Comment by PatrickJS** [comment]
thanks! I'm deploying a change right now
