### ISSUE TITLE
[✨] Create a unique file name for each version of service-worker.js

### ISSUE THREAD

**Issue by DustinJSilk** [QwikDev/qwik#6311]
### Is your feature request related to a problem?

The service-worker.js file includes a list of bundles to prefetch. If the service-worker.js file is cached by the browser or a CDN, the user may receive an outdated list of files to prefetch resulting in a large amount of unnecessary network requests which may return 404 or it could prefetch unused files. It also means that the correct files arent being prefetched which reduces performance.

### Describe the solution you'd like

Create a unique file name for each service-worker.js file so that if a new version is released, the service worker setup will install the new version.

### Describe alternatives you've considered

We could ensure we return a Cache-Control header with the service-worker.js file so that it isnt cached by browsers or CDNs, but then the page will always download a new copy even when it isnt needed.

**Comment by DustinJSilk** [comment]
This seems related to https://github.com/QwikDev/qwik/issues/6302 and also some of the issues here https://github.com/QwikDev/qwik/issues/3777.

**Comment by PatrickJS** [comment]
Where are you deploying your qwik app? Aws, cloudflare, vercel, gcp, other?

**Comment by PatrickJS** [comment]
service-worker.js spec ignores caching policy for this reason. We have another version of service-worker for MFE that we haven't documented by should be more agnostic so won't require updating

**Comment by DustinJSilk** [comment]
I see, it looks like the below adds a Cache-Control header to the service-worker.js, which causes it to cache in the CDN which means it doesnt update in the browser until the CDN entry expires.

```ts
const { router, notFound, staticFile } = createQwikCity({
  // ...
  static: {
    cacheControl: 'public, max-age=31557600',
  },
)}
```

**Comment by PatrickJS** [comment]
yeah, the cdn might be caching it but the browser won't follow the cache spec. on your cdn you can add a setting to ignore caching the service-worker.js or clear the cache for it on deploys

**Comment by DustinJSilk** [comment]
Unfortunately GCP CDN doesn't allow you to ignore a specific file, i'd need to either invalidate the entry with each deploy or remove the Cache-Control header from the service-worker.js file somehow

**Comment by PatrickJS** [comment]
@DustinJSilk ok @thejackshelton is making an example app but it should be as easy as 
replacing
`<ServiceWorkerRegister />`
with
```
<PrefetchServiceWorker />
        <PrefetchGraph />
```
in your root.tsx

**Comment by DustinJSilk** [comment]
Ok great! It looks like this will embed the symbol files in the HTML and pass it through to the service worker to then be prefetched.

Are there any draw backs in performance to using this approach as opposed to the regular service worker when it isnt cached by the CDN?

Thanks for your time!

**Comment by PatrickJS** [comment]
no drawbacks 👍 this is the new way to do it which will also works for microfrontends

**Comment by PatrickJS** [comment]
ok one thing about this (we need to fix) is that base is set to `/build/` so assuming you didn't set `base` in your ssr.entry.tsx file then it should be fine. if it's different then you have to set the new value in the component

**Comment by DustinJSilk** [comment]
ok cool, i'll get this setup and test it out on my staging environment today

**Comment by DustinJSilk** [comment]
Ah actually, the `PrefetchServiceWorker` doesnt support a nonce property like the `ServiceWorkerRegister` component.

**Comment by PatrickJS** [comment]
@DustinJSilk if you need a fix right away before the next release you can do this in `entry.ssr.tsx` for any scripts you need. 
![image](https://github.com/QwikDev/qwik/assets/1016365/7f5375eb-f3ad-40f8-8e0e-6880549b6c74)

**Comment by PatrickJS** [comment]
@DustinJSilk can you message me on the qwik discord

**Comment by DustinJSilk** [comment]
Im closing this issue since it is solved by the fact that the service worker spec doesn't cache service worker files in the browser and the PrefetchServiceWorker doesn't change with each build so it is safe to cache in a CDN.

The only thing to note is that future changes to the PrefetchServiceWorker might require some users to evict their prefetch-service-worker.js file from their CDN to reflect changes
