### ISSUE TITLE
[🐞] Error Boundary Issue

### ISSUE THREAD

**Issue by tzdesign** [QwikDev/qwik#6315]
### Which component is affected?

Qwik Runtime

### Describe the bug

Using ErrorBoundary (which is not documented) leads to symbol not found error:

<img width="445" alt="image" src="https://github.com/QwikDev/qwik/assets/3037096/c5c31c2b-1efa-4c9f-9cb5-dcef6f8c5cf4">

### Reproduction

https://github.com/tzdesign/qwik-error-boundary-issue

### Steps to reproduce

pnpm install && pnpm preview

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (14) arm64 Apple M3 Max
    Memory: 4.50 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - /usr/local/bin/node
    Yarn: 1.22.22 - ~/Library/pnpm/yarn
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: 9.0.5 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 124.0.6367.207
    Edge: 124.0.2478.105
    Safari: 17.5
  npmPackages:
    @builder.io/qwik: ^1.5.4 => 1.5.4 
    @builder.io/qwik-city: ^1.5.4 => 1.5.4 
    typescript: 5.4.5 => 5.4.5 
    undici: * => 6.16.1 
    vite: ^5.2.10 => 5.2.11
```

### Additional Information

It's also odd that qwik has a component ErrorBoundary created by Manu, but does not export it.

If I have time a bit this week, I might write docs about the error boundary.

**Comment by tzdesign** [comment]
@PatrickJS @wmertens you know if we are able to use `useErrorBoundery` in the future?

I might listen to `qerror` for now. I read the code, but I probably don't understand the issue with the log.
Still remains in 1.9.1

**Comment by wmertens** [comment]
@Varixo does the errorboundary work in v2?

**Comment by gioboa** [comment]
I have this warning in dev mode but it's working fine in dev and preview with v2.
```
QWIK WARN You are trying to add an event "onError-boundary$" using `useOn` hook, but a node to which you can add an event is not found. Please make sure that the component has a valid element node. 
```
v2 will be release soon so I marked this issue with `STATUS-3: solved by V2`, thanks.
