### ISSUE TITLE
Link is broken [📖]

### ISSUE THREAD

**Issue by greatgraphicdesign** [QwikDev/qwik#6329]
### Suggestion

On [this page](https://qwik.dev/docs/cookbook/portals/), the link in the following block of text leads to a 404.
```
The following is an SSR portal implementation using Qwik City. If you are using multiple frontend frameworks alongside Qwik, you may prefer a [React-like portal implementation](https://github.com/qwikifiers/qwik-ui/blob/main/packages/kit-headless/src/components/popover/popover-impl.tsx#L42).
```

**Comment by greatgraphicdesign** [comment]
I would be happy to if I knew the correct destination, but I don’t!

**Comment by PatrickJS** [comment]
@thejackshelton whats the correct link?

**Comment by thejackshelton** [comment]
> @thejackshelton whats the correct link?

https://github.com/qwikifiers/qwik-ui/blob/main/packages/kit-headless/src/components/popover/popover-panel-impl.tsx#L84

recently changed the name sorry about that.

**Comment by thejackshelton** [comment]
@greatgraphicdesign up for making a PR with the link above?

**Comment by greatgraphicdesign** [comment]
Submitted: https://github.com/QwikDev/qwik/pull/6334
