### ISSUE TITLE
[🐞] 1.5.5 unicode problem

### ISSUE THREAD

**Issue by dejurin** [QwikDev/qwik#6352]
### Which component is affected?

Qwik Runtime

### Describe the bug

Hello, I noticed a problem with unicode encoding in the update. You can see for yourself, have a look at the site.

<img width="466" alt="Screenshot 2024-05-22 at 03 00 37" src="https://github.com/QwikDev/qwik/assets/4470015/bf5c8786-2db5-45d0-b892-9f5170b28fd0">
<img width="623" alt="Screenshot 2024-05-22 at 03 04 27" src="https://github.com/QwikDev/qwik/assets/4470015/e0b63aa5-c35d-4393-a35a-1d02b40f7ffb">

I noticed that this problem occurs in production, in development the characters are encoded as expected.

### Reproduction

https://qwik.dev/

### System Info

```shell
Browsers: Chrome, Safari, FireFox
MacOSX: 14.4.1
```

**Comment by PatrickJS** [comment]
thanks for reporting

**Comment by PatrickJS** [comment]
to fix it anyone right now can update their root.tsx or return headers from their server to include utf-8
