### ISSUE TITLE
[🐞] Qwik development server is taking up 1 GB of memory

### ISSUE THREAD

**Issue by wanjohiryan** [QwikDev/qwik#6364]
### Which component is affected?

Qwik Runtime

### Describe the bug

<img width="771" alt="2024-05-23 03_06_16-Task Manager - Brave" src="https://github.com/QwikDev/qwik/assets/71614375/021ff2bd-2a67-4e23-857a-de5e63800a9c">

I have a simple site using Qwik, and when i run `pnpm dev` on my local machine. It will automatically take up 1GB of memory. 

I am still investigating whether this happens in production too.

### Reproduction

null

### Steps to reproduce

1. Have a fair number of pnpm workspaces in your project.
2.  Import/Reference them in your `www` and run `pnpm dev`
( you get all this imported into your console - check the sources tab in Chrome Inspector)
3. Reload times get increasingly high, and machine starts lagging.

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (4) x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
    Memory: 1.50 GB / 7.85 GB
  Binaries:
    Node: 21.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.4 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (123.0.2420.65)
    Internet Explorer: 11.0.22621.1
```

### Additional Information

Is there a way to reduce the amount of files imported or cached onto the browser when in dev mode? I think this might be the issue, because my web app works okay on some routes (very fast on the landing page). However, where there's a lot of pnpm workspace files, we start getting a lot of memory usage.

Sometimes, this files will be cached even when in routes where they are not needed. Then qwik becomes slow :(

**Comment by dejurin** [comment]
It's not clear what qwik has to do with it.

**Comment by PatrickJS** [comment]
yeah this should only be for development because of vite. so shouldn't effect your qwik app in prod

**Comment by PatrickJS** [comment]
in chrome you can set service-worker to bypass to network or you can just comment out the service-worker in dev

**Comment by wanjohiryan** [comment]
Thank you, this helped. 💖

It turns out also that my web-workers are also downloading and processing huge amounts of data. Which building up a memory heap specifically on that route.
