### ISSUE TITLE
[🐞] Error while adding Auth.js support

### ISSUE THREAD

**Issue by harshmangalam** [QwikDev/qwik#6424]
### Which component is affected?

Qwik City (routing)

### Describe the bug

[auth][error] UnknownAction: Cannot parse action at /api/auth/session. Read more at https://errors.authjs.dev#unknownaction

### Reproduction

N/A

### Steps to reproduce

- add auth.js `pnpm run qwik add auth`
- start the dev server `pnpm run dev`

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1
    Memory: 120.91 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.12.1 - ~/Library/pnpm/pnpm
    bun: 1.1.0 - /opt/homebrew/bin/bun
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 125.0.6422.113
    Safari: 17.4.1
```

**Comment by gioboa** [comment]
Hi, I'm working with the Auth.js team to refactor this integration. 
spoiler: we will move the integration inside the Auth.js codebase to guarantee the maximum level of alignment and compatibility
