### ISSUE TITLE
[🐞] Typescript error in the custom portal code provided on Qwik.dev

### ISSUE THREAD

**Issue by greatgraphicdesign** [QwikDev/qwik#6449]
### Which component is affected?

Qwik Runtime

### Describe the bug

I ran pnpm run build for the first time on my project, and I'm getting this set of Typescript errors related to the `portal-provider.tsx` code that I retrieved from the Qwik.dev website:

```
/Volumes/MBP18-Data/Web/github/qwik-weather/src/portal-provider.tsx
  62:9   error  When referencing "portals" inside a different scope ($), Qwik needs to serialize the value, however "portals.value.jsx.type" is unknown, which could be serializable or not, please make the type more specific.
Check out https://qwik.dev/docs/advanced/dollar/ for more details  qwik/valid-lexical-scope
  62:25  error  When referencing "portals" inside a different scope ($), Qwik needs to serialize the value, however "portals.value.jsx.type" is unknown, which could be serializable or not, please make the type more specific.
Check out https://qwik.dev/docs/advanced/dollar/ for more details  qwik/valid-lexical-scope
  62:59  error  When referencing "portal" inside a different scope ($), Qwik needs to serialize the value, however "portal.jsx.type" is unknown, which could be serializable or not, please make the type more specific.
Check out https://qwik.dev/docs/advanced/dollar/ for more details          qwik/valid-lexical-scope
  68:7   error  When referencing "portals" inside a different scope ($), Qwik needs to serialize the value, however "portals.value.jsx.type" is unknown, which could be serializable or not, please make the type more specific.
Check out https://qwik.dev/docs/advanced/dollar/ for more details  qwik/valid-lexical-scope
...
```

Here is the project in stackblitz:
https://stackblitz.com/github/greatgraphicdesign/qwik-weather?file=src%2Fhooks%2FuseWeather.tsx

To see the portal in action, click the white gear icon in the upper right corner of the app.

Here is the Qwik docs page containing the portal code, which I used to present the alert message:
https://qwik.dev/docs/cookbook/portals/

Is there something wrong with my implementation, or is something wrong with the example code?

### Reproduction

https://stackblitz.com/github/greatgraphicdesign/qwik-weather?file=src%2Fhooks%2FuseWeather.tsx

### Steps to reproduce

Added the custom provider-portal code provided on Qwik.dev to my project `src` folder, and imported the `Portal` and `PortalProvider` into my `layout` file and the  `PortalCloseAPIContextId` into my modal component (`alert`). 

### System Info

```shell
Reproducible on Stackblitz. See demo link.
```

**Comment by wmertens** [comment]
This is just a lint warning. You can ignore it by using `as any` or `as JsxNode<string>` (I think) 

The reason is that the default generic type for JsxNode is `unknown`, perhaps that should instead be `string |FunctionComponent<unknown>`

**Comment by greatgraphicdesign** [comment]
Thanks! Using type `any` doesn't eliminate the errors completely as I'm encountering complaints about the implicit `any` type down the chain. However, if I change the Portal definition so we have `jsx: string`, then all the errors disappear. What do you think?

```
interface Portal {
  name: string;
  jsx: string;
  close: QRL<() => void>;
  contexts: Array<ContextPair<any>>;
}
```

**Comment by thejackshelton** [comment]
The custom portal section of the docs has been removed. We suggest using the popover API (native), or for full production ready support use Qwik UI's popover.
