### ISSUE TITLE
[🐞] Service Worker prefetch strategy does not work with multiple Qwik containers

### ISSUE THREAD

**Issue by af-tomwilkins** [QwikDev/qwik#6455]
### Which component is affected?

Qwik Runtime

### Describe the bug

I am using a micro-frontend architecture using Qwik, serving from Cloudflare Workers. I am trying to get speculative module fetching working, but have found that it does not work when multiple containers are present with unique bases.

I posted a question on [Discord](https://discord.com/channels/842438759945601056/1246079319877357690) about this and was advised to post as an issue here.

As an example, here is a script rendered from one of the containers in the reproduction repository:
```html
<script q:type="prefetch-bundles">
  document.dispatchEvent(
    new CustomEvent("qprefetch", {
      detail: { bundles: ["q-fcd49e5f.js", "q-6dc420be.js"] },
    })
  );
  document.dispatchEvent(
    new CustomEvent("qprefetch", { detail: { links: [location.pathname] } })
  );
</script>
```

Notice that the base is not included in the emitted event.

Here is the script rendered by using the `PrefetchServiceWorker` component (which I appreciate is alpha, but the same problem exists for `RegisterServiceWorker` from `qwik-city`).

```html
<script q:key="prefetch-service-worker" q:head="">
  ((e, t, n, s, r) => {
    (r = e.getAttribute("q:base")),
      e.getAttribute("q:manifest-hash"),
      t
        .register("/qwik-prefetch-service-worker.js", { scope: "/" })
        .then((o, i) => {
          (i = () => n.forEach((n.push = (c) => o.active.postMessage(c)))),
            o.installing
              ? o.installing.addEventListener(
                  "statechange",
                  (c) => c.target.state == "activated" && i()
                )
              : i();
        }),
      s && n.push(["verbose"]),
      document.addEventListener(
        "qprefetch",
        (o) => o.detail.bundles && n.push(["prefetch", r, ...o.detail.bundles])
      );
  })(
    document.currentScript.closest("[q\\:container]"),
    navigator.serviceWorker,
    window.qwikPrefetchSW || (window.qwikPrefetchSW = []),
    true
  );
</script>

```

As the base is inferred from the closest container, this will always resolve to the base from the container where the Service Worker is registered. This means any bundles from other containers will have incorrect URLs constructed before being forwarded to the Service Worker.

What I would expect to see is for `qprefetch` events to include the base of the closest container, so that the correct URLs are constructed. Where the events are consumed and forwarded to the worker, the correct base is not in scope at all, so it has to be included in the event.

In creating the repro, I noticed an additional bug with the Service Worker itself, in [https://github.com/QwikDev/qwik/blob/f6fc2f855a11b541d383bf9b26db399dbb781a5a/packages/qwik/src/prefetch-service-worker/process-message.ts#L150](GitHub)

```ts
export function drainMsgQueue(swState: SWState) {
  if (!swState.$msgQueuePromise$ && swState.$msgQueue$.length) {
    const top = swState.$msgQueue$.shift()!;
    swState.$msgQueuePromise$ = processMessage(swState, top).then(() => {
      drainMsgQueue(swState);
    });
  }
}
```

Messages are only processed when `$msgQueuePromise$` is falsey. Conceptually this is fine, however there is no code that restores it to a falsey value when all messages are processed. The result is that only the first message to the SW is processed. Happy to raise a separate issue on this if that's preferable.

### Reproduction

https://github.com/af-tomwilkins/cloudflare-qwik-mfes/tree/main

### Steps to reproduce

1. Clone the reproduction repo
2. See the README
3. Run `npm i`
4. Open terminal in `packages/main` directory, run `npm start`
5. Open terminal in `packages/body` directory, run `npm start`
6. Open [localhost:8080](http://localhost:8080)
7. Use the rendered toggle button to observe module loading
8. View source to see Qwik `prefetch-bundles` and `prefetch-service-worker` elements as described

### System Info

```shell
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 2.74 GB / 15.79 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.1.7 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.18362.1474.0)
    Internet Explorer: 11.0.18362.1
```

**Comment by gioboa** [comment]
Hi, thanks for your report. I will look at it

**Comment by JerryWu1234** [comment]
Will fix it in v2?

**Comment by gioboa** [comment]
We are investigating into it for the v1 as well
I created this basic mfe starter to deep dive the problem 
https://github.com/gioboa/qwik-microfrontend-starter

**Comment by thejackshelton** [comment]
Hi @af-tomwilkins,

As you mentioned, restoring $msgQueuePromise$ to a falsy value resumes the prefetching.

I've installed the specific debug commit of @builder.io/qwik and @builder.io/qwik-city using the following commands:
```
npm i https://pkg.pr.new/@builder.io/qwik@b2a3d22
npm i https://pkg.pr.new/@builder.io/qwik-city@b2a3d22
```

Currently, I'm debugging further in debug mode. We're making progress! 🫡

Thank you for your patience.

**Comment by af-tomwilkins** [comment]
Hi @thejackshelton , @gioboa 👋 

I really appreciate the speed of the fix here, it's made a huge different to my application. Thank you. 

There is however a lingering issue that hopefully you can help with.

The new prefetch strategy works by pushing into the `qwikPrefetchSW` array. This takes the container base into account, so it all works well.

My problem is that there doesn't seem to be a way to turn off the old strategy, which fires `qprefetch` events on the document. The `prefetch-service-worker` listens for these and prepends with the base from the closest container - where the service worker is registered (same problem as before).

I've pushed some changes to my reproduction repo to 404 on JS that can't be found, which makes it more obvious in the network tab when this is happening:

![image](https://github.com/QwikDev/qwik/assets/65285334/cd42bf12-3239-40da-bfa9-f77a7c22ce35)

The failed requests are from the `qprefetch` strategy, where bundles for the `body` container get prepended with `main`.

You'll notice there are successful requests for the same filenames. These are from the `qwikPrefetchSW` and have the correct base prepended, as per the fix.

Is there any way I can disable `qprefetch`? Or should I raise an issue?

Thanks again.

**Comment by gioboa** [comment]
We are working on it because we noticed the same issue in our official mfe application. Stay tuned, thanks for the feedback

**Comment by af-tomwilkins** [comment]
Thanks @gioboa , that's much appreciated. Is there an issue I can follow for it?

**Comment by gioboa** [comment]
Yup #6582 fixed it
