### ISSUE TITLE
[🐞] TextEncoderStream polyfill breaks resumability

### ISSUE THREAD

**Issue by mhuretski** [QwikDev/qwik#6458]
### Which component is affected?

Qwik Runtime

### Describe the bug

In qwik-city 1.5.5 new [TextEncoderStream polyfill](https://github.com/QwikDev/qwik/pull/6310) was introduced. 

When deployed to Cloudflare useLexicalScope might return undefined for signals in some weird scenarios. Or qrls might stop working or anything else due to errors during resumability on client. 
I assume it occurs due to encoding issues, for example with new TextEncoderStream containers have `class="qc�"` when in 1.5.4 `class="qc📦"`. Some other symbols might also be corrupted, so qwik can't resume containers in edge cases.

Issue might not be reproducible if amount or sequence of counters is different or even if something irrelevant is removed like head nodes somewhere else.

### Reproduction

https://github.com/mhuretski/qwik-starter-1djsma

### Steps to reproduce

qwik-city 1.5.4 https://30efff55.check-qwik-155.pages.dev/ (OK)
qwik-city 1.5.5:
 - qwik 1.5.5 https://a2ac90cb.check-qwik-155.pages.dev/ (broken)
 - qwik 1.5.4 https://9fd9292e.check-qwik-155.pages.dev/ (broken)

1. click any of first 2 buttons
2. in 1.5.5 version containers are resumed corrupted when in 1.5.4 it's ok.

### System Info

```shell
cloudflare pages, qwik-city 1.5.5
```

**Comment by octet-stream** [comment]
@mhuretski you can test the fix by installing qwik-city from here: https://github.com/QwikDev/qwik/pull/6466#issuecomment-2154865837

**Comment by PatrickJS** [comment]
yeah, you have to setup Cloudflare to use nodejs api for 1.5.5 for it to work otherwise in the next release 1.5.6 it will work
