### ISSUE TITLE
[🐞] Strange types issue when building components

### ISSUE THREAD

**Issue by ziimakc** [QwikDev/qwik#6459]
### Which component is affected?

Qwik Runtime

### Describe the bug

Building one component on top of another gives strange typescript issues:

```
type InputProps = PropsOf<"input">;

export const InputBase = component$<InputProps>((props) => {
  return <input {...props} />;
});
```
Error
- Types of property bind:checked'' are incompatible
- Type 'Signal<boolean | undefined>' is not assignable to type 'never'

```
export const InputWrapper = component$<InputProps>((props) => {
  return <InputBase autoComplete="email" {...props} />;
});
```

While this works fine
```
export const InputWrapper2 = component$<InputProps>((props) => {
  return <InputBase {...props} />;
});
```

---

Also works if you omit a few properties from type:
```
type InputProps = Omit<
	PropsOf<"input">,
	"bind:checked" | "popovertarget" | "toggle" | "popovertargetaction"
>;
```

### Reproduction

https://github.com/ziimakc/qwik-types-issue

### Steps to reproduce

- `pnpm i`
- `tsc`

### System Info

```shell
-
```

**Comment by JerryWu1234** [comment]
@ziimakc Maybe you can try to use `autocomplete`.
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

**Comment by JerryWu1234** [comment]
![image](https://github.com/QwikDev/qwik/assets/27261522/f29e7b8c-8ab9-4e0c-8152-355560e73a98)

**Comment by gioboa** [comment]
@ziimakc did you solve the problem?
