### ISSUE TITLE
[🐞] After Integrating Builder.io

### ISSUE THREAD

**Issue by ps6067966** [QwikDev/qwik#6461]
### Which component is affected?

Qwik Runtime

### Describe the bug

![image](https://github.com/QwikDev/qwik/assets/26248740/528468d6-8c01-4a73-ae48-50e58094f05d)

I'm using npm run dev command. 

Completely New Project. 

### Reproduction

none

### Steps to reproduce

New Project. 
Integrate Builder.io 
npm run dev command. 

### System Info

```shell
{
  "name": "my-qwik-site-with-visual-cms",
  "description": "Site integrated with Builder.io for visual editing",
  "engines": {
    "node": "^18.17.0 || ^20.3.0 || >=21.0.0"
  },
  "engines-annotation": "Mostly required by sharp which needs a Node-API v9 compatible runtime",
  "private": true,
  "trustedDependencies": [
    "sharp"
  ],
  "trustedDependencies-annotation": "Needed for bun to allow running install scripts",
  "type": "module",
  "scripts": {
    "build": "qwik build",
    "build.client": "vite build",
    "build.preview": "vite build --ssr src/entry.preview.tsx",
    "build.types": "tsc --incremental --noEmit",
    "deploy": "echo 'Run \"npm run qwik add\" to install a server adapter'",
    "dev": "vite --mode ssr",
    "dev.debug": "node --inspect-brk ./node_modules/vite/bin/vite.js --mode ssr --force",
    "fmt": "prettier --write .",
    "fmt.check": "prettier --check .",
    "lint": "eslint \"src/**/*.ts*\"",
    "preview": "qwik build preview && vite preview --open",
    "start": "vite --open --mode ssr",
    "qwik": "qwik"
  },
  "devDependencies": {
    "@builder.io/dev-tools": "^1.0.12",
    "@builder.io/qwik": "^1.5.5",
    "@builder.io/qwik-city": "^1.5.5",
    "@builder.io/sdk-qwik": "^0.14.10",
    "@types/eslint": "^8.56.10",
    "@types/node": "^20.12.7",
    "@typescript-eslint/eslint-plugin": "^7.7.1",
    "@typescript-eslint/parser": "^7.7.1",
    "eslint": "^8.57.0",
    "eslint-plugin-qwik": "^1.5.5",
    "prettier": "^3.2.5",
    "typescript": "5.4.5",
    "undici": "*",
    "vite": "^5.2.10",
    "vite-tsconfig-paths": "^4.2.1"
  }
}
```

### Additional Information

Package Json

**Comment by ps6067966** [comment]
Builder.io integration is super important to me. Please fix this as soon as possible. 
We want to migrate our website with help of builder.io

**Comment by ps6067966** [comment]
If any more information is required. Please let me know.

**Comment by JerryWu1234** [comment]
> Builder.io integration is super important to me. Please fix this as soon as possible. We want to migrate our website with help of builder.io

Could you offer a reproduce ?

**Comment by ps6067966** [comment]
> > Builder.io integration is super important to me. Please fix this as soon as possible. We want to migrate our website with help of builder.io
> 
> Could you offer a reproduce ?

To Reproduce Error: 
1. npm create qwik@latest
2. Select recommended options, like app with routing. 
3. npm i
4. npm run qwik add builder.io  
run above command to integrate builder.io 
5. npm run dev
6. You'll see error. 

npm run qwik add builder.io  
This command doesn't produce .env file as well with recommended options.

**Comment by gioboa** [comment]
> Builder.io integration is super important to me. Please fix this as soon as possible. 
> We want to migrate our website with help of builder.io

Thanks for reporting this is issue.
We have a weekly schedule to resolve bugs and implement features. I can understand that it's important to you, but I would like to keep the tone of the conversation as polite and calm as possible. Thanks

**Comment by JerryWu1234** [comment]
@ps6067966 
![image](https://github.com/QwikDev/qwik/assets/27261522/aee82ec2-b886-4c7c-b036-0a66edb89065)
![image](https://github.com/QwikDev/qwik/assets/27261522/21a76dc8-6491-4fd6-b5b2-af73d31fca73)

everything is fine for me

**Comment by wmertens** [comment]
The error is "invalid path" which windows shows when a reserved filename is used. 

Try using WSL for development?

Or try in a different directory without a space?

**Comment by ps6067966** [comment]
> The error is "invalid path" which windows shows when a reserved filename is used.
> 
> Try using WSL for development?
> 
> Or try in a different directory without a space?

Thank you. 
issue was folder space name. 
after moving to different directory, it worked. 

Thank you once again.

**Comment by gioboa** [comment]
Thanks you all. I'm glad that it's solved.
