### ISSUE TITLE
[🐞] Qwik removes elements generated by 3rd party plugin

### ISSUE THREAD

**Issue by KingSora** [QwikDev/qwik#6464]
### Which component is affected?

Qwik Runtime

### Describe the bug

Qwik removes element which were generated by a 3rd party plugin. The 3rd party plugin is not written in qwik.

### Reproduction

https://stackblitz.com/edit/qwik-starter-riimvh?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

1. Let the app initialize, notize the red border (this element is generated by the 3rd party plugin)
2. Click on the "Hide Content" Button
3. The red border disappeared because the element was removed

I've build the same example in react: https://stackblitz.com/edit/vitejs-vite-euyxdy?file=src%2FApp.tsx which doesn't have the same problem. `Svelte`, `Vue`, `Angular` and `Solid` also dont have the same problem.

### System Info

```shell
Shouldn't matter
```

**Comment by wmertens** [comment]
You shouldn't touch the div you're running the plugin on. Just run it in the visible task and if you want to show/hide, do it with a slot in a parent component. 

You also shouldn't track the ref

**Comment by KingSora** [comment]
@wmertens I'm not touching the element I'm running the element on. I'm touching one of its **children**.

Please re-consider this circumstance

**Comment by wmertens** [comment]
Ok, but Qwik has to have full control over the entire DOM of the container (leaves excepted). So if you want to change a child, you need to either:
- make it a portal using a hack in v1 (see qwik-ui popover to see how)
- wait for portals in v2 (API still TBD)
- use a different container and communicate using custom events and globals

**Comment by wmertens** [comment]
What is your specific usecase? Did you consider porting the third party library?

**Comment by KingSora** [comment]
> Ok, but Qwik has to have full control over the entire DOM of the container (leaves excepted). 

I guess I'm just confused about the fact that an non-related element is removed from the DOM even though the element has nothing to do with the element which was removed, besides the parent. And since other frameworks handle cases like this just fine, I would assume this is an wrong assumption qwik makes about its DOM updates.

> What is your specific usecase?

I'm trying to make a qwik wrapper for my vanilla js library. The library generates its own elements. Essentially the DOM before an initialization looks like this:

```jsx
<target> {/** created by qwik */}
  <viewport> {/** created by qwik */}
    <Slot />
  </viewport>
<target>
```

After initialization:
```jsx
<target> {/** created by qwik */}
  <foreign /> {/** created outside qwik */}
  <viewport> {/** created by qwik */}
    <Slot />
  </viewport>
  <foreign /> {/** created outside qwik */}
  <foreign /> {/** created outside qwik */}
<target>
```

Now I would expect qwik to just ignore all `foreign` elements, because the template doesn't allow any modifications in those places anyway. But qwik makes unexpected modifications to the `foreign` elements when I, for example, change the `style` attribute of the `target` element.

> Did you consider porting the third party library?

Well, this is supposed to be the port. Re-writing the whole library in qwik is out of the question since the maintenance would become too much of an hassle.

**Comment by KingSora** [comment]
@wmertens I'm really sorry when I'm annoying with this issue but I'm convinced this is one area qwik should improve in.

I've debugged the whole thing and the following things are my findings:

- This problem happens because of how the the old and new v-dom state is [determined](https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/render/dom/render-dom.ts#L49-L51)
- In the _**very first update cycle**_ of the component on the client (the cycle where I'm toggeling a property) the `old v-dom` result returns a empty children array. This is technically not correct since I have children (in the real dom and v-dom).
- Because of this the children diffing kicks in and does its thing. In this process the foreign and qwik generated dom elements are all mixed up.
- In all subsequent updates the `old v-dom` result is correct because it probably uses some kind of cache of the previous update cycle.

To me this looks like the very first state change "hydrates" the component and potentially completely re-renders it. All subsequent state changes are fine-grained updates (at least updates to children).

So my workaround would be to trigger a "dummy" re-render of the component as soon as it is mounted in the DOM and in the following render cycle initializing my plugin. 

My question is now: Do you think this can be improved? I would gladly contribute to qwik and solve this issue. This could not only improve on my issue but also bring potential performance improvements.

**Comment by wmertens** [comment]
Right, so that technique is exactly what we do in qwik-ui for popovers.

However, V2 will be more robust to DOM changes, so one option would be to just wait and see :)

We're also planning to have a react-like portal API, maybe.

**Comment by KingSora** [comment]
@wmertens alright, thank you! :)
