### ISSUE TITLE
[🐞] onSubmit$ / onSubmitComplete$ signature broken?

### ISSUE THREAD

**Issue by tzdesign** [QwikDev/qwik#6541]
### Which component is affected?

Qwik Runtime

### Describe the bug

The signature seems to be broken. At least for default usage like this:

```tsx
<Form
      action={action}
      onSubmit$={() => {
        console.log('Test');
      }}
 >
      <input type="text" name="text" required class={styles.input} />
      <button type="submit">
        Add item
      </button>
</Form>
```

<img width="653" alt="image" src="https://github.com/QwikDev/qwik/assets/3037096/c6834d8d-8ad2-4456-bcc7-b6369dc7c2c5">

### Reproduction

https://stackblitz.com/edit/qwik-starter-zbdln6?file=src%2Froutes%2Fdemo%2Ftodolist%2Findex.tsx

### Steps to reproduce

Open stackblitz and go to the starter todo list on the bottom.
Code works, typescript cries like a baby.

### System Info

```shell
Tested on Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @builder.io/qwik: ^1.5.7 => 1.5.7 
    @builder.io/qwik-city: ^1.5.7 => 1.5.7 
    typescript: 5.3.3 => 5.3.3 
    undici: 5.28.2 => 5.28.2 
    vite: 4.5.2 => 4.5.2
```

### Additional Information

We don't update, because we have it in multiple places with embedded functions.
I guess @PatrickJS changed the signature in 1.5.6?

If I find some spare time next week I might be able to check these types, but normally all marked $ props are inferred as QRL by default, except this two.

**Comment by thejackshelton** [comment]
@tzdesign you need a QRL there

```tsx
          onSubmit$={$(() => {
            console.log('Test');
          })}
```

or:

```tsx
const handleSubmit$ = $(() => {
 //
})

onSubmit$={handleSubmit$}
```

**Comment by PatrickJS** [comment]
@tzdesign this is my fault it's purely type issue

**Comment by tzdesign** [comment]
@PatrickJS good that you already have a clue. I hope it's easy to fix?

**Comment by PatrickJS** [comment]
fixed in https://github.com/QwikDev/qwik/pull/6542
