### ISSUE TITLE
[✨] Please let us disable __image__info

### ISSUE THREAD

**Issue by Nefcanto** [QwikDev/qwik#6549]
### Is your feature request related to a problem?

For any reason when __image__info does not work, and the website contains lots of images the console is littered with hundreds of errors related to the __image__info. This is extremely annoying. Extremely.

### Describe the solution you'd like

No solution comes to my mind. We just painstakingly scroll before or after those __image__info lines to find out our logs and other information.

### Describe alternatives you've considered

No alternatives.

**Comment by gioboa** [comment]
Hi @Nefcanto can you share a screenshot of this problem pls?

**Comment by Nefcanto** [comment]
@gioboa, sure.

![imageedit_5_4677573269](https://github.com/QwikDev/qwik/assets/12782347/461c887c-fbd3-4dcb-9653-12ca74306b4b)

**Comment by gioboa** [comment]
I see, can you create an example with qwik.new pls? I would like to reproduce the error but I'm not sure if I am covering your case.

**Comment by PatrickJS** [comment]
well I think we should just have an option to not have the image features

**Comment by gioboa** [comment]
You are right @PatrickJS 
Here you are https://github.com/QwikDev/qwik/pull/6427

**Comment by gioboa** [comment]
Closed by #6427
