### ISSUE TITLE
[🐞] Bug in Link component (SSG)

### ISSUE THREAD

**Issue by acalexuy** [QwikDev/qwik#6560]
### Which component is affected?

Qwik Runtime

### Describe the bug

There's a bug on Qwik particularly SSG websites, that whenever you use a link component. The content doesn't change but the URL change.

My expected behavior is it will work like the Link component on Next.js

Qwik - https://project-zeus-gold.vercel.app/news/home-loans/home-loans-in-brisbane/
Next JS - https://cns-next-acalexuy.vercel.app/home-loans/gene-breakthrough-restores-the-sight-of-people-with-inherited-eye-disease-and-could-save-thousands-from-blindness/

### Reproduction

https://project-zeus-gold.vercel.app/news/home-loans/home-loans-in-brisbane/

### Steps to reproduce

1. Go to https://project-zeus-gold.vercel.app/news/home-loans/home-loans-in-brisbane/
2. Click any latest articles below
3. Notice that the route changes but the content does not

### System Info

```shell
"@builder.io/qwik": "^1.5.1",
"@builder.io/qwik-city": "^1.5.1",
```

**Comment by gioboa** [comment]
Hi @acalexuy can you recreate a basic example with [qwik.new](https://qwik.new) please?
We can't debug your code in the browser to check the issue and we can't clone your repo either because an entire application has too many variables to configure.

**Comment by gioboa** [comment]
Hi,
q-data are used in  routeAction$() and gobalAction$() and you need an up and running server for that. So SSG is not the correct way to deploy your app.

**Comment by acalexuy** [comment]
Thanks @gioboa, I thought it will be like [getStaticProps ](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-static-props)of Next.js 12 which get's the data on build

**Comment by gioboa** [comment]
I see, [here](https://qwik.dev/docs/guides/static-site-generation/#ssg-vs-server-side-rendered-ssr) you can find a well written page about SSG vs SSR in Qwik.

**Comment by acalexuy** [comment]
From the doc, "SSG pre-renders each webpage at build-time" so it's already generated. And I can confirm this on my app

1. Go to https://project-zeus-gold.vercel.app/news/home-loans/melbourne-home-loan-market-trends/
2. Click "Home Loans in brisbane" article under the Latest articles
3. Notice that the route changes but the content does not
4. But when you do a full reload on the page, the content is updated

**Comment by gioboa** [comment]
You are right, I'll check it 👏💪

**Comment by gioboa** [comment]
You can use a public data source as well I guess
eg. https://swapi.dev/

**Comment by wmertens** [comment]
I suppose there are several things happening here:
- `q-data.json` for all route loaders should be generated and stored during SSG
  - but it should be generated by the server if there is one running
- when q-data can't be fetched, there should be some error visible
  - perhaps via a custom DOM event that can be prevented so that it can be intercepted, and if not intercepted show an alert dialog?

**Comment by acalexuy** [comment]
> You can use a public data source as well I guess eg. https://swapi.dev/ and compile your app with SSG mode

This will not work. Because the source is online. I already tried this on my repo https://github.com/acalexuy/qwik-ssg/blob/5dddbbf6664b41c381374a7d2bc19e2dddacdabb/src/routes/news/%5Bslug%5D/index.tsx and here's the app https://qwik-ssg-sample.vercel.app/. It works fine 

To replicate the issue, the website must be generated using a local data

**Comment by gioboa** [comment]
I see, you can use [JSON Server](https://www.digitalocean.com/community/tutorials/json-server) to simulate a local server

**Comment by acalexuy** [comment]
Hi @gioboa, I already solved the issue. The cause of the issue is returning null on the component when there's no data. I solved it by just returning a fragment
`if (!articlePageData) return null;` to `if (!articlePageData) return <></>;`

**Comment by gioboa** [comment]
Nice, thanks for the update.

**Comment by acalexuy** [comment]
I also discovered another bug, when you tried to put a URL that doesn't exist on Link component. It will go to that 404 page automatically

Here's the sample

1. Go to https://qwik-ssg-sample.vercel.app/news/home-loans/1/
2. Click "Go to news 4"
3. Wait for a sec, it will redirect you to `/news/home-loans/5` which is 404

Here's a minimal reproduction https://github.com/acalexuy/qwik-ssg. Run first the json-server `npx json-server ./mocked/news.json` then `npm run preview`

**Comment by gioboa** [comment]
What behavior do you expect here?

**Comment by acalexuy** [comment]
It should not automatically redirect to the 404 page, unless the user click the link

**Comment by gioboa** [comment]
Oh I see. Nice catch, can you open an issue for this pls? Thanks
