### ISSUE TITLE
[🐞] Vite+Qwik JavaScript template preset not working

### ISSUE THREAD

**Issue by brybrant** [QwikDev/qwik#6567]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

Hi! I reported this issue to the Vite repo:
https://github.com/vitejs/vite/issues/17473

...But I was told it's an issue with Qwik so I should report the issue here instead

### Reproduction

https://stackblitz.com/edit/vitejs-vite-bgwvyc

### Steps to reproduce

```bash
> npm create vite@latest
> Select a framework - Qwik
> Select a variant - JavaScript

> npm install

> npm run dev
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 6.00 GB / 15.94 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: 1.22.19 - ~\.yarn\bin\yarn.CMD
    npm: 10.1.0 - C:\Program Files (x86)\nodejs\npm.CMD
    pnpm: 9.3.0 - C:\Program Files (x86)\nodejs\pnpm.CMD
  Browsers:
    Chrome: 125.0.6422.142
    Edge: Chromium (125.0.2535.92)
    Internet Explorer: 11.0.19041.4355
```

**Comment by gioboa** [comment]
Thanks for your feedback, we will look at the code to solve the problem.
