### ISSUE TITLE
[✨]Adding visual clue in the docs TOC

### ISSUE THREAD

**Issue by Kampouse** [QwikDev/qwik#6580]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

currently all the  navigation links are in one color "Blue"   

### Describe alternatives you've considered

changing the font colour when you change section in the docs would be great 
the Nextjs docs  as this current implementation 
![image](https://github.com/QwikDev/qwik/assets/41765025/5f7adebf-3aca-4cfc-8719-aa84369df02b)

### Additional context

thanks you
i am  considering trying to do it!
Is it worth the efforts?

**Comment by thejackshelton** [comment]
Sounds great to me 👍 . We do something similar in the Qwik UI Table of contents
https://qwikui.com/docs/headless/introduction/

Although it's not a primary / active color it's bold. I think it's worth the effort, makes it more clear where you actually are on the page.

**Comment by shairez** [comment]
@Kampouse thanks!
want to take a stab at it?

**Comment by Kampouse** [comment]
Yes!

**Comment by thejackshelton** [comment]
@Kampouse did we end up tackling this?

**Comment by Kampouse** [comment]
@thejackshelton   i had some qwik issue 
![image](https://github.com/user-attachments/assets/b0826dbd-ed87-406e-84a5-2f2dbe687190)
should look into what they were

**Comment by thejackshelton** [comment]
> [@thejackshelton](https://github.com/thejackshelton) i had some qwik issue ![image](https://private-user-images.githubusercontent.com/41765025/348762583-b0826dbd-ed87-406e-84a5-2f2dbe687190.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTc3NDAsIm5iZiI6MTcyMTA1NzQ0MCwicGF0aCI6Ii80MTc2NTAyNS8zNDg3NjI1ODMtYjA4MjZkYmQtZWQ4Ny00MDZlLTg0YTUtMmYyZGJlNjg3MTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE1MzA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NzgwNDk4MjBmMDM3YTdjMGY1ZjI5ZWY1NTgxNGU1YjE0ZDk5OTQyODQ1YTFmMTQxN2FhM2NhMTUyM2MzNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yWv0D5hRvXmnlZSOpZZVnKdAV8DbieiExod9rj2iWHI) should look into what they were

Is there a PR up I can look through! Will check out the problem 👍

**Comment by Kampouse** [comment]
@thejackshelton   i always ended up with this annoyance 
![image](https://github.com/user-attachments/assets/bfde64aa-71ec-4077-a531-a63781ef7cfa)

**Comment by Kampouse** [comment]
i will update my  repository ti lastest to see if change anything

**Comment by maiieul** [comment]
@kampouse you might want to check out the toc component we have in Qwik UI for an accessible component (https://github.com/qwikifiers/qwik-ui/blob/main/apps/website/src/components/toc/toc.tsx). Although we to resort to a few hacks to make it more accessible with uls...  So it might be better to wait a bit for it be more robust.

Until then you could use our previous implementation (https://github.com/qwikifiers/qwik-ui/blob/6626767f3d798a93e5d1a87fc99c9af98f0cd326/apps/website/src/components/toc/toc.tsx), which should make it easy to switch to our current one later. You can still use the useOnDocument that we use on the current implementation.

Feel free to DM me on Discord if you want to sync!

**Comment by Kampouse** [comment]
that exactly what i was using

**Comment by TheMcnafaha** [comment]
Calling it "hacks" is a bit of an exaggeration. It's all standard JS patterns that are also used in other repos like shadcn. I would also strongly advise against basing your work on the previous TOC for two reasons: (1) we have moved into a recursive pattern and (2) no longer use visible tasks. Both of these changes significantly alter the behavior of the component, meaning that a solution that works in the old TOC might not work in the current one. Plus, you will have nasty merge conflicts.

I contributed a lot to the refactor of the current TOC, so feel free to ask me any questions about it.  My gut feeling is that you should look at the anchor component, especifically at the conditional class.

**Comment by Kampouse** [comment]
Hi i had i a bit more success with   useWindow  followed the https://github.com/qwikifiers/qwik-ui/blob/main/apps/website/src/components/toc/toc.tsx?rgh-link-date=2024-07-15T15%3A51%3A56Z  and  
![image](https://github.com/user-attachments/assets/255af03e-5ac9-41c5-b721-2a8345874867)
  while it worked for some odd reason when  removing my text "am active" the wholing returned to the qwik env issue

**Comment by Kampouse** [comment]
i open a pr related to this here https://github.com/QwikDev/qwik/pull/6689

**Comment by TheMcnafaha** [comment]
is this the desired result?
![image](https://github.com/user-attachments/assets/eff31dec-a08d-4f43-99c2-bd9436d502d8)

**Comment by Kampouse** [comment]
yes this the desired result

**Comment by TheMcnafaha** [comment]
Then you actually have a good blueprint to use. 

The big picture is that you need to implement the active item code from the qwikui TOC (look at the useActiveItem function) and then implement this anchor component:

```js
const Anchor = component$<AnchorProps>(({ node, activeItem }) => {
  const isActive = node.id === activeItem;
  return (
    <a
      href={`#${node.id}`}
      onClick$={[
        $(() => {
          const element = document.getElementById(node.id);
          if (element) {
            const navbarHeight = 90;
            const position =
              element.getBoundingClientRect().top + window.scrollY - navbarHeight;
            window.scrollTo({ top: position, behavior: 'auto' });
          }
        }),
      ]}
      class={cn(
        node.level > 2 && 'ml-2',
        'inline-block no-underline transition-colors hover:text-foreground',
        isActive ? 'font-medium text-foreground text-red-400' : 'text-muted-foreground',
      )}
    >
      {node.text}
    </a>
  );
});
```

This should work as it doens't rely on recursion.

**Comment by gioboa** [comment]
It's is done. I close it.
