### ISSUE TITLE
[🐞] PrefetchServiceWorker throws `insufficient resources` when navigating while prefetching

### ISSUE THREAD

**Issue by DustinJSilk** [QwikDev/qwik#6602]
### Which component is affected?

Qwik Runtime

### Describe the bug

While the PrefetchServiceWorker prefetches the graph, if you interact/navigate to a new page which triggers another prefetch, the browsers throws errors with insufficient resources.

Please see the below video.

https://github.com/QwikDev/qwik/assets/5979984/b38f056e-8baf-48b8-999d-33a63282dfe8

### Reproduction

https://github.com/DustinJSilk/qwik-prefetch-nav-crash

### Steps to reproduce

`$ ./generate.sh`

`$ pnpm i`

`$ pnpm preview`

Click on the `page` link before the graph finishes prefetching and see 404s thrown.

### System Info

```shell
n/a
```

**Comment by gioboa** [comment]
How can we solve this issue? @DustinJSilk do you have a possible solution?

**Comment by DustinJSilk** [comment]
I'm not too clued up on the current implementation, but would this not point to an issue where `$maxPrefetchRequests$` isn't being respected, which means the dependencies for the linked page are all being fetched with the highest priority?
So the issue here would actually be how the graph is built where all 750 child pages are set as required dependencies for the navigated page to load when they aren't needed yet

**Comment by gioboa** [comment]
Can you test [this version](https://github.com/QwikDev/qwik/pull/6607/checks?check_run_id=26678843432) in your environment pls? It works fine for me.

**Comment by DustinJSilk** [comment]
I'm still getting the same issue mentioned above.

It seems to exist in reverse order as well in a slightly different way, maybe this will help to identify the problem:
When first loading the child page, it doesn't prefetch all the symbols yet. Then, when navigating to the home page it prefetches all the symbols in parallel causing the same error as above. I've attached a video below showing this similar issue.

https://github.com/QwikDev/qwik/assets/5979984/d19f32e5-a89f-4327-a129-89c0363dd000

**Comment by DustinJSilk** [comment]
As I think about it, i wonder if its safe to allow the browser to throw these errors since as long as they eventually recover. We don't know what the limit is per device and don't want to restrict how fast we prefetch if the files are high priority.

So I think the real issue here isn't the fact that the errors are being thrown, they can be ignored, but rather that we're fetching bundles with high priority when they aren't in fact high priority.

**Comment by gioboa** [comment]
In my PR the dependencies have less priority than the "prefetch" bundles. I think we need to limit the requests in parallel

**Comment by gioboa** [comment]
It's similar to #6150 because here is fetching all the pages basically

**Comment by jwickers** [comment]
BTW the doc here: https://qwik.dev/docs/routing/#link-prefetch does not mention the onVisible prefetching

**Comment by DustinJSilk** [comment]
I would say disabling the prefetch would be the wrong solution. What should happen is that the requests for the link you’re navigating to should be fetched with the highest priority so that it doesn’t need to wait for the rest of the prefetches to complete.

**Comment by thejackshelton** [comment]
I think what's actually going on here is the moment a possible interaction is on the page, the new prefetch service worker will start grabbing anything it can in the application and start adding it to the bundle graph, regardless of if there is any possible links to navigate to on the page.

https://github.com/user-attachments/assets/450b1a75-a23e-4117-9b21-6bb9c991ab64

This is a more minimal reproduction, following the same reproduction steps. We create a bunch of routes, and then there is nothing on the page except a click handler and a QRL
https://github.com/thejackshelton/prefetching-world-repro

It seems to be a bug in the new service worker implementation, and possibly something to do with Qwik City. 

I'll look more into the implementation 🫡

**Comment by wmertens** [comment]
confirmed fixed with #6853

**Comment by DustinJSilk** [comment]
Amazing, looking forward to getting these changes to production soon. Thanks @wmertens

**Comment by shairez** [comment]
@DustinJSilk now that 1.9 is out, can you please check if it solved the issue?

Thanks!

**Comment by DustinJSilk** [comment]
This looks to be solved now with the reproduction repo.
I'll get this added to my app this week to see how it performs.
Thanks for getting this done, everyone!
