### ISSUE TITLE
[🐞] An unknown symbol is fetched in preview which returns a 404 with the PrefetchServiceWorker

### ISSUE THREAD

**Issue by DustinJSilk** [QwikDev/qwik#6605]
### Which component is affected?

Qwik Runtime

### Describe the bug

When running a preview build when using a Link component, qwik attempts to prefetch a symbol which doesn't exist.
![Screenshot 2024-06-25 at 12 49 42](https://github.com/QwikDev/qwik/assets/5979984/cb147dc3-5ee4-4d50-bca3-b4f1064dabf1)

### Reproduction

https://github.com/DustinJSilk/qwik-prefetch-missing-symbol

### Steps to reproduce

`$ pnpm i`

`$ pnpm preview`

See 404 error in the browser for file `/build/q-Bq36Wx9q.js`. This only exists when using the Link component.

### System Info

```shell
n/a
```

**Comment by gioboa** [comment]
I tested the repo locally and the missing bundle it's in the graph but there is no actual file for that.
So the graph file is wrong.

**Comment by gioboa** [comment]
This is the old service worker, we need to remove it from the graph.

**Comment by gioboa** [comment]
With the new PrefetchServiceWorker you need to remove the `src/routes/service-worker.ts` file from your project because it's the old way to install the SW. This will solve the 404 issue.
