### ISSUE TITLE
[✨] Qwik is great! Please make more videos tutorial for 2.0 or something.

### ISSUE THREAD

**Issue by sprappcom** [QwikDev/qwik#6639]
### Is your feature request related to a problem?

too few tutorials online.

### Describe the solution you'd like

maybe can do 2.0 tutorial after 2.0 comes out or before it's officially out.

### Describe alternatives you've considered

too few video tutorials online

**Comment by gioboa** [comment]
Thanks for the feedback. We are looking for content creators that help us to produce videos and tutorials. We are centralising this kind of discussions in our [Discord server](https://qwik.dev/chat)
so I close this issue here and I'm looking forward to continue the discussion there. Thanks
