### ISSUE TITLE
[✨] Discussion tab too for discussion, how to have integration of qwik with customized server backend / nginx? 

### ISSUE THREAD

**Issue by sprappcom** [QwikDev/qwik#6640]
### Is your feature request related to a problem?

1. can we have discussion tab?
2. how to have qwik integration with "nginx" or customized golang backend?

### Describe the solution you'd like

as mentioned

### Describe alternatives you've considered

none

**Comment by gioboa** [comment]
Hi @sprappcom thanks for opening this.
we have a [discord server](https://qwik.dev/chat) for this kind of support.
So I close this issue and I am looking forward to answering you there. Thanks
