### ISSUE TITLE
[🐞] Failed to fetch dynamically imported module: `http://localhost:5174/..../@builder.io/qwik-react/lib/usewakeupsignal_activate_6lyztwgzxaa.js?_qrl_parent=index.qwik.mjs`

### ISSUE THREAD

**Issue by wanjohiryan** [QwikDev/qwik#6665]
### Which component is affected?

Qwik React

### Describe the bug

I am trying out the latest `qwik` and `qwik-city` version 1.7.0 together with `qwik-react` with reference to this issue #6619 

After creating a new project with `pnpm create qwik@latest`. I just installed the `qwik-react` boilerplate using `pnpm qwik add react`, then navigated to `localhost:5174/react` to check out the Mui slider.

That is where I am getting this error.
```js
Failed to fetch dynamically imported module: http://localhost:5174/node_modules/.pnpm/@builder.io%2Bqwik-react@0.5.0_@builder.io%2Bqwik@1.7.0_@types%2Bnode@20.14.10_undici@6.19.2__@type_n7pyegryyqmds23w7jledjesou/node_modules/@builder.io/qwik-react/lib/usewakeupsignal_activate_6lyztwgzxaa.js?_qrl_parent=index.qwik.mjs
```

And if i ignore and close the error, the Mui slider does not work at all.

### Reproduction

none

### Steps to reproduce

1. `pnpm create qwik@latest`
2. `pnpm qwik add react`
3. Navigate to `http://localhost:5174/react`
4. Close the error, try interacting with the MUI slider.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (2) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 2.04 GB / 5.79 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
    pnpm: 9.4.0 - ~/.local/share/pnpm/pnpm
    bun: 1.1.18 - ~/.bun/bin/bun
  npmPackages:
    @builder.io/qwik: ^1.5.7 => 1.7.0
    @builder.io/qwik-city: ^1.5.7 => 1.7.0
    @builder.io/qwik-react: 0.5.0 => 0.5.0
    typescript: 5.4.5 => 5.4.5
    undici: * => 6.19.2
    vite: ^5.2.10 => 5.3.3
```

### Additional Information

Downgrading `qwik` and `qwik-city` down to `^1.5.7`, which was the stable version for me, is not working.

**Comment by DustinJSilk** [comment]
Im getting these errors a lot when updating to 1.7.0. 1.5.7 is the last working version for me

**Comment by nelsonprsousa** [comment]
Correct. Try 1.7.1 and let us know if you still find problems with this version.

**Comment by wanjohiryan** [comment]
Hey, `v1.7.1` does solve the issue for me.

Thanks. Marking this as resolved :)
