### ISSUE TITLE
[🐞] Unability to change chunkFileNames with vite.build.rollupOptions.chunkFileNames

### ISSUE THREAD

**Issue by maiieul** [QwikDev/qwik#6673]
### Which component is affected?

Qwik Runtime

### Describe the bug

I believe this was introduce in #6588 @gioboa

In previous versions, I was able to add 
```tsx
  let output: any = {};
  if (!isDev) {
    // Client-specific configuration
    output = {
      // Customize the client build structure
      entryFileNames: ({ name }: any) => {
        if (name.startsWith('entry')) {
          return '[name].js';
        }
        return `build/[name]-[hash].js`;
      },
      chunkFileNames: () => {
        return `build/[name]-[hash].js`;
      },
      assetFileNames: `build/[name]-[hash].[ext]`,
    };
  }
  ```
  in a vite.config
  
  with 
  
  ```tsx
      build: {
      rollupOptions: {
        output,
      },
    },
```

But now when running preview with it,
    
I get
   > x Build failed in 5.55s
TypeError [PLUGIN_ERROR]: [vite-plugin-qwik-post] The "path" argument must be of type string. Received function chunkFileNames
    at Object.dirname (node:path:1279:5)
    at Object.handler (/Users/maieul/dev/qwik-ui/node_modules/.pnpm/@builder.io+qwik@https+++pkg.pr.new+@builder.io+qwik@7fdea60_@types+node@20.12.12_sass@1.77.4_v2qpm4luyvgabz4seeshjuuzrq/node_modules/@builder.io/qwik/optimizer.cjs:3561:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'PLUGIN_ERROR',
  pluginCode: 'ERR_INVALID_ARG_TYPE',
  plugin: 'vite-plugin-qwik-post',
  hook: 'generateBundle'
}

### Reproduction

https://github.com/qwikifiers/qwik-ui

### Steps to reproduce

- Go to apps/website/vite.config.ts
- Uncomment comments
- Run preview

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 80.64 MB / 24.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 22.2.0 - /opt/homebrew/bin/node
    npm: 10.7.0 - /opt/homebrew/bin/npm
    pnpm: 9.5.0 - /usr/local/bin/pnpm
    bun: 1.1.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
```

### Additional Information

I believe this is caused in packages/qwik/src/optimizer/src/plugins/vite.ts either by removal of 

```tsx
output: normalizeRollupOutputOptions(
            path,
            )
```
line 337

or type casting in
```tsx
          const filePath = sys.path.dirname(_.chunkFileNames as string);
```
line 564

**Comment by maiieul** [comment]
If it's not possible to fix without introducing complexity or fragility in the codebase, perhaps we can provide an option on the qwikVite plugin for the users to change the chunk files names in preview.

**Comment by gioboa** [comment]
Thanks @maiieul  for the feedback. 
Would you like to create a PR for that?
