### ISSUE TITLE
[🐞] in dev mode, ignore dist/

### ISSUE THREAD

**Issue by wmertens** [QwikDev/qwik#6677]
### Which component is affected?

Qwik Runtime

### Describe the bug

When running in dev mode, and there's a stale dist/ folder with SSG files in there, those files get served.

In dev, only public/ should be served.

### Reproduction

not yet

### Steps to reproduce

drive by issue creation, no repro, could be just an issue with this proprietary repo

### System Info

```shell
macos with latest qwik
```

**Comment by thejackshelton** [comment]
@yousefmarey12 is working on this
