### ISSUE TITLE
[🐞] unocss no work when bun run serve

### ISSUE THREAD

**Issue by lontten** [QwikDev/qwik#6691]
### Which component is affected?

Qwik Runtime

### Describe the bug

unocss can work when bun run dev,
but when bun run serve unocss no work

### Reproduction

https://github.com/lontten/d10

### Steps to reproduce

bun i
bun run build
bun run serve

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 8.93 GB / 31.82 GB
  Binaries:
    Node: 20.12.2 - d:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - d:\Program Files\nodejs\npm.CMD
    pnpm: 9.0.6 - d:\Program Files\nodejs\pnpm.CMD
    bun: 1.1.20 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (126.0.2592.102)
    Internet Explorer: 11.0.22621.3527
```

**Comment by lontten** [comment]
when serve No request  http://localhost:5173/__uno.css
No error message printed

**Comment by shairez** [comment]
Thanks for the report @lontten !

@hypecode-tech we like to keep things friendly in our community, so please edit your message to adhere to our [community values](https://docs.google.com/document/d/1MrSp2caaREETHUL56C2fIIJeFJsBA_sWJ9raL6hWoo8/edit#heading=h.bpbzghkvfgrn), thanks.

**Comment by wmertens** [comment]
@lontten do you mean that it's not requesting __uno.css? That is expected, it should be part of the global.css file. Vite bundles all css imports into a single file.

**Comment by lontten** [comment]
no request css file
## dev
![image](https://github.com/user-attachments/assets/d26d9bbb-192b-4264-9f68-d1e50ad2f5a0)
## serve
![image](https://github.com/user-attachments/assets/62fb3a94-7990-40b4-92b1-c6e722ae7bf0)

**Comment by lontten** [comment]
[right way](https://github.com/unocss/unocss/tree/main/examples/qwik)

**Comment by gioboa** [comment]
Thanks for the update 👍
