### ISSUE TITLE
[🐞] Incorrect starting value of select tag with bind:value

### ISSUE THREAD

**Issue by dolsem** [QwikDev/qwik#6712]
### Which component is affected?

Qwik Runtime

### Describe the bug

When using `bind:value` with a select tag, the value of the select is always the first option on initial render, regardless of the value of the signal passed to it.

### Reproduction

https://stackblitz.com/edit/qwik-starter-svqtlv?file=src%2Fcomponents%2Fselect-example.tsx

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @builder.io/qwik: ^1.4.3 => 1.4.3 
    @builder.io/qwik-city: ^1.4.3 => 1.4.3 
    typescript: 5.3.3 => 5.3.3 
    undici: 5.28.2 => 5.28.2 
    vite: 4.5.2 => 4.5.2
```

**Comment by thejackshelton** [comment]
Hey @dolsem! I believe this is how the native select html tag works, the first rendered `option` element is always the "selected value". 

To get around this you could make sure the selectedLabel is the first option in the list, but I would recommend avoiding the native select element and using Qwik UI's headless select instead. It's easier to style, consistent across platforms, and also has the desired behavior mentioned in this issue.

**Comment by dolsem** [comment]
@thejackshelton I don't think that's the case, see here - https://stackblitz.com/edit/web-platform-65elzw?file=index.html

Thank you for the suggestion. I haven't switched to Qwik UI yet because it seems to be in a pretty early phase.

**Comment by thejackshelton** [comment]
You're using the `selected` attribute, which specifically changes the initial selected value on page load with the native html select element. If you remove this attribute, then it will always select the first rendered option element.

For example:

```tsx
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Home</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <!--
      Need a visual blank slate?
      Remove all code in `styles.css`!
    -->
    <link rel="stylesheet" href="styles.css" />
    <script type="module" src="script.js"></script>
  </head>
  <body>
    <select>
      <option value="b">Option B</option>
      <option value="a">Option A</option>
    </select>
  </body>
</html>

```

This will select option B.

There are many pitfalls and usability issues with the native select, the open ui group acknowledges this and has been working on a proposal. It is why I created the headless select in Qwik UI
https://qwikui.com/docs/headless/select/#select

There is more you can do here than with the native alternative.

**Comment by dolsem** [comment]
Hmm so I've just tried using `selected` in my Qwik code and it seems to be working. Coming from React, I assumed this was not the right way. I'll close the issue.

As for Qwik UI, I'll definitely switch to it eventually, I'm just waiting on a stable release.
