### ISSUE TITLE
[🐞] @auth/qwik package does not correctly register routes

### ISSUE THREAD

**Issue by cwoolum** [QwikDev/qwik#6729]
### Which component is affected?

Qwik Runtime

### Describe the bug

When trying to use the `@auth/qwik` package, routes are not getting registered which causes auth redirects to fail with the error `/api/auth/signin` not found.

![image](https://github.com/user-attachments/assets/b1e00655-bd98-4b38-989a-9070a247f2e9)

### Reproduction

https://stackblitz.com/edit/qwik-starter-7tnnx2

### Steps to reproduce

1. Create a new Qwik app
2. Add auth
3. Convert to using `@auth/core` instead of `@builder.io/qwik-auth` in `plugin@auth.ts`.
4. Add an onRequest handler to redirect if a user is unauthenticated

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @auth/core: ^0.13.0 => 0.13.0 
    @auth/qwik: ^0.2.2 => 0.2.2 
    @builder.io/qwik: ^1.4.3 => 1.4.3 
    @builder.io/qwik-auth: 0.1.1 => 0.1.1 
    @builder.io/qwik-city: ^1.4.3 => 1.4.3 
    typescript: 5.3.3 => 5.3.3 
    undici: 5.28.2 => 5.28.2 
    vite: 4.5.2 => 4.5.2
```

**Comment by cwoolum** [comment]
Dug a bit deeper and as per the [source](https://github.com/nextauthjs/next-auth/blob/main/packages/frameworks-qwik/src/index.ts#L153), the auth routes no longer live under `/api`. I'll get a PR up to fix the docs.

**Comment by gioboa** [comment]
Thanks @cwoolum nice catch 
The basePath is `auth/` [here is the code](https://github.com/nextauthjs/next-auth/blob/main/packages%2Fframeworks-qwik%2Fsrc%2Findex.ts#L335)
I'm looking forward to merging your PR
