### ISSUE TITLE
[🐞] SPA reload randomly fails to update the values loaded by the `routeLoader$`

### ISSUE THREAD

**Issue by genki** [QwikDev/qwik#6789]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I am making app that uses `routeLoader$` for loading dynamic data.
I found the SPA reload sometimes fails to update the data like this.

https://github.com/user-attachments/assets/a88f5efb-625d-4b67-8c1f-c87978e3cc29

Note that the 3rd reload (around 0:07 at the video) trigger the call of the route loader and logged the count at server side but doesn't change the values in client side.
The next click updates the values but doesn't trigger the call.

I expected the each reload can update the value.

### Reproduction

https://github.com/genki/qtest

### Steps to reproduce

Please clone the repo above and
```sh
pnpm i
pnpm run dev
```
then open `http://localhost:5173/`

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 117.77 MB / 24.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.12.1 - /opt/homebrew/opt/node@20/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - /opt/homebrew/opt/node@20/bin/npm
    pnpm: 9.6.0 - ~/Library/pnpm/pnpm
    bun: 1.1.21 - ~/.bun/bin/bun
  Browsers:
    Chrome: 127.0.6533.101
    Safari: 17.5
  npmPackages:
    @builder.io/qwik: ^1.8.0 => 1.8.0 
    @builder.io/qwik-city: ^1.8.0 => 1.8.0 
    typescript: 5.4.5 => 5.4.5 
    undici: * => 6.19.5 
    vite: ^5.2.10 => 5.3.5
```

### Additional Information

Interestingly, this behaviour doesn't occur at the stackbliz.
https://stackblitz.com/edit/github-ahtxgw?file=src%2Froutes%2Findex.tsx

**Comment by genki** [comment]
This issue is not only when the reload but for when SPA navigation too.

**Comment by genki** [comment]
As the @auth/qwik using the `routeLoader$` inside to load the session information, this issue causes a vulnerabilities.
If an user has done `signOut` and navigated to another page by SPA navigation, the old session data randomly remains. So another user can see the previous user's private data if they share the same machine.

**Comment by genki** [comment]
I found that the problem is solved if I checked the "Disable cache" at the devtools.
It means the dynamic q-data.json is unexpectedly cached (besides, it happens randomly).
The reason of this issue may be around the `loadClientData`

**Comment by lontten** [comment]
"@builder.io/qwik": "^1.9.0",
 "@builder.io/qwik-city": "^1.9.0",
    
This issue has arisen again.
q-data.json is unexpectedly cached
the problem is solved if checked the "Disable cache" at the devtools.

**Comment by wmertens** [comment]
@lontten can you check the headers that the browser received for the q-data.json? And please specify your environment, SSG or not, anything that could impact the caching

**Comment by lontten** [comment]
access-control-allow-origin:
*
cache-control:
max-age=5, stale-while-revalidate=604800
content-type:
application/json; charset=utf-8
date:
Fri, 04 Oct 2024 12:58:18 GMT
server-timing:
useServerTimeLoader;dur=0.2779999999984284,useBook;dur=92.89895899999829

**Comment by lontten** [comment]
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M1
    Memory: 95.77 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    pnpm: 9.11.0 - ~/.nvm/versions/node/v20.17.0/bin/pnpm
    bun: 1.1.29 - ~/.bun/bin/bun
  Browsers:
    Edge: 129.0.2792.79
    Safari: 18.0
    
    
  env:  bun run dev

**Comment by lontten** [comment]
![videoframe_13643](https://github.com/user-attachments/assets/c9588217-1382-43f2-945f-89cc108fc51c)

**Comment by lontten** [comment]
https://github.com/user-attachments/assets/412656b4-8f72-42ac-8885-82c43b13ac56

**Comment by wmertens** [comment]
@lontten `cache-control:
max-age=5` tells your browser to cache it...

**Comment by lontten** [comment]
@wmertens 
why cache 5s

doc show

Route Loaders are executed on the server, after every navigation. This means that they are executed every time a user navigates to a page in an SPA or MPA, and they are executed even if the user is navigating to the same page.

they are executed every time.

**Comment by lontten** [comment]
I found the cache cofig is layout.tsx > onGet > cacheControl

web page show the cache
but, the routeLoader$  still be executed,The caching feature in routeLoader is meaningless and also results in error displays.

**Comment by wmertens** [comment]
@lontten it's not useless, it depends on the use case. Sometimes you need caching, sometimes not

**Comment by lontten** [comment]
I mean, when  caching, the routeLoader$ still called the API and obtained the data, so it didn't reduce the pressure on the API server.

**Comment by wmertens** [comment]
Ah that's because of `stale-while-revalidate=604800`. So the bug is that qwik should somehow detect this and use the new data when it comes in. Can you open an issue?

**Comment by wmertens** [comment]
Qwik could fetch from cache only first and then with default settings. If the data changes it will update reactively
