### ISSUE TITLE
Fix attribute changing with ternary operator in v2

### ISSUE THREAD

**Issue by wmertens** [QwikDev/qwik#6842]
There is a bug in v2 in the optimizer when attribute with signal and ternary operator is not wrapped in `fnSignal`

```tsx
const Cmp = component$(() => {
  const toggleSig = useSignal(false);

  const handleClick$ = $(() => {
    toggleSig.value = !toggleSig.value;
  });

  return (
    <button onClick$={handleClick$} data-open={toggleSig.value ? true : undefined}>
      Removing data-open re-renders
    </button>
  );
});
```

https://qwik.dev/playground/#f=Q0o0xmaW2BKNDqL21VGgPAlBwqMkPz09B2QqMFDgxmukJeYUpwLdBVeWASyFc1Ih1StQJbI5Cggz9IBZEVjI2ioooglZA9WBEiZGeEOaMIiauxrZolpwPa8LrIrzbKvRLbGHFOhWCsDKJjUNWOal1MKCOCg1F5g3gW0WuHagrbqQNFUMDXho2wka%2FKN5ZkjmGQA

**Comment by JerryWu1234** [comment]
I can take a look ,if this isn't Rust problem
