### ISSUE TITLE
`tsm` is no longer supported

### ISSUE THREAD

**Issue by wmertens** [QwikDev/qwik#6856]
### Is your feature request related to a problem?

[we can't update vfile](https://github.com/vfile/vfile/issues/90) because `tsm` doesn't support its import map.

### Describe the solution you'd like

We're only using tsm for builds, so we can easily replace it.

### Describe alternatives you've considered

use tsnode, or maybe via some small build we don't need anything?

**Comment by wmertens** [comment]
@JerryWu1234 yes that would be great, thank you ☺️

**Comment by shairez** [comment]
fixed by #6877 
Thanks @JerryWu1234 !
