### ISSUE TITLE
[🐞] Qwik 1.9.0 holds onto searchParams when redirecting from a server action

### ISSUE THREAD

**Issue by brandonpittman** [QwikDev/qwik#6926]
### Which component is affected?

Qwik City (routing)

### Describe the bug

Through 1.8.0, our app would successfully redirect from server actions to some URL like `/profile` from the front page of the app. The front page takes an `?id=XXX` param to get some data and then after tapping a consent button, it runs an action, saves data to a cookie and throws a redirect.

It used to drop the search params when redirecting. Since 1.9.0, it holds onto the search params. 

### Reproduction

https://stackblitz.com/edit/github-cv95eb?file=src%2Froutes%2Findex.tsx

### System Info

```shell
System:
    OS: macOS 15.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 63.16 MB / 16.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.20.3 - ~/Library/pnpm/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 10.7.0 - ~/Library/pnpm/npm
    pnpm: 9.4.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 129.0.6668.60
    Safari: 18.1
    Safari Technology Preview: 18.0
  npmPackages:
    @builder.io/qwik: 1.9.0 => 1.9.0
    @builder.io/qwik-city: 1.9.0 => 1.9.0
```

**Comment by brandonpittman** [comment]
Seems related to this:

https://github.com/QwikDev/qwik/pull/6778/files#diff-6c570481bf47bb1dae75e8d12166dc67e7ed94954b9714816b7378813b20a24d

But if this is what the team thinks should be the correct behavior, how can I drop the searchParams?

**Comment by wmertens** [comment]
@brandonpittman can you provide a repro so we're talking about the same things? I thought that change was to provide search parameters when calling actions?

**Comment by brandonpittman** [comment]
@wmertens 

The repro link above shows this behavior:

if you submit a form from a page with searchParmas and redirect in the action, the page you get redirected to has the previous page’s searchParams even though the redirect was to a route with no searchParams.

**Comment by brandonpittman** [comment]
@wmertens Just for completeness, here's another Stackblitz pinned at 1.8.0 where redirects don't hold onto the submitting page's searchParams.

https://stackblitz.com/edit/github-cv95eb-7l9fik?file=package.json

**Comment by thejackshelton** [comment]
Just to confirm, it's holding the search params of the old page after the redirect?

**Comment by brandonpittman** [comment]
Pretty sure this is what broke things:

https://github.com/QwikDev/qwik/pull/6778

**Comment by brandonpittman** [comment]
@thejackshelton 

If I submit a PR, do I need to fix the regression while leaving the commit that broke it in the first place in-place?

**Comment by brandonpittman** [comment]
Another problem is that if you redirect to a URL with searchParams, Qwik drops the params in the URL you try to redirect to.

**Comment by brandonpittman** [comment]
I started a PR that confirms that a change in 1.9.0 broke this functionality. Merely commenting the change out restores the original functionality. 

https://github.com/QwikDev/qwik/pull/6927

Can we just revert the bad PR or do I need to rewrite the original PR that broke the existing functionality while preserving the original PR's intent?

**Comment by brandonpittman** [comment]
I created a PR. Can someone take a look at it, please?
