### ISSUE TITLE
[🐞] Components that have an async task causes crash if it is passed via params.

### ISSUE THREAD

**Issue by genki** [QwikDev/qwik#6928]
### Which component is affected?

Qwik Runtime

### Describe the bug

I found some components are doing strange behavior when they have async `useTask$` and some conditions are met.
Finally I could sculpt a reproduction code like this:

```tsx
import { component$, createContextId, JSXOutput, Signal, useContext, useContextProvider, useSignal, useTask$, useVisibleTask$ } from "@builder.io/qwik";

const CounterCtx = createContextId<Signal<number>>("counter");

const Foo = component$(() => {
  const counter = useContext(CounterCtx);
  const label = useSignal(0);
  useTask$(async ({track}) => {  // <- (1) the async task
    const count = track(() => counter.value);
    label.value = count + 1;
  })
  return <>{counter}</>;
})

type BarProps = {
  foo:JSXOutput
}
const Bar = component$(({foo}:BarProps) => {
  return <div>
    <span>Bar</span>
    <div style={{display:"none"}}>
    {foo}
    </div>
  </div>
});

export default component$(() => {
  const counter = useSignal(0);
  useContextProvider(CounterCtx, counter)
  useVisibleTask$(() => {
    setInterval(() => counter.value++, 1000); // (2) the task will be triggered by a visual task
  })
  const foo =<Foo/>;  // (3) The component is passed via params.
  return (
    <>
      Test
      <Bar foo={foo}/>
    </>
  );
});
```

The conditions are commented in the source code above.
When those 3 conditions are met, the dev server crushes.

### Reproduction

https://stackblitz.com/edit/github-wtmvpz?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

Please visit the link above and see the crash.
And change the async task to synchronous task by removing `async` to see again it would not crash.

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M2
    Memory: 84.63 MB / 24.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.12.1 - /opt/homebrew/opt/node@20/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - /opt/homebrew/opt/node@20/bin/npm
    pnpm: 9.11.0 - /opt/homebrew/bin/pnpm
    bun: 1.1.26 - ~/.bun/bin/bun
  Browsers:
    Chrome: 129.0.6668.70
    Safari: 17.6
  npmPackages:
    @builder.io/qwik: file:../clone/qwik/packages/qwik => 1.9.0 
    @builder.io/qwik-city: file:../clone/qwik/packages/qwik-city => 1.9.0 
    typescript: ^5.3.3 => 5.3.3 
    undici: ^5.28.4 => 5.28.4 
    vite: ^5.3.3 => 5.3.3
```

**Comment by wmertens** [comment]
Thank you for the repro!

It seems like this is working in V2, can you verify? 

https://qwikdev-build-v2.qwik-8nx.pages.dev/playground/#f=7VY9S8RAEO3vVwypEi6eOcXCM5fCA0EbCy1sE4hgIQn5ECXsf%2FfNzO5lWSPYCtctyczO7ry3b55Pmuzqeok1aUi1lB6eXh7HAZxOSedy6lHUXzu6yjcvVMRRVr5aOiyjEPsI%2FdRGHlj%2F6%2B4wfKKd4ROwHkEHT1HEkUyLuotwV5t%2F1zScuERuDbApCPIe4FwVO7lInWkSp4XjTP4ePYWqXjxZn2C0EhEGYH5G8TaRMatRAzIEHO8U2Fsy7RntyTYQnrGWSqRn0C9yLc5a05Z%2FmsR7sMVksw3A59e6WsnTuy07QNT2SOYWvDbNbgYXfNfTICpo2sShZHbHDX5IBLtFZRv7uwJx%2Bbms9CN%2BO6s1sS1pMUt2FFU8bCMyxvF2Qh1jWWu3tAtWnD%2BJ1gKuIV6huM54g%2Fy65m6Gw32uQeyN7jkOWCzhtV6ntM0yVGT44wvFnlGHecDkrth9vcGkdHBn1ReVsBP9CFdgiSFo6k2483vKmcnAUugUXyYyP2fDhIHawpdjsw84PXiF8r3f%2FKo7z%2FBGTigYbJTYS%2BedgMySkdycZP7%2Fyfw3

**Comment by genki** [comment]
@wmertens Yes, it seemed working in V2.
Then switched the version to 1.9, the error occurred as expected.

**Comment by wmertens** [comment]
Excellent! So I'll close this

**Comment by genki** [comment]
@wmertens Now we have to use V2?

**Comment by wmertens** [comment]
@genki well we didn't release it yet, but this bug is fixed there and it can be worked around in V1? 
It looks like a very intricate bug, so we won't spend time in on fixing it in V1.

**Comment by genki** [comment]
＠wmertens Yeah, I am really looking forward to the V2 released.
