### ISSUE TITLE
[📖] Please do not override JS common stuff

### ISSUE THREAD

**Issue by Nefcanto** [QwikDev/qwik#6929]
### Suggestion

In the [route loaders](https://qwik.dev/docs/route-loader/) page it's specified that:

> Route Loaders can only be declared inside the src/routes folder, in a layout.tsx or index.tsx file, and they MUST be exported.

Please don't override JS common practices. What if somebody wants to reuse a route loader across multiple index or layout files?

It's common in JS to break code into modules. Please don't prevent developers from defining a `blogLoader` in a separate file, and import/export it into `/blog/index.jsx` and `/post/index.jsx` files.

Please fix the aforementioned part of the documentation.

**Comment by JerryWu1234** [comment]
Could you please give me more clues how to fix it ?

**Comment by Nefcanto** [comment]
@JerryWu1234, that message can be changed to something like this:

> Please note that route loaders should be exported only from layouts or index files. But they can be declared in any valid way ES modules allow. To reuse a route loader across multiple layout or index files, define it in a separate file, export it, then import it in layout or index files and re-export it as a named export.
