### ISSUE TITLE
Page gets slow

### ISSUE THREAD

**Issue by mightyplow** [QwikDev/qwik#7005]
Hi,
this maybe is not a real issue but while investigating qwik I stumbled upon something I would like to ask about whether this is a framework issue or not.
When going to https://qwik.dev/docs/middleware/ in Chrome on Linux and scrolling around the page, I can easily recognize a huge slowdown of the scrolling. At first, the page and the scrolling is very fluffy but after some scrolling to the end of the page and back up and down again ... the scrolling loses all it's fluffiness.
I can recognize this behaviour on nearly all pages in the docs but it's easier to see on very long pages.
Is this an inherent behaviour in the framework itself or is this only related to the way the docs are build up?

**Comment by wmertens** [comment]
Can't reproduce this on Linux+Wayland+Chrome 130. Maybe it's an extension? Can you try this in a new profile or incognito page?

When looking at the devtools, the only DOM breakpoint for scroll is qwikloader.

**Comment by mightyplow** [comment]
okay thank you. I already tried it in an incognito tab but I will try again with all extensions disabled.
