### ISSUE TITLE
[🐞] v2: doesn't handle missing/added fragments well

### ISSUE THREAD

**Issue by wmertens** [QwikDev/qwik#7033]
### Which component is affected?

Qwik Runtime

### Describe the bug

when vnodes are tree shaken, or a component returns a fragment where there wasn't any, the consolidation of jsx output vs existing vnodes will recreate existing vnodes instead of moving them inside the fragment.

### Reproduction

in varixo's head ;)

### System Info

```shell
v2
```

**Comment by Varixo** [comment]
fixed by https://github.com/QwikDev/qwik/pull/6963
