### ISSUE TITLE
[🐞] Removing in a list of input remove the last input

### ISSUE THREAD

**Issue by GrandSchtroumpf** [QwikDev/qwik#7047]
### Which component is affected?

Qwik Runtime

### Describe the bug

When working with a list of input bound to a `useStore` removing one item from the list always remove the last 
```jsx
export default component$(() => {
  const form = useStore<{ list: string[] }>({
    list: [],
  });
  return (
    <form>
      <ul>
        {form.list.map((_, i) => (
          <li key={i}>
            <input value={form.list[i]} />
            <button type="button" onClick$={() => form.list.splice(i, 1)}>
              Remove
            </button>
          </li>
        ))}
      </ul>
      <button type="button" onClick$={() => form.list.push('')}>
        Add
      </button>
    </form>
  );
});
```
I believe the error comes from `key={i}`. We cannot use the value as a `key` as it would rerender on each keystrike and would unfocus.

### Reproduction

https://stackblitz.com/edit/github-dmhnex?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

1. Click on "Add" multiple time
2. Enter different values in each input
3. Click on "Remove" in one of the input (except the last one)
4. The last input has been remove instead of the one you clicked on

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 7950X3D 16-Core Processor
    Memory: 18.06 GB / 31.18 GB
  Binaries:
    Node: 22.8.0 - ~\.nvm\versions\node\v22.8.0\bin\node.EXE
    npm: 10.9.0 - ~\.nvm\versions\node\v22.8.0\bin\npm.CMD
    pnpm: 9.12.2 - ~\.nvm\versions\node\v22.8.0\bin\pnpm.CMD
  Browsers:
    Edge: Chromium (129.0.2792.65)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @builder.io/qwik: https://pkg.pr.new/@builder.io/qwik@f72fda5 => 1.10.0
    @builder.io/qwik-city: https://pkg.pr.new/@builder.io/qwik-city@f72fda5 => 1.10.0
    typescript: 5.4.5 => 5.4.5
    undici: * => 6.20.0
    vite: 5.3.5 => 5.3.5
```

**Comment by JerryWu1234** [comment]
I'll  take a look

**Comment by JerryWu1234** [comment]
@GrandSchtroumpf 
```js
<input value={form.list[i]} onInput$={(_, el) => (form.list[i] = el.value)} />
```

Please adding this code.

You've just input a value, and you also need to assign a value to `form.list[i]`. otherwise the each item of `form.list` is empty

**Comment by GrandSchtroumpf** [comment]
@JerryWu1234 Ok it works now. So each input must have a different value. I find it weird to set the value attribute on the input while it's already has the value internaly. It requires an unnecessary additional DOM operation.

I'll close it because it works. Thanks for the advice

**Comment by JerryWu1234** [comment]
> @JerryWu1234 Ok it works now. So each input must have a different value. I find it weird to set the value attribute on the input while it's already has the value internaly. It requires an unnecessary additional DOM operation.
> 
> I'll close it because it works. Thanks for the advice

Other framework actually is same behavior. i think

**Comment by GrandSchtroumpf** [comment]
@JerryWu1234 I'm reopening this issue because there is still a bug. 
If you create an Input proxy component the expected behavior is not working : 
```tsx
// Simple component that forward the props
const Input = component$<PropsOf<'input'>>((props) => {
  return <input {...props} />
});
export default component$(() => {
   const store = useStore({ list: [] });
   return (
     <ul>
       {store.list.map((group, i) => (
         <li key={i}>
           {/* Not working with <Input />, but working with <input /> */}
           <Input value={group.key} onInput$((e, input) => group.key = input.value} />
           <Input value={group.value} onInput$((e, input) => group.value = input.value} />
           <button onClick$={() => store.list.splice(i, 1)}>Remove</button>
         </li>
       )}
     </ul>
     <button onClick={() => store.list.push({ key: '', value: '' })}>Add</button>
   )
})
```

I've updated the code of my exemple: https://stackblitz.com/edit/github-dmhnex?file=src%2Froutes%2Findex.tsx

**Comment by JerryWu1234** [comment]
![image](https://github.com/user-attachments/assets/bd4899f2-3bae-4293-854b-23cee4b62d8e)
try this

**Comment by JerryWu1234** [comment]
`value={group?.key}`

**Comment by JerryWu1234** [comment]
@GrandSchtroumpf mentioned in  doc

**Comment by GrandSchtroumpf** [comment]
@JerryWu1234 sorry for the delay. It works indeed in a simple example but it doesn't on my form library. I'm trying to pinpoint where it come from and update the demo. I'm going to close this issue for now and reopen later if I'm able to reproduce at a small scale.

**Comment by wmertens** [comment]
@GrandSchtroumpf additionally, by using key=i and then removing an array item, you're specifically saying that it should remove items from the tail.

You need to use a consistent id if you want this to work correctly. 

For example, you could leave the array item be null and that would mean it is deleted.

**Comment by GrandSchtroumpf** [comment]
I understand that key need to be unique. But when working with a dynamic list of inputs there is nothing unique about each item except their index. Changing the value of the input on each keydown but it's an unnecessary amount of rendering also it breaks native property like the reset event that uses the value attribute as reference for the initial value.

**Comment by wmertens** [comment]
I think you have to keep track of the IDs with a separate array of IDs then

**Comment by GrandSchtroumpf** [comment]
Hmmm that doesn't feels right. It means having one additional state per array and sub arrays. Plus the extra work of updating them on each update.
Ideally the forms should be able to match the state without any extra data. At least that's how I've been working with form with all the other frameworks.

**Comment by wmertens** [comment]
So it looks like using values to differentiate inputs works or what?

The problem is that there's hidden state in inputs that must be preserved, and if you just use the index as a key, then a whole bunch of inputs will be changed to get the value and callback of their neighbor, losing the internal state.

If all of the items have different values, then the framework might be able to figure out what's what, but when it's all the same it will make mistakes.

The additional state is simply state that's already additional, namely the index, and you're messing with that state by splicing the array.

Instead, either never shrink the array or add unique ids to each item.
