### ISSUE TITLE
[🐞] Can't build with bun

### ISSUE THREAD

**Issue by svi3c** [QwikDev/qwik#7051]
### Which component is affected?

Qwik Optimizer (rust)

### Describe the bug

I want to build with bun.
When I run `bun -b build` or `bun -b preview`, it builds fine, but I get an error when running the built app.
![image](https://github.com/user-attachments/assets/7d9c68d1-0c1b-40bb-a4f9-228cc830e16f)

### Reproduction

https://qwik.dev/docs/getting-started/#create-an-app-using-the-cli

### Steps to reproduce

1. Create a qwik app via `bun create qwik@latest`
2. Within the app directory run `bun -b preview`

### System Info

```shell
System:
    OS: macOS 15.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 214.89 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    Yarn: 4.1.1 - ~/.volta/bin/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    bun: 1.1.34 - ~/.bun/bin/bun
  Browsers:
    Chrome: 130.0.6723.117
    Safari: 18.1
  npmPackages:
    @builder.io/qwik: ^1.9.1 => 1.9.1
    @builder.io/qwik-city: ^1.9.1 => 1.9.1
    typescript: 5.4.5 => 5.4.5
    undici: * => 6.20.1
    vite: 5.3.5 => 5.3.5
```

### Additional Information

When building with NodeJS (having it installed and erasing the `-b` flag), it works.
But this way, I cannot use the Bun APIs at build / SSG time and I cannot build it in one go via my Bun monorepo.

**Comment by damianpumar** [comment]
After looking into it, I found that by removing this script, the compilation works correctly. Now, I need to understand what is happening.

https://github.com/QwikDev/qwik/blob/a1b44df6b21feec3e98b6c0c8ea582e1bcd82127/packages/qwik-city/src/runtime/src/router-outlet-component.tsx#L40C11-L59C21

**Comment by damianpumar** [comment]
@gioboa discovered that it works correctly with version `bun create qwik@2.0.0-alpha.1`. For this reason, I think we can close this issue, as version 2 will be released soon.

**Comment by gioboa** [comment]
@damianpumar Thanks for your help :clap:

**Comment by svi3c** [comment]
Great, thanks for your investigation, @damianpumar 
Now I'm even more excited about the 2.0 release :)
