### ISSUE TITLE
[🐞] v2: repl somewhat broken

### ISSUE THREAD

**Issue by wmertens** [QwikDev/qwik#7074]
### Which component is affected?

Qwik Playground

### Describe the bug

in v2 the repl no longer shows the html etc output tabs, and initial console logging seems broken too

### Reproduction

https://qwikdev-build-v2.qwik-8nx.pages.dev/playground

### Steps to reproduce

click on the html tab in the output panel

### System Info

```shell
browser
```

**Comment by Varixo** [comment]
Fixed by #7170 and #7171
