### ISSUE TITLE
[🐞] Vite error @qwik-router-not-found-path when migrating to v2

### ISSUE THREAD

**Issue by steffanek** [QwikDev/qwik#7131]
### Which component is affected?

Qwik Runtime

### Describe the bug

I've tried to migrate to v2 manually and I have a common qwik file to store qwik related function, components and types.
When importing for example Slot from this common file, I've noticed a vite error. 
See the repro in `src > routes > layout.tsx` where I explicitly do: `import { Slot } from '~/common/qwik';`

### Reproduction

https://stackblitz.com/edit/github-7ygh5v?file=src%2Froutes%2Findex.tsx,src%2Froutes%2Flayout.tsx,src%2Fcomponents%2Frouter-head%2Frouter-head.tsx,src%2Fcommon%2Fqwik.ts,src%2Fentry.ssr.tsx,src%2Fentry.preview.tsx,src%2Fentry.dev.tsx,tsconfig.json,vite.config.ts,src%2Froot.tsx

### System Info

```shell
ystem:
    OS: macOS 14.3
    CPU: (8) arm64 Apple M3
    Memory: 1.55 GB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.2.0 - /opt/homebrew/bin/node
    npm: 10.7.0 - /opt/homebrew/bin/npm
    pnpm: 9.7.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Safari: 17.3
  npmPackages:
    @builder.io/qwik: ^1.11.0 => 1.11.0
    @builder.io/qwik-city: ^1.11.0 => 1.11.0
    typescript: 5.6.3 => 5.6.3
    undici: ^6.21.0 => 6.21.0
    vite: 6.0.2 => 6.0.2
```

### Additional Information

As discussed today @wmertens, my feeling was right about the common/qwik causing it.

**Comment by gioboa** [comment]
@steffanek We should document that, would you like to contribute with a docs PR?
I think the right place could be [here](https://github.com/QwikDev/qwik/blob/9cdfc58762fc19375e49c9947a1c0dd1ac0d3d2f/packages/docs/src/routes/docs/(qwik)/advanced/vite/index.mdx?plain=1#L28) in the `build/v2/` branch. Thanks in advance :rocket:
