### ISSUE TITLE
[🐞] can't use qwik Devtools

### ISSUE THREAD

**Issue by JerryWu1234** [QwikDev/qwik#7153]
### Which component is affected?

Qwik Runtime

### Describe the bug

![image](https://github.com/user-attachments/assets/dda0575e-f602-46f4-a1ec-1b36f0391cb0)

### Reproduction

don't need 

### System Info

```shell
mac 
Chrome
```

**Comment by gioboa** [comment]
Hi @JerryWu1234 
we need to revamp our devtools because are the moment are unusable.
Would you like to collaborate on this?

**Comment by JerryWu1234** [comment]
> Hi @JerryWu1234 
> 
> we need to revamp our devtools because at the moment are unusable.
> 
> Would you like to collaborate on this?

I would like to do that. It would be great if could tell me more information

**Comment by byte-barista** [comment]
I have tried to create some kind of devtools similar to react-devtools. I think that we are too restricted currently. I was able to recreate a component tree with component ids (q:id) from HTML comments (), but I couldn't find a good way to get a component name. Also, I was able to track a state from useSignal$ through the qwik property on a container element (q:container) and object id from a HTML comment ()
![CleanShot 2024-12-14 at 15 38 13@2x](https://github.com/user-attachments/assets/56906726-a4ce-4b61-ac47-f6975ae2934d)

I'm not sure if this even is a proper way how we should get these things 😅

**Comment by gioboa** [comment]
Here is the [devtools repo](https://github.com/QwikDev/devtools)
We can start form scratch directly with V2.
The idea is to have a tool ( like the Nuxt one ) to configure Qwik ( enable/disable things ) , manage assets etc etc
You can reach me on Discord to discuss about it

**Comment by gioboa** [comment]
I close this issue because we are working on the new devtools, soon we will release the first version. Thanks
