### ISSUE TITLE
[🐞] Qwik removing nested form tag

### ISSUE THREAD

**Issue by GrandSchtroumpf** [QwikDev/qwik#7184]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

Nested <form> tags are removed from the template. In this example, the <form> inside a <dialog> element will not be in the final HTML ...
```tsx
export default component$(() => {
  const dialogId = useId();
  const open = $(() => {
    const dialog = document.getElementById(dialogId) as HTMLDialogElement;
    dialog.showModal();
  });
  return (
    <form preventdefault:submit>
      <button type="button" onClick$={open} aria-controls={dialogId}>
        Open Dialog
      </button>
      <dialog id={dialogId}>
        <form method="dialog" stoppropagation:submit> {/* <-- Not included */}
          <input type="text" />
          <button type="submit" value="ok" formMethod="dialog">
            Save
          </button>
        </form>
      </dialog>
    </form>
  );
});
```

I'm aware that <form> tag shouldn't have `<form>` tags as children, but I think with `<dialog>` this is a legit use. Also I wouldn't expect the framework to remove it. Moreover without a warning.

### Reproduction

https://stackblitz.com/edit/github-sced1jck?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

Create a component with nested <form> tag. Inspect the code in the browser, the nested form has been removed.

### System Info

```shell
System:
    OS: Windows 11 10.0.26100
    CPU: (32) x64 AMD Ryzen 9 7950X3D 16-Core Processor
    Memory: 18.63 GB / 31.18 GB
  Binaries:
    Node: 22.8.0 - ~\.nvm\versions\node\v22.8.0\bin\node.EXE
    npm: 10.9.0 - ~\.nvm\versions\node\v22.8.0\bin\npm.CMD
    pnpm: 9.12.2 - ~\.nvm\versions\node\v22.8.0\bin\pnpm.CMD
  Browsers:
    Edge: Chromium (129.0.2792.65)
    Internet Explorer: 11.0.26100.1882
  npmPackages:
    @builder.io/qwik: 1.10.0 => 1.10.0
    @builder.io/qwik-city: 1.10.0 => 1.10.0
    typescript: 5.4.5 => 5.4.5
    undici: * => 6.20.0
    vite: 5.3.5 => 5.3.5
```

### Additional Information
Usually this kind of problem can be fixed with `createPortal` to move the dialog form out of the parent form, but qwik doesn't provide this kind of solution.

**Comment by GrandSchtroumpf** [comment]
This is chrome behavior. Nothing to do with qwik.

**Comment by gioboa** [comment]
@GrandSchtroumpf Thanks for the update
